import { createHash, createPublicKey, verify, type KeyObject } from "node:crypto";
import type { StrategyInterval } from "./types";

export const CSV_AUTH_MANIFEST_VERSION = 1;
export type CsvAuthenticationFailureCode = "MALFORMED_MANIFEST" | "UNSUPPORTED_MANIFEST_VERSION" | "INVALID_BASE64" | "INVALID_KEY" | "KEY_FINGERPRINT_MISMATCH" | "UNKNOWN_KEY" | "KEY_REVOKED" | "KEY_EXPIRED" | "MANIFEST_EXPIRED" | "MANIFEST_NOT_YET_VALID" | "CSV_FINGERPRINT_MISMATCH" | "SYMBOL_MISMATCH" | "INTERVAL_MISMATCH" | "INVALID_SIGNATURE";
export interface CsvAuthenticationManifest { version: number; keyFingerprint: string; csvSha256: string; symbol: string; interval: StrategyInterval; issuedAt: number; expiresAt: number; signature: string; }
export interface TrustedCsvPublisherKey { id: number; keyFingerprint: string; publicKeySpkiBase64: string; status: "ACTIVE" | "REVOKED"; expiresAt: number | null; }
export type CsvAuthenticationResult = { status: "UNSIGNED"; observedCsvFingerprint: string; } | { status: "REJECTED"; observedCsvFingerprint: string; manifest: CsvAuthenticationManifest | null; failureCode: CsvAuthenticationFailureCode; message: string; } | { status: "VERIFIED"; observedCsvFingerprint: string; manifest: CsvAuthenticationManifest; publisherKeyId: number; };

const SHA256_HEX = /^[a-f0-9]{64}$/;
const BASE64 = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/;
function sha256(value: Buffer | string) { return createHash("sha256").update(value).digest("hex"); }
function base64(value: string): Buffer | null { const trimmed = value.trim(); if (!trimmed || !BASE64.test(trimmed)) return null; const decoded = Buffer.from(trimmed, "base64"); return decoded.length > 0 ? decoded : null; }
export function fingerprintCsvAuthenticationPublicKey(publicKeySpkiBase64: string): string { const decoded = base64(publicKeySpkiBase64); if (!decoded) throw new Error("Public key must be padded standard base64 SPKI data."); const key = createPublicKey({ key: decoded, format: "der", type: "spki" }); if (key.asymmetricKeyType !== "ed25519") throw new Error("Only Ed25519 public keys are supported."); return sha256(decoded); }
export function canonicalizeCsvAuthenticationManifest(manifest: Omit<CsvAuthenticationManifest, "signature">): string { return JSON.stringify({ version: manifest.version, keyFingerprint: manifest.keyFingerprint, csvSha256: manifest.csvSha256, symbol: manifest.symbol, interval: manifest.interval, issuedAt: manifest.issuedAt, expiresAt: manifest.expiresAt }); }
function parseManifest(manifestJson: string): CsvAuthenticationManifest | null { try { const value: unknown = JSON.parse(manifestJson); if (!value || typeof value !== "object" || Array.isArray(value)) return null; const source = value as Record<string, unknown>; const permitted = ["version", "keyFingerprint", "csvSha256", "symbol", "interval", "issuedAt", "expiresAt", "signature"]; if (Object.keys(source).some((key) => !permitted.includes(key))) return null; if (source.version !== CSV_AUTH_MANIFEST_VERSION || typeof source.keyFingerprint !== "string" || typeof source.csvSha256 !== "string" || typeof source.symbol !== "string" || typeof source.interval !== "string" || typeof source.issuedAt !== "number" || typeof source.expiresAt !== "number" || typeof source.signature !== "string") return null; if (!SHA256_HEX.test(source.keyFingerprint) || !SHA256_HEX.test(source.csvSha256) || !["5m", "15m", "1h", "4h", "1d"].includes(source.interval) || !Number.isSafeInteger(source.issuedAt) || !Number.isSafeInteger(source.expiresAt) || source.expiresAt <= source.issuedAt || !/^[A-Z0-9]{2,15}$/.test(source.symbol)) return null; return { version: source.version, keyFingerprint: source.keyFingerprint, csvSha256: source.csvSha256, symbol: source.symbol, interval: source.interval as StrategyInterval, issuedAt: source.issuedAt, expiresAt: source.expiresAt, signature: source.signature }; } catch { return null; } }
function rejected(observedCsvFingerprint: string, manifest: CsvAuthenticationManifest | null, failureCode: CsvAuthenticationFailureCode, message: string): CsvAuthenticationResult { return { status: "REJECTED", observedCsvFingerprint, manifest, failureCode, message }; }
function keyObject(value: string): KeyObject | null { try { const decoded = base64(value); if (!decoded) return null; const key = createPublicKey({ key: decoded, format: "der", type: "spki" }); return key.asymmetricKeyType === "ed25519" ? key : null; } catch { return null; } }
export function verifyCsvAuthentication(input: { csvText: string; manifestJson: string | null | undefined; symbol: string; interval: StrategyInterval; trustedKeys: TrustedCsvPublisherKey[]; now?: number; }): CsvAuthenticationResult {
  const observedCsvFingerprint = sha256(input.csvText);
  if (input.manifestJson === undefined || input.manifestJson === null || !input.manifestJson.trim()) return { status: "UNSIGNED", observedCsvFingerprint };
  const manifest = parseManifest(input.manifestJson); if (!manifest) return rejected(observedCsvFingerprint, null, "MALFORMED_MANIFEST", "Manifest must contain exactly the supported canonical signed fields.");
  const now = input.now ?? Date.now(); if (manifest.issuedAt > now + 300_000) return rejected(observedCsvFingerprint, manifest, "MANIFEST_NOT_YET_VALID", "Manifest issuedAt is more than five minutes in the future."); if (manifest.expiresAt < now) return rejected(observedCsvFingerprint, manifest, "MANIFEST_EXPIRED", "Manifest has expired."); if (manifest.csvSha256 !== observedCsvFingerprint) return rejected(observedCsvFingerprint, manifest, "CSV_FINGERPRINT_MISMATCH", "Manifest CSV fingerprint does not match the uploaded text."); if (manifest.symbol !== input.symbol.trim().toUpperCase()) return rejected(observedCsvFingerprint, manifest, "SYMBOL_MISMATCH", "Manifest symbol does not match this import."); if (manifest.interval !== input.interval) return rejected(observedCsvFingerprint, manifest, "INTERVAL_MISMATCH", "Manifest interval does not match this import.");
  const trustedKey = input.trustedKeys.find((key) => key.keyFingerprint === manifest.keyFingerprint); if (!trustedKey) return rejected(observedCsvFingerprint, manifest, "UNKNOWN_KEY", "No user-trusted publisher key matches the manifest."); if (trustedKey.status === "REVOKED") return rejected(observedCsvFingerprint, manifest, "KEY_REVOKED", "The matching publisher key has been revoked."); if (trustedKey.expiresAt !== null && trustedKey.expiresAt < now) return rejected(observedCsvFingerprint, manifest, "KEY_EXPIRED", "The matching publisher key has expired.");
  let publicKey: KeyObject | null; try { if (fingerprintCsvAuthenticationPublicKey(trustedKey.publicKeySpkiBase64) !== trustedKey.keyFingerprint) return rejected(observedCsvFingerprint, manifest, "KEY_FINGERPRINT_MISMATCH", "Stored public-key material no longer matches its registered fingerprint."); publicKey = keyObject(trustedKey.publicKeySpkiBase64); } catch { return rejected(observedCsvFingerprint, manifest, "INVALID_KEY", "Stored public key is not a valid Ed25519 SPKI key."); }
  const signature = base64(manifest.signature); if (!publicKey || !signature) return rejected(observedCsvFingerprint, manifest, "INVALID_BASE64", "Public key or signature is not valid padded standard base64."); const valid = verify(null, Buffer.from(canonicalizeCsvAuthenticationManifest(manifest), "utf8"), publicKey, signature); return valid ? { status: "VERIFIED", observedCsvFingerprint, manifest, publisherKeyId: trustedKey.id } : rejected(observedCsvFingerprint, manifest, "INVALID_SIGNATURE", "Ed25519 signature does not verify against the registered publisher key.");
}
