import { generateKeyPairSync, sign } from "node:crypto";
import { describe, expect, it } from "vitest";
import { canonicalizeCsvAuthenticationManifest, fingerprintCsvAuthenticationPublicKey, verifyCsvAuthentication } from "./csvAuth";

const csv = "timestamp,open,high,low,close,volume\n2024-01-01T00:00:00.000Z,10,11,9,10.5,1";
const now = 1_735_689_600_000;
function fixture() { const pair = generateKeyPairSync("ed25519"); const publicKeySpkiBase64 = pair.publicKey.export({ type: "spki", format: "der" }).toString("base64"); const keyFingerprint = fingerprintCsvAuthenticationPublicKey(publicKeySpkiBase64); const csvSha256 = verifyCsvAuthentication({ csvText: csv, manifestJson: null, symbol: "BTC", interval: "1h", trustedKeys: [], now }).observedCsvFingerprint; const unsigned = { version: 1, keyFingerprint, csvSha256, symbol: "BTC", interval: "1h" as const, issuedAt: now - 1_000, expiresAt: now + 86_400_000 }; const signature = sign(null, Buffer.from(canonicalizeCsvAuthenticationManifest(unsigned), "utf8"), pair.privateKey).toString("base64"); return { publicKeySpkiBase64, keyFingerprint, manifest: JSON.stringify({ ...unsigned, signature }), trustedKeys: [{ id: 3, keyFingerprint, publicKeySpkiBase64, status: "ACTIVE" as const, expiresAt: null }] }; }
describe("CSV source authentication", () => {
  it("verifies a signed canonical manifest only with the matching trusted Ed25519 key", () => { const input = fixture(); expect(verifyCsvAuthentication({ csvText: csv, manifestJson: input.manifest, symbol: "BTC", interval: "1h", trustedKeys: input.trustedKeys, now })).toMatchObject({ status: "VERIFIED", publisherKeyId: 3 }); });
  it("rejects file substitution, malformed signatures, unknown keys, expired manifests and revoked keys", () => { const input = fixture(); expect(verifyCsvAuthentication({ csvText: `${csv}\n`, manifestJson: input.manifest, symbol: "BTC", interval: "1h", trustedKeys: input.trustedKeys, now })).toMatchObject({ status: "REJECTED", failureCode: "CSV_FINGERPRINT_MISMATCH" }); expect(verifyCsvAuthentication({ csvText: csv, manifestJson: input.manifest.replace(/.$/, "x"), symbol: "BTC", interval: "1h", trustedKeys: input.trustedKeys, now })).toMatchObject({ status: "REJECTED" }); expect(verifyCsvAuthentication({ csvText: csv, manifestJson: input.manifest, symbol: "BTC", interval: "1h", trustedKeys: [], now })).toMatchObject({ status: "REJECTED", failureCode: "UNKNOWN_KEY" }); expect(verifyCsvAuthentication({ csvText: csv, manifestJson: input.manifest, symbol: "BTC", interval: "1h", trustedKeys: input.trustedKeys.map((key) => ({ ...key, status: "REVOKED" as const })), now })).toMatchObject({ status: "REJECTED", failureCode: "KEY_REVOKED" }); const expired = JSON.parse(input.manifest) as Record<string, unknown>; expired.expiresAt = now - 1; expect(verifyCsvAuthentication({ csvText: csv, manifestJson: JSON.stringify(expired), symbol: "BTC", interval: "1h", trustedKeys: input.trustedKeys, now })).toMatchObject({ status: "REJECTED", failureCode: "MANIFEST_EXPIRED" }); });
  it("keeps absent manifests explicitly unsigned rather than authenticated", () => { expect(verifyCsvAuthentication({ csvText: csv, manifestJson: null, symbol: "BTC", interval: "1h", trustedKeys: [], now })).toMatchObject({ status: "UNSIGNED" }); });
});
