import { describe, expect, it } from "vitest";
import { compareBacktestRuns, executeControlledParameterSearch, validateParameterSearchPlan } from "./research";
import type { HistoricalCandle, StrategyRiskConfig, StrategyRuleConfig } from "./types";

const candles: HistoricalCandle[] = Array.from({ length: 240 }, (_, index) => ({ openTime: index * 3_600_000, closeTime: (index + 1) * 3_600_000 - 1, open: 100 + index * 0.01, high: 101 + index * 0.01, low: 99 + index * 0.01, close: 100 + index * 0.01, volume: 10, quoteVolumeUsd: 1_000, tradeCount: 1 }));
const rules: StrategyRuleConfig = { version: 1, entry: { type: "BREAKOUT", lookback: 5 }, exit: { type: "NONE" }, requestedQuantity: 0.1 };
const risk: StrategyRiskConfig = { initialEquityUsd: 100_000, riskPerTradePercent: 1, maxDailyLossPercent: 20, maxDailyDrawdownPercent: 30, maxOpenPositions: 3, maxPortfolioExposurePercent: 80, maxAssetExposurePercent: 80, stopMethod: "fixed", fixedStopPercent: 2, atrMultiplier: 2, structureBufferBps: 25, minimumRewardRisk: 1, consecutiveLossLimit: 4, cooldownMinutes: 30, feeBps: 10, slippageBps: 10, blockHighVolatility: false };
describe("controlled parameter research", () => {
  it("caps search space and requires three chronological non-overlapping periods", () => { expect(() => validateParameterSearchPlan({ ranges: [{ key: "entry.lookback", start: 2, end: 200, step: 1 }], periodSplit: { trainingPercent: 1 / 3, validationPercent: 1 / 3 } }, candles.length)).toThrow(/maximum/i); const result = validateParameterSearchPlan({ ranges: [{ key: "entry.lookback", start: 4, end: 6, step: 1 }], periodSplit: { trainingPercent: 1 / 3, validationPercent: 1 / 3 } }, candles.length); expect(result.combinations).toHaveLength(3); expect(result.periods[0]!.endIndexExclusive).toBe(result.periods[1]!.startIndex); });
  it("is deterministic, preserves candidate fingerprints, and keeps risk-engine outcomes", () => { const input = { symbol: "BTC", interval: "1h" as const, source: "coinbase" as const, datasetFingerprint: "a".repeat(64), candles, rules, risk, plan: { ranges: [{ key: "entry.lookback" as const, start: 4, end: 5, step: 1 }], periodSplit: { trainingPercent: 1 / 3, validationPercent: 1 / 3 } } }; const first = executeControlledParameterSearch(input); const second = executeControlledParameterSearch(input); expect(first).toEqual(second); expect(first.candidates[0]?.fingerprint).toMatch(/^[a-f0-9]{64}$/); expect(first.candidates[0]?.results).toHaveLength(3); });
  it("compares stored metrics without presenting an optimization claim", () => { const metrics = { initialEquityUsd: 100, finalEquityUsd: 110, netPnlUsd: 10, netPnlPercent: 10, tradeCount: 2, acceptedDecisionCount: 2, rejectedDecisionCount: 0, winCount: 1, lossCount: 1, winRatePercent: 50, profitFactor: 2, maxDrawdownPercent: 4, maximumExposurePercent: 10, averageExposurePercent: 5, stopEventCount: 0, targetEventCount: 1, ruleExitCount: 1, endOfDataExitCount: 0 }; const result = compareBacktestRuns([{ id: 1, strategyRevisionNumber: 1, datasetFingerprint: "a", rangeStart: 1, rangeEnd: 2, interval: "1h", runConfig: {}, metrics, averageTradeUsd: 5, returnToDrawdownRatio: 2.5 }, { id: 2, strategyRevisionNumber: 2, datasetFingerprint: "b", rangeStart: 3, rangeEnd: 4, interval: "1h", runConfig: {}, metrics: { ...metrics, netPnlUsd: 12 }, averageTradeUsd: 6, returnToDrawdownRatio: 3 }]); expect(result.runs[1]?.differences.netPnlUsd).toBe(2); expect(result.disclaimer).toMatch(/do not establish future/i); });
});
