import { createHash } from "node:crypto";
import { normalizeRiskSettings } from "../risk/settings";
import { runDeterministicBacktest } from "./backtest";
import { validateRuleConfig } from "./rules";
import type { BacktestMetrics, BacktestResult, HistoricalCandle, StrategyRiskConfig, StrategyRuleConfig } from "./types";
import { StrategyValidationError } from "./types";

export const MAX_PARAMETER_COMBINATIONS = 100;
export const MAX_PARAMETER_CANDLE_EXECUTIONS = 30_000;
export const MIN_PERIOD_CANDLES = 80;
export type ParameterKey = "risk.fixedStopPercent" | "risk.minimumRewardRisk" | "entry.fastPeriod" | "entry.slowPeriod" | "entry.oversoldThreshold" | "entry.lookback";
export interface ParameterRange { key: ParameterKey; start: number; end: number; step: number; }
export interface PeriodSplit { trainingPercent: number; validationPercent: number; }
export interface ParameterSearchPlan { ranges: ParameterRange[]; periodSplit: PeriodSplit; }
export interface SearchPeriod { label: "TRAINING" | "VALIDATION" | "OUT_OF_SAMPLE"; startIndex: number; endIndexExclusive: number; candles: HistoricalCandle[]; }
export interface SearchCandidate { sequence: number; parameters: Record<ParameterKey, number>; fingerprint: string; rules: StrategyRuleConfig; risk: StrategyRiskConfig; results: Array<{ period: SearchPeriod["label"]; result: BacktestResult; warnings: string[] }>; warnings: string[]; }
export interface RobustnessAnalysis { candidateCount: number; completedCandidateCount: number; netPnlPercentStdDev: number | null; maxDrawdownPercentStdDev: number | null; tradeCountStdDev: number | null; warnings: string[]; }
export class ParameterSearchError extends Error { constructor(message: string) { super(message); this.name = "ParameterSearchError"; } }
function hash(value: unknown): string { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function standardDeviation(values: number[]): number | null { if (values.length < 2) return null; const mean = values.reduce((sum, value) => sum + value, 0) / values.length; return Math.sqrt(values.reduce((sum, value) => sum + (value - mean) ** 2, 0) / values.length); }
function rangeValues(range: ParameterRange): number[] { if (!Number.isFinite(range.start) || !Number.isFinite(range.end) || !Number.isFinite(range.step) || range.step <= 0 || range.end < range.start) throw new ParameterSearchError(`Invalid range for ${range.key}.`); const count = Math.floor((range.end - range.start) / range.step + 1e-9) + 1; if (count > MAX_PARAMETER_COMBINATIONS) throw new ParameterSearchError(`Range for ${range.key} exceeds the maximum discrete range length.`); const last = range.start + (count - 1) * range.step; if (Math.abs(last - range.end) > 1e-7) throw new ParameterSearchError(`Step for ${range.key} must land exactly on the range end.`); return Array.from({ length: count }, (_, index) => Number((range.start + index * range.step).toFixed(8))); }
export function validateParameterSearchPlan(plan: ParameterSearchPlan, candleCount: number): { combinations: Array<Record<ParameterKey, number>>; periods: Array<Pick<SearchPeriod, "label" | "startIndex" | "endIndexExclusive">> } {
  if (!plan.ranges.length || plan.ranges.length > 4) throw new ParameterSearchError("Parameter search requires 1 to 4 explicitly supported ranges."); const keys = new Set(plan.ranges.map((range) => range.key)); if (keys.size !== plan.ranges.length) throw new ParameterSearchError("Parameter ranges must not repeat a key."); const values = plan.ranges.map(rangeValues); const count = values.reduce((product, items) => product * items.length, 1); if (count > MAX_PARAMETER_COMBINATIONS) throw new ParameterSearchError(`Search has ${count} combinations; maximum is ${MAX_PARAMETER_COMBINATIONS}.`); const { trainingPercent, validationPercent } = plan.periodSplit; if (!Number.isFinite(trainingPercent) || !Number.isFinite(validationPercent) || trainingPercent <= 0 || validationPercent <= 0 || trainingPercent + validationPercent >= 1) throw new ParameterSearchError("Training and validation percentages must be positive and leave a non-empty out-of-sample period."); if (count * candleCount > MAX_PARAMETER_CANDLE_EXECUTIONS) throw new ParameterSearchError(`Search would evaluate ${count * candleCount} candle-configurations; maximum is ${MAX_PARAMETER_CANDLE_EXECUTIONS}.`); const trainingEnd = Math.floor(candleCount * trainingPercent); const validationEnd = trainingEnd + Math.floor(candleCount * validationPercent); const periods = [{ label: "TRAINING" as const, startIndex: 0, endIndexExclusive: trainingEnd }, { label: "VALIDATION" as const, startIndex: trainingEnd, endIndexExclusive: validationEnd }, { label: "OUT_OF_SAMPLE" as const, startIndex: validationEnd, endIndexExclusive: candleCount }]; if (periods.some((period) => period.endIndexExclusive - period.startIndex < MIN_PERIOD_CANDLES)) throw new ParameterSearchError(`Each chronological period requires at least ${MIN_PERIOD_CANDLES} candles.`); const combinations: Array<Record<ParameterKey, number>> = []; const enumerate = (depth: number, current: Partial<Record<ParameterKey, number>>) => { if (depth === plan.ranges.length) { combinations.push(current as Record<ParameterKey, number>); return; } const range = plan.ranges[depth]!; for (const value of values[depth]!) enumerate(depth + 1, { ...current, [range.key]: value }); }; enumerate(0, {}); return { combinations, periods };
}
function candidateConfig(baseRules: StrategyRuleConfig, baseRisk: StrategyRiskConfig, parameters: Record<ParameterKey, number>) { const rules: StrategyRuleConfig = structuredClone(baseRules); const risk: StrategyRiskConfig = { ...baseRisk }; for (const [key, value] of Object.entries(parameters) as Array<[ParameterKey, number]>) { if (key === "risk.fixedStopPercent") risk.fixedStopPercent = value; else if (key === "risk.minimumRewardRisk") risk.minimumRewardRisk = value; else if (key === "entry.fastPeriod") { if (rules.entry.type !== "SMA_CROSSOVER") throw new ParameterSearchError("entry.fastPeriod requires an SMA-crossover entry rule."); rules.entry.fastPeriod = Math.round(value); } else if (key === "entry.slowPeriod") { if (rules.entry.type !== "SMA_CROSSOVER") throw new ParameterSearchError("entry.slowPeriod requires an SMA-crossover entry rule."); rules.entry.slowPeriod = Math.round(value); } else if (key === "entry.oversoldThreshold") { if (rules.entry.type !== "RSI_RECOVERY") throw new ParameterSearchError("entry.oversoldThreshold requires an RSI-recovery entry rule."); rules.entry.oversoldThreshold = value; } else if (key === "entry.lookback") { if (rules.entry.type !== "BREAKOUT") throw new ParameterSearchError("entry.lookback requires a breakout entry rule."); rules.entry.lookback = Math.round(value); } }
  try { return { rules: validateRuleConfig(rules), risk: { ...normalizeRiskSettings(risk), initialEquityUsd: risk.initialEquityUsd } }; } catch (error) { throw new ParameterSearchError(error instanceof Error ? error.message : "Candidate parameters are invalid."); }
}
function resultWarnings(metrics: BacktestMetrics, period: SearchPeriod["label"]): string[] { const warnings: string[] = []; if (metrics.tradeCount < 10) warnings.push(`${period}: fewer than 10 closed trades; performance estimates are unstable.`); if (metrics.maxDrawdownPercent >= 20) warnings.push(`${period}: maximum drawdown is at least 20%.`); return warnings; }
export function executeControlledParameterSearch(input: { symbol: string; interval: StrategyRiskConfig extends never ? never : "5m" | "15m" | "1h" | "4h" | "1d"; source: "binance" | "coinbase" | "user_imported_unverified"; datasetFingerprint: string; candles: HistoricalCandle[]; rules: StrategyRuleConfig; risk: StrategyRiskConfig; plan: ParameterSearchPlan; }): { candidates: SearchCandidate[]; robustness: RobustnessAnalysis; periods: SearchPeriod[] } {
  const validated = validateParameterSearchPlan(input.plan, input.candles.length); const periods = validated.periods.map((period) => ({ ...period, candles: input.candles.slice(period.startIndex, period.endIndexExclusive) })); const candidates: SearchCandidate[] = validated.combinations.map((parameters, index) => { const config = candidateConfig(input.rules, input.risk, parameters); const fingerprint = hash({ dataset: input.datasetFingerprint, rules: config.rules, risk: config.risk, parameters, engine: "2.3.0" }); const results = periods.map((period) => { const result = runDeterministicBacktest({ symbol: input.symbol, interval: input.interval, source: input.source === "user_imported_unverified" ? "coinbase" : input.source, datasetFingerprint: `${input.datasetFingerprint}:${period.label}`, candles: period.candles, rules: config.rules, risk: config.risk }); return { period: period.label, result, warnings: resultWarnings(result.metrics, period.label) }; }); const training = results[0]!.result.metrics; const validation = results[1]!.result.metrics; const warnings = [...results.flatMap((result) => result.warnings)]; if (training.netPnlPercent > 0 && validation.netPnlPercent < 0) warnings.push("Training-positive and validation-negative performance indicates possible overfitting."); if (Math.abs(training.netPnlPercent - validation.netPnlPercent) >= 20) warnings.push("Large training/validation return gap indicates parameter sensitivity."); return { sequence: index + 1, parameters, fingerprint, rules: config.rules, risk: config.risk, results, warnings }; }); const trainingMetrics = candidates.map((candidate) => candidate.results.find((result) => result.period === "TRAINING")!.result.metrics); const robustnessWarnings: string[] = []; const pnlStd = standardDeviation(trainingMetrics.map((metrics) => metrics.netPnlPercent)); const drawdownStd = standardDeviation(trainingMetrics.map((metrics) => metrics.maxDrawdownPercent)); const tradesStd = standardDeviation(trainingMetrics.map((metrics) => metrics.tradeCount)); if (pnlStd !== null && pnlStd >= 15) robustnessWarnings.push("Training return varies materially across tested parameters; sensitivity is high."); if (drawdownStd !== null && drawdownStd >= 10) robustnessWarnings.push("Drawdown varies materially across tested parameters; drawdown stability is low."); if (trainingMetrics.some((metrics) => metrics.tradeCount < 10)) robustnessWarnings.push("At least one candidate has fewer than 10 closed training trades."); return { candidates, robustness: { candidateCount: candidates.length, completedCandidateCount: candidates.length, netPnlPercentStdDev: pnlStd, maxDrawdownPercentStdDev: drawdownStd, tradeCountStdDev: tradesStd, warnings: robustnessWarnings }, periods };
}

export interface ComparableRun { id: number; strategyRevisionNumber: number; datasetFingerprint: string; rangeStart: number; rangeEnd: number; interval: string; runConfig: Record<string, unknown>; metrics: BacktestMetrics; averageTradeUsd: number | null; returnToDrawdownRatio: number | null; }
export function compareBacktestRuns(runs: ComparableRun[]) { if (runs.length < 2 || runs.length > 5) throw new StrategyValidationError("Compare from 2 to 5 completed backtest runs."); const baseline = runs[0]!; return { baselineRunId: baseline.id, runs: runs.map((run) => ({ ...run, differences: { netPnlUsd: run.metrics.netPnlUsd - baseline.metrics.netPnlUsd, netPnlPercent: run.metrics.netPnlPercent - baseline.metrics.netPnlPercent, winRatePercent: (run.metrics.winRatePercent ?? 0) - (baseline.metrics.winRatePercent ?? 0), maxDrawdownPercent: run.metrics.maxDrawdownPercent - baseline.metrics.maxDrawdownPercent, tradeCount: run.metrics.tradeCount - baseline.metrics.tradeCount, averageTradeUsd: run.averageTradeUsd === null || baseline.averageTradeUsd === null ? null : run.averageTradeUsd - baseline.averageTradeUsd, returnToDrawdownRatio: run.returnToDrawdownRatio === null || baseline.returnToDrawdownRatio === null ? null : run.returnToDrawdownRatio - baseline.returnToDrawdownRatio } })), disclaimer: "Historical comparisons describe stored simulations only. They do not establish future performance." };
}
