import { beforeEach, describe, expect, it, vi } from "vitest";
import type { TrpcContext } from "../_core/context";

vi.mock("../services/marketData", () => ({
  exchangeIntervals: ["1m", "5m", "15m", "1h", "4h", "1d"], marketOrders: ["market_cap_desc", "market_cap_asc", "volume_desc", "volume_asc", "id_asc", "id_desc"],
  getMarketDirectory: vi.fn(), searchMarketDirectory: vi.fn(), getAssetMarketDetail: vi.fn(), getLiveQuote: vi.fn(), getLiveCandles: vi.fn(), getLiveActiveCandle: vi.fn(), getLiveHistoricalCandlePage: vi.fn(), getLiveOrderBook: vi.fn(), getLiveTrades: vi.fn(), getLiveTradingContext: vi.fn(), serializeMarketDataError: vi.fn((error: Error) => ({ code: "UNAVAILABLE", message: error.message, retryAfterSeconds: null })),
}));
import { getLiveActiveCandle, getLiveHistoricalCandlePage } from "../services/marketData";
vi.mock("../services/chartViewPreferences", () => ({ getChartViewPreference: vi.fn(), saveChartViewPreference: vi.fn() }));
import { getChartViewPreference, saveChartViewPreference } from "../services/chartViewPreferences";
import { marketDataRouter } from "./marketData";

const authenticated = (): TrpcContext => ({ user: { id: 33, openId: "market-history-user", email: null, name: null, loginMethod: "manus", role: "user", createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() }, req: { protocol: "https", headers: {} } as TrpcContext["req"], res: {} as TrpcContext["res"] });
const anonymous = (): TrpcContext => ({ ...authenticated(), user: null });
describe("marketData liveHistoryPage router", () => {
  beforeEach(() => vi.clearAllMocks());
  it("requires an authenticated caller before reaching the provider-history service", async () => { const caller = marketDataRouter.createCaller(anonymous()); await expect(caller.liveHistoryPage({ symbol: "BTC", interval: "1h", source: "binance", startTime: 1_725_000_000_000, endTime: 1_725_003_600_000_000, limit: 20 })).rejects.toMatchObject({ code: "UNAUTHORIZED" }); expect(getLiveHistoricalCandlePage).not.toHaveBeenCalled(); });
  it("passes the explicit provider UTC range without changing source", async () => { vi.mocked(getLiveHistoricalCandlePage).mockResolvedValue({ source: "coinbase", candles: [], coverage: { status: "EMPTY" } } as never); const input = { symbol: "ETH", interval: "1h" as const, source: "coinbase" as const, startTime: 1_725_000_000_000, endTime: 1_725_003_600_000_000, limit: 20 }; const caller = marketDataRouter.createCaller(authenticated()); await expect(caller.liveHistoryPage(input)).resolves.toMatchObject({ success: true, data: { source: "coinbase" } }); expect(getLiveHistoricalCandlePage).toHaveBeenCalledWith(input); });
  it("rejects an unordered UTC range before provider work", async () => { const caller = marketDataRouter.createCaller(authenticated()); await expect(caller.liveHistoryPage({ symbol: "BTC", interval: "1h", source: "binance", startTime: 1_725_003_600_000_000, endTime: 1_725_000_000_000, limit: 20 })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(getLiveHistoricalCandlePage).not.toHaveBeenCalled(); });
  it("scopes chart-view preference reads and writes to the authenticated user", async () => { vi.mocked(getChartViewPreference).mockResolvedValue(null); vi.mocked(saveChartViewPreference).mockResolvedValue({ assetSymbol: "BTC", source: "binance", interval: "1h", requestedStart: 1_725_000_000_000, requestedEnd: 1_725_003_600_000_000, visibleCandles: 80, updatedAt: 1_725_003_600_000_000 }); const caller = marketDataRouter.createCaller(authenticated()); await expect(caller.getChartViewPreference({ assetSymbol: "BTC", source: "binance", interval: "1h" })).resolves.toBeNull(); await expect(caller.saveChartViewPreference({ assetSymbol: "BTC", source: "binance", interval: "1h", requestedStart: 1_725_000_000_000, requestedEnd: 1_725_003_600_000_000, visibleCandles: 80 })).resolves.toMatchObject({ assetSymbol: "BTC" }); expect(getChartViewPreference).toHaveBeenCalledWith(33, { assetSymbol: "BTC", source: "binance", interval: "1h" }); expect(saveChartViewPreference).toHaveBeenCalledWith(33, expect.objectContaining({ visibleCandles: 80 })); });
  it("rejects an invalid saved range before persistence", async () => { const caller = marketDataRouter.createCaller(authenticated()); await expect(caller.saveChartViewPreference({ assetSymbol: "BTC", source: "binance", interval: "1h", requestedStart: 1_725_003_600_000_000, requestedEnd: 1_725_000_000_000, visibleCandles: 80 })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(saveChartViewPreference).not.toHaveBeenCalled(); });
  it("passes the active-candle request to its explicit provider without a source fallback", async () => { vi.mocked(getLiveActiveCandle).mockResolvedValue({ source: "coinbase", candle: { openTime: 1_725_000_000_000 } } as never); const caller = marketDataRouter.createCaller(anonymous()); const input = { symbol: "SOL", interval: "15m" as const, source: "coinbase" as const }; await expect(caller.activeCandle(input)).resolves.toMatchObject({ success: true, data: { source: "coinbase" } }); expect(getLiveActiveCandle).toHaveBeenCalledWith(input); });
});
