import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { protectedProcedure, router } from "../_core/trpc";
import { StrategyLabError, archivePaperStrategy, captureHistoricalDataset, createPaperStrategy, defaultStrategyRiskConfig, duplicatePaperStrategy, getBacktestDatasetCandles, getBacktestRun, getPaperStrategy, getStrategyLabAuditHistory, getStrategyLabEntitlement, importHistoricalOhlcvCsv, listPaperStrategies, listTrustedCsvPublisherKeys, previewCsvSourceAuthentication, registerTrustedCsvPublisherKey, revokeTrustedCsvPublisherKey, revisePaperStrategy, runPaperStrategyBacktest } from "../services/strategyLab";
import { getControlledParameterSearch, getFeatureEntitlementDefinitions, launchControlledParameterSearch, listRecentBacktestRuns, listVerifiedDatasets, saveBacktestRunComparison } from "../services/strategyLabResearch";
import { StrategyValidationError } from "../strategy/types";
import { consumeEntitlementUsage, EntitlementError, requireEntitlement } from "../services/entitlementService";

const interval = z.enum(["5m", "15m", "1h", "4h", "1d"]);
const entry = z.discriminatedUnion("type", [z.object({ type: z.literal("SMA_CROSSOVER"), fastPeriod: z.number().int(), slowPeriod: z.number().int() }), z.object({ type: z.literal("RSI_RECOVERY"), period: z.number().int(), oversoldThreshold: z.number().finite() }), z.object({ type: z.literal("BREAKOUT"), lookback: z.number().int() })]);
const exit = z.discriminatedUnion("type", [z.object({ type: z.literal("NONE") }), z.object({ type: z.literal("SMA_CROSSUNDER"), fastPeriod: z.number().int(), slowPeriod: z.number().int() }), z.object({ type: z.literal("RSI_OVERBOUGHT"), period: z.number().int(), overboughtThreshold: z.number().finite() })]);
const strategyInput = z.object({ name: z.string().trim().min(1).max(100), description: z.string().trim().max(2000).nullable().optional(), symbol: z.string().trim().min(2).max(15), interval, status: z.enum(["DRAFT", "ACTIVE"]).optional(), rules: z.object({ version: z.literal(1), entry, exit, requestedQuantity: z.number().finite().positive() }), risk: z.object({ initialEquityUsd: z.number().finite().positive(), riskPerTradePercent: z.number().finite(), maxDailyLossPercent: z.number().finite(), maxDailyDrawdownPercent: z.number().finite(), maxOpenPositions: z.number().int(), maxPortfolioExposurePercent: z.number().finite(), maxAssetExposurePercent: z.number().finite(), stopMethod: z.enum(["fixed", "atr", "structure"]), fixedStopPercent: z.number().finite(), atrMultiplier: z.number().finite(), structureBufferBps: z.number().int(), minimumRewardRisk: z.number().finite(), consecutiveLossLimit: z.number().int(), cooldownMinutes: z.number().int(), feeBps: z.number().int(), slippageBps: z.number().int(), blockHighVolatility: z.boolean() }) }).superRefine((value, ctx) => {
  const validateCross = (rule: { fastPeriod: number; slowPeriod: number }, path: (string | number)[]) => { if (rule.fastPeriod < 2 || rule.slowPeriod > 200 || rule.fastPeriod >= rule.slowPeriod) ctx.addIssue({ code: "custom", path, message: "Fast period must be at least 2 and lower than slow period (maximum 200)." }); };
  if (value.rules.entry.type === "SMA_CROSSOVER") validateCross(value.rules.entry, ["rules", "entry"]);
  if (value.rules.exit.type === "SMA_CROSSUNDER") validateCross(value.rules.exit, ["rules", "exit"]);
  if (value.rules.entry.type === "BREAKOUT" && (value.rules.entry.lookback < 2 || value.rules.entry.lookback > 180)) ctx.addIssue({ code: "custom", path: ["rules", "entry", "lookback"], message: "Breakout lookback must be 2 to 180." });
  if ((value.rules.entry.type === "RSI_RECOVERY" && (value.rules.entry.period < 2 || value.rules.entry.period > 200 || value.rules.entry.oversoldThreshold < 5 || value.rules.entry.oversoldThreshold > 45)) || (value.rules.exit.type === "RSI_OVERBOUGHT" && (value.rules.exit.period < 2 || value.rules.exit.period > 200 || value.rules.exit.overboughtThreshold < 55 || value.rules.exit.overboughtThreshold > 95))) ctx.addIssue({ code: "custom", path: ["rules"], message: "RSI rule parameters are outside their safe range." });
});
const datasetInput = z.object({ symbol: z.string().trim().min(2).max(15), interval, startTime: z.number().int().nonnegative(), endTime: z.number().int().positive() });
const parameterKey = z.enum(["risk.fixedStopPercent", "risk.minimumRewardRisk", "entry.fastPeriod", "entry.slowPeriod", "entry.oversoldThreshold", "entry.lookback"]);
const parameterSearchInput = z.object({ strategyId: z.number().int().positive(), datasetId: z.number().int().positive(), plan: z.object({ ranges: z.array(z.object({ key: parameterKey, start: z.number().finite(), end: z.number().finite(), step: z.number().finite() })).min(1).max(4), periodSplit: z.object({ trainingPercent: z.number().finite(), validationPercent: z.number().finite() }) }) });
const csvAuthenticationInput = z.object({ csvText: z.string().min(1).max(2_000_000), symbol: z.string().trim().min(2).max(15), interval, manifestJson: z.string().trim().min(2).max(16_000).nullable().optional() });
function rethrow(error: unknown): never { if (error instanceof EntitlementError) throw new TRPCError({ code: "PRECONDITION_FAILED", message: error.message, cause: error.decision }); if (error instanceof StrategyLabError) throw new TRPCError({ code: error.code === "NOT_FOUND" ? "NOT_FOUND" : error.code === "FORBIDDEN" ? "FORBIDDEN" : error.code === "UNAVAILABLE" ? "PRECONDITION_FAILED" : "BAD_REQUEST", message: error.message }); if (error instanceof StrategyValidationError) throw new TRPCError({ code: "BAD_REQUEST", message: error.message }); throw error; }

export const strategyLabRouter = router({
  getEntitlement: protectedProcedure.query(({ ctx }) => getStrategyLabEntitlement(ctx.user.id)),
  getFeatureEntitlements: protectedProcedure.query(() => getFeatureEntitlementDefinitions()),
  getDefaults: protectedProcedure.query(() => ({ risk: defaultStrategyRiskConfig(), simulationOnly: true as const })),
  list: protectedProcedure.query(async ({ ctx }) => { try { return await listPaperStrategies(ctx.user.id); } catch (error) { return rethrow(error); } }),
  get: protectedProcedure.input(z.object({ strategyId: z.number().int().positive() })).query(async ({ ctx, input }) => { try { return await getPaperStrategy(ctx.user.id, input.strategyId); } catch (error) { return rethrow(error); } }),
  create: protectedProcedure.input(strategyInput).mutation(async ({ ctx, input }) => { try { await requireEntitlement(ctx.user.id, "strategy_lab"); const strategy = await createPaperStrategy(ctx.user.id, input); await consumeEntitlementUsage(ctx.user.id, "strategy_lab"); return strategy; } catch (error) { return rethrow(error); } }),
  update: protectedProcedure.input(z.object({ strategyId: z.number().int().positive(), strategy: strategyInput })).mutation(async ({ ctx, input }) => { try { return await revisePaperStrategy(ctx.user.id, input.strategyId, input.strategy); } catch (error) { return rethrow(error); } }),
  duplicate: protectedProcedure.input(z.object({ strategyId: z.number().int().positive(), name: z.string().trim().min(1).max(100) })).mutation(async ({ ctx, input }) => { try { await requireEntitlement(ctx.user.id, "strategy_lab"); const strategy = await duplicatePaperStrategy(ctx.user.id, input.strategyId, input.name); await consumeEntitlementUsage(ctx.user.id, "strategy_lab"); return strategy; } catch (error) { return rethrow(error); } }),
  archive: protectedProcedure.input(z.object({ strategyId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { try { return await archivePaperStrategy(ctx.user.id, input.strategyId); } catch (error) { return rethrow(error); } }),
  captureDataset: protectedProcedure.input(datasetInput).mutation(async ({ ctx, input }) => { try { return await captureHistoricalDataset(ctx.user.id, input); } catch (error) { return rethrow(error); } }),
  listTrustedPublisherKeys: protectedProcedure.query(async ({ ctx }) => { try { return await listTrustedCsvPublisherKeys(ctx.user.id); } catch (error) { return rethrow(error); } }),
  registerTrustedPublisherKey: protectedProcedure.input(z.object({ displayName: z.string().trim().min(1).max(120), publicKeySpkiBase64: z.string().trim().min(16).max(1024), expiresAt: z.number().int().positive().nullable().optional() })).mutation(async ({ ctx, input }) => { try { return await registerTrustedCsvPublisherKey(ctx.user.id, input); } catch (error) { return rethrow(error); } }),
  revokeTrustedPublisherKey: protectedProcedure.input(z.object({ keyId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { try { return await revokeTrustedCsvPublisherKey(ctx.user.id, input.keyId); } catch (error) { return rethrow(error); } }),
  previewCsvAuthentication: protectedProcedure.input(csvAuthenticationInput).mutation(async ({ ctx, input }) => { try { return await previewCsvSourceAuthentication(ctx.user.id, input); } catch (error) { return rethrow(error); } }),
  importCsvDataset: protectedProcedure.input(z.object({ fileName: z.string().trim().min(1).max(255), sourceLabel: z.string().trim().min(1).max(120), ...csvAuthenticationInput.shape })).mutation(async ({ ctx, input }) => { try { return await importHistoricalOhlcvCsv(ctx.user.id, input); } catch (error) { return rethrow(error); } }),
  listDatasets: protectedProcedure.query(async ({ ctx }) => { try { return await listVerifiedDatasets(ctx.user.id); } catch (error) { return rethrow(error); } }),
  listRuns: protectedProcedure.query(async ({ ctx }) => { try { return await listRecentBacktestRuns(ctx.user.id); } catch (error) { return rethrow(error); } }),
  run: protectedProcedure.input(z.object({ strategyId: z.number().int().positive(), dataset: datasetInput.omit({ symbol: true, interval: true }) })).mutation(async ({ ctx, input }) => { try { await requireEntitlement(ctx.user.id, "backtesting_basic"); const strategy = await getPaperStrategy(ctx.user.id, input.strategyId); const run = await runPaperStrategyBacktest(ctx.user.id, input.strategyId, { ...input.dataset, symbol: strategy.symbol, interval: strategy.interval }); await consumeEntitlementUsage(ctx.user.id, "backtesting_basic"); return run; } catch (error) { return rethrow(error); } }),
  getRun: protectedProcedure.input(z.object({ runId: z.number().int().positive() })).query(async ({ ctx, input }) => { try { return await getBacktestRun(ctx.user.id, input.runId); } catch (error) { return rethrow(error); } }),
  getDatasetCandles: protectedProcedure.input(z.object({ datasetId: z.number().int().positive(), limit: z.number().int().min(20).max(300).default(120), beforeSequence: z.number().int().positive().nullable().optional() })).query(async ({ ctx, input }) => { try { return await getBacktestDatasetCandles(ctx.user.id, input.datasetId, input.limit, input.beforeSequence ?? null); } catch (error) { return rethrow(error); } }),
  compareRuns: protectedProcedure.input(z.object({ runIds: z.array(z.number().int().positive()).min(2).max(5) })).mutation(async ({ ctx, input }) => { try { await requireEntitlement(ctx.user.id, "backtesting_advanced"); const comparison = await saveBacktestRunComparison(ctx.user.id, input.runIds); await consumeEntitlementUsage(ctx.user.id, "backtesting_advanced"); return comparison; } catch (error) { return rethrow(error); } }),
  launchParameterSearch: protectedProcedure.input(parameterSearchInput).mutation(async ({ ctx, input }) => { try { await requireEntitlement(ctx.user.id, "parameter_search"); const search = await launchControlledParameterSearch(ctx.user.id, input); await consumeEntitlementUsage(ctx.user.id, "parameter_search"); return search; } catch (error) { return rethrow(error); } }),
  getParameterSearch: protectedProcedure.input(z.object({ searchId: z.number().int().positive() })).query(async ({ ctx, input }) => { try { return await getControlledParameterSearch(ctx.user.id, input.searchId); } catch (error) { return rethrow(error); } }),
  getAuditHistory: protectedProcedure.input(z.object({ page: z.number().int().min(0).optional(), pageSize: z.number().int().min(1).max(50).optional() }).optional()).query(async ({ ctx, input }) => { try { return await getStrategyLabAuditHistory(ctx.user.id, input?.page ?? 0, input?.pageSize ?? 20); } catch (error) { return rethrow(error); } }),
});
