import { beforeEach, describe, expect, it, vi } from "vitest";
import type { TrpcContext } from "../_core/context";

vi.mock("../services/strategyLab", () => ({
  StrategyLabError: class StrategyLabError extends Error { constructor(public code: string, message: string) { super(message); } },
  getStrategyLabEntitlement: vi.fn(), defaultStrategyRiskConfig: vi.fn(), listPaperStrategies: vi.fn(), getPaperStrategy: vi.fn(), createPaperStrategy: vi.fn(), revisePaperStrategy: vi.fn(), duplicatePaperStrategy: vi.fn(), archivePaperStrategy: vi.fn(), captureHistoricalDataset: vi.fn(), importHistoricalOhlcvCsv: vi.fn(), listTrustedCsvPublisherKeys: vi.fn(), registerTrustedCsvPublisherKey: vi.fn(), revokeTrustedCsvPublisherKey: vi.fn(), previewCsvSourceAuthentication: vi.fn(), runPaperStrategyBacktest: vi.fn(), getBacktestRun: vi.fn(), getStrategyLabAuditHistory: vi.fn(),
}));
vi.mock("../services/strategyLabResearch", () => ({ getFeatureEntitlementDefinitions: vi.fn(), listVerifiedDatasets: vi.fn(), saveBacktestRunComparison: vi.fn(), launchControlledParameterSearch: vi.fn(), getControlledParameterSearch: vi.fn() }));
vi.mock("../services/entitlementService", () => ({ EntitlementError: class EntitlementError extends Error {}, requireEntitlement: vi.fn(), consumeEntitlementUsage: vi.fn() }));
import { createPaperStrategy, getPaperStrategy, importHistoricalOhlcvCsv, previewCsvSourceAuthentication, registerTrustedCsvPublisherKey, runPaperStrategyBacktest } from "../services/strategyLab";
import { launchControlledParameterSearch } from "../services/strategyLabResearch";
import { consumeEntitlementUsage, requireEntitlement } from "../services/entitlementService";
import { strategyLabRouter } from "./strategyLab";

function context(): TrpcContext { return { user: { id: 91, openId: "strategy-user", email: null, name: null, loginMethod: "manus", role: "user", createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() }, req: { protocol: "https", headers: {} } as TrpcContext["req"], res: {} as TrpcContext["res"] }; }
const strategy = { name: "BTC rule", description: null, symbol: "BTC", interval: "1h" as const, status: "ACTIVE" as const, rules: { version: 1 as const, entry: { type: "SMA_CROSSOVER" as const, fastPeriod: 10, slowPeriod: 30 }, exit: { type: "NONE" as const }, requestedQuantity: 0.1 }, risk: { initialEquityUsd: 100_000, riskPerTradePercent: 1, maxDailyLossPercent: 3, maxDailyDrawdownPercent: 5, maxOpenPositions: 3, maxPortfolioExposurePercent: 60, maxAssetExposurePercent: 30, stopMethod: "fixed" as const, fixedStopPercent: 3, atrMultiplier: 2, structureBufferBps: 25, minimumRewardRisk: 1.5, consecutiveLossLimit: 3, cooldownMinutes: 30, feeBps: 10, slippageBps: 10, blockHighVolatility: true } };

describe("strategyLab router", () => {
  beforeEach(() => vi.clearAllMocks());
  it("creates a strategy only in the authenticated caller scope after a server-side entitlement decision", async () => { vi.mocked(createPaperStrategy).mockResolvedValue({ id: 7, ...strategy } as never); const caller = strategyLabRouter.createCaller(context()); await expect(caller.create(strategy)).resolves.toMatchObject({ id: 7 }); expect(requireEntitlement).toHaveBeenCalledWith(91, "strategy_lab"); expect(createPaperStrategy).toHaveBeenCalledWith(91, strategy); expect(consumeEntitlementUsage).toHaveBeenCalledWith(91, "strategy_lab"); });
  it("rejects an invalid crossover before reaching persistence", async () => { const caller = strategyLabRouter.createCaller(context()); await expect(caller.create({ ...strategy, rules: { ...strategy.rules, entry: { type: "SMA_CROSSOVER", fastPeriod: 40, slowPeriod: 20 } } })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(createPaperStrategy).not.toHaveBeenCalled(); });
  it("loads strategy metadata then launches the historical service with explicit UTC dates", async () => { vi.mocked(getPaperStrategy).mockResolvedValue({ id: 7, symbol: "BTC", interval: "1h", revision: {} } as never); vi.mocked(runPaperStrategyBacktest).mockResolvedValue({ id: 3, simulation: true } as never); const caller = strategyLabRouter.createCaller(context()); await expect(caller.run({ strategyId: 7, dataset: { startTime: 1_700_000_000_000, endTime: 1_700_360_000_000 } })).resolves.toMatchObject({ id: 3 }); expect(requireEntitlement).toHaveBeenCalledWith(91, "backtesting_basic"); expect(runPaperStrategyBacktest).toHaveBeenCalledWith(91, 7, { symbol: "BTC", interval: "1h", startTime: 1_700_000_000_000, endTime: 1_700_360_000_000 }); expect(consumeEntitlementUsage).toHaveBeenCalledWith(91, "backtesting_basic"); });
  it("scopes CSV import to the authenticated user and preserves the unverified source label", async () => { vi.mocked(importHistoricalOhlcvCsv).mockResolvedValue({ importId: 5, validationStatus: "VERIFIED", sourceClassification: "USER_IMPORTED_UNVERIFIED" } as never); const caller = strategyLabRouter.createCaller(context()); await expect(caller.importCsvDataset({ fileName: "btc.csv", sourceLabel: "User export", symbol: "BTC", interval: "1h", csvText: "timestamp,open,high,low,close,volume" })).resolves.toMatchObject({ importId: 5 }); expect(importHistoricalOhlcvCsv).toHaveBeenCalledWith(91, expect.objectContaining({ sourceLabel: "User export" })); });
  it("rejects impossible parameter ranges before launching the search service", async () => { const caller = strategyLabRouter.createCaller(context()); await expect(caller.launchParameterSearch({ strategyId: 7, datasetId: 8, plan: { ranges: [], periodSplit: { trainingPercent: 0.6, validationPercent: 0.2 } } })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(launchControlledParameterSearch).not.toHaveBeenCalled(); });
  it("scopes trusted publisher-key registration and authentication preview to the caller", async () => { vi.mocked(registerTrustedCsvPublisherKey).mockResolvedValue({ id: 12, status: "ACTIVE" } as never); vi.mocked(previewCsvSourceAuthentication).mockResolvedValue({ status: "UNSIGNED", observedCsvFingerprint: "a".repeat(64) } as never); const caller = strategyLabRouter.createCaller(context()); await expect(caller.registerTrustedPublisherKey({ displayName: "My archive signer", publicKeySpkiBase64: "A".repeat(32), expiresAt: null })).resolves.toMatchObject({ id: 12 }); await expect(caller.previewCsvAuthentication({ csvText: "timestamp,open,high,low,close,volume", symbol: "BTC", interval: "1h", manifestJson: null })).resolves.toMatchObject({ status: "UNSIGNED" }); expect(registerTrustedCsvPublisherKey).toHaveBeenCalledWith(91, expect.objectContaining({ displayName: "My archive signer" })); expect(previewCsvSourceAuthentication).toHaveBeenCalledWith(91, expect.objectContaining({ symbol: "BTC" })); });
  it("rejects oversized or empty authentication material before persistence", async () => { const caller = strategyLabRouter.createCaller(context()); await expect(caller.registerTrustedPublisherKey({ displayName: "x", publicKeySpkiBase64: "A".repeat(2) })).rejects.toMatchObject({ code: "BAD_REQUEST" }); await expect(caller.previewCsvAuthentication({ csvText: "x", symbol: "BTC", interval: "1h", manifestJson: "" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(registerTrustedCsvPublisherKey).not.toHaveBeenCalledWith(91, expect.objectContaining({ displayName: "x" })); });
});
