import { ArrowUpRight, DatabaseZap, LockKeyhole, ReceiptText, ServerCog, Settings2, ShieldCheck, Users } from 'lucide-react';
import { useState } from 'react';
import { startLogin } from '@/const';
import { useAuth } from '@/_core/hooks/useAuth';
import { trpc } from '@/lib/trpc';

type Tab = 'overview' | 'users' | 'transactions' | 'integrations' | 'settings';
const tabs: { id: Tab; label: string; icon: React.ReactNode }[] = [
  { id: 'overview', label: 'Overview', icon: <ServerCog className="size-4" aria-hidden="true" /> },
  { id: 'users', label: 'Users', icon: <Users className="size-4" aria-hidden="true" /> },
  { id: 'transactions', label: 'Transactions', icon: <ReceiptText className="size-4" aria-hidden="true" /> },
  { id: 'integrations', label: 'Integrations', icon: <DatabaseZap className="size-4" aria-hidden="true" /> },
  { id: 'settings', label: 'Settings', icon: <Settings2 className="size-4" aria-hidden="true" /> },
];

export default function AdminDashboard() {
  const { user, loading, isAuthenticated } = useAuth();
  const [activeTab, setActiveTab] = useState<Tab>('overview');
  if (loading) return <AccessShell><div className="grid gap-4 sm:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <div key={index} className="h-28 animate-pulse rounded-2xl border border-border bg-card/75" />)}</div></AccessShell>;
  if (!isAuthenticated) return <AccessShell><AccessState title="Administrator sign-in required" copy="This workspace is limited to authorized platform administrators. Sign in to verify your access policy." action="Sign in to continue" onAction={startLogin} /></AccessShell>;
  if (user?.role !== 'admin') return <AccessShell><AccessState title="Administrator access is restricted" copy="The signed-in account does not have the administrator role required to view this workspace. No account, user, or transaction data has been exposed." /></AccessShell>;
  return <AccessShell><div className="rounded-2xl border border-primary/25 bg-primary/8 p-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-primary" aria-hidden="true" /><div><p className="text-sm font-semibold">Verified administrator session</p><p className="mt-1 text-sm leading-6 text-foreground-secondary">This workspace exposes protected integration telemetry only when a server-backed source is connected.</p></div></div></div><div className="mt-5 flex gap-1 overflow-x-auto rounded-xl border border-border bg-card/75 p-1" role="tablist" aria-label="Administrator views">{tabs.map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={activeTab === tab.id} onClick={() => setActiveTab(tab.id)} className={`inline-flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold transition-colors focus-visible:outline-none ${activeTab === tab.id ? 'bg-primary text-primary-foreground' : 'text-foreground-secondary hover:bg-background-secondary hover:text-foreground'}`}>{tab.icon}{tab.label}</button>)}</div><section className="mt-5">{activeTab === 'overview' && <Overview />}{activeTab === 'users' && <Unavailable title="User directory unavailable" copy="No server-backed administrator procedure is configured to list or manage user records. User data is intentionally absent from this preview." icon={<Users className="size-7 text-foreground-muted" aria-hidden="true" />} />}{activeTab === 'transactions' && <Unavailable title="Transaction monitoring unavailable" copy="No authenticated transaction-monitoring source is connected. This workspace intentionally does not fabricate transfers, balances, or operational activity." icon={<ReceiptText className="size-7 text-foreground-muted" aria-hidden="true" />} />}{activeTab === 'integrations' && <OnChainIntegration />}{activeTab === 'settings' && <SettingsState />}</section></AccessShell>;
}

function AccessShell({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-border bg-background/70 backdrop-blur-xl"><div className="container py-5 sm:py-7"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-foreground-muted">Protected workspace</p><h1 className="mt-1 flex items-center gap-2 text-2xl font-semibold tracking-tight sm:text-3xl"><ShieldCheck className="size-6 text-primary" aria-hidden="true" />Admin control room</h1><p className="mt-1 max-w-2xl text-sm text-foreground-secondary">A role-aware operational surface with explicit data boundaries.</p></div></header><div className="container max-w-6xl py-5 sm:py-7 lg:py-8">{children}</div></main>; }
function AccessState({ title, copy, action, onAction }: { title: string; copy: string; action?: string; onAction?: () => void }) { return <section className="mx-auto flex min-h-[420px] max-w-xl flex-col items-center justify-center rounded-2xl border border-border bg-card/75 px-5 text-center shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl"><span className="inline-flex size-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><LockKeyhole className="size-6" aria-hidden="true" /></span><h2 className="mt-5 text-xl font-semibold">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-foreground-secondary">{copy}</p>{action && onAction && <button type="button" onClick={onAction} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground transition-transform active:scale-[0.98] focus-visible:outline-none">{action}<ArrowUpRight className="size-4" aria-hidden="true" /></button>}</section>; }
function Overview() { const cards = [{ label: 'User directory', state: 'Not connected', copy: 'No administrative user API is configured.', icon: <Users className="size-5" aria-hidden="true" /> }, { label: 'Transaction stream', state: 'Not connected', copy: 'No monitoring source is configured.', icon: <ReceiptText className="size-5" aria-hidden="true" /> }, { label: 'Platform configuration', state: 'Read-only shell', copy: 'Configuration is managed outside this preview.', icon: <Settings2 className="size-5" aria-hidden="true" /> }]; return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3">{cards.map((card) => <article key={card.label} className="rounded-2xl border border-border bg-card/75 p-4 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl"><span className="inline-flex size-9 items-center justify-center rounded-xl bg-background-secondary text-foreground-secondary">{card.icon}</span><p className="mt-4 text-sm font-semibold">{card.label}</p><p className="mt-1 text-sm font-semibold text-warning">{card.state}</p><p className="mt-2 text-sm leading-6 text-foreground-secondary">{card.copy}</p></article>)}</div><SubscriptionDebug /><Unavailable title="No live administrative telemetry" copy="Connect protected server procedures for metrics, user management, transaction monitoring, and system controls. Until then, this secure shell avoids displaying invented operational statistics." icon={<ServerCog className="size-7 text-foreground-muted" aria-hidden="true" />} /></div>; }
function SubscriptionDebug() { const [userId, setUserId] = useState(''); const [requestedId, setRequestedId] = useState<number | null>(null); const account = trpc.subscriptions.adminAccount.useQuery({ userId: requestedId ?? 1 }, { enabled: requestedId !== null, retry: false }); const submit = () => { const parsed = Number(userId); if (Number.isInteger(parsed) && parsed > 0) setRequestedId(parsed); }; return <section className="rounded-2xl border border-primary/25 bg-primary/5 p-5"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-primary">V3.0 internal entitlement visibility</p><h2 className="mt-1 text-lg font-semibold">Subscription and usage lookup</h2><p className="mt-2 text-sm text-foreground-secondary">This read-only tool calls the server-side administrator procedure. It cannot edit plans, grant access, charge a customer, or expose a directory.</p><div className="mt-4 flex max-w-md gap-2"><input value={userId} onChange={(event) => setUserId(event.target.value)} inputMode="numeric" aria-label="User ID for subscription lookup" className="terminal-input" placeholder="User ID" /><button type="button" onClick={submit} className="rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground">Inspect</button></div>{account.isFetching ? <p className="mt-4 text-sm text-foreground-secondary">Loading server-owned subscription state…</p> : account.error ? <p className="mt-4 text-sm text-danger">The requested account could not be inspected.</p> : account.data ? <div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-border bg-background/60 p-3"><p className="text-xs text-foreground-muted">Plan / state</p><p className="mt-1 font-semibold">{account.data.subscription.plan} · {account.data.subscription.state}</p></div><div className="rounded-xl border border-border bg-background/60 p-3"><p className="text-xs text-foreground-muted">Configured features</p><p className="mt-1 font-semibold">{account.data.features.filter((item) => item.allowed).length} allowed</p></div><div className="rounded-xl border border-border bg-background/60 p-3"><p className="text-xs text-foreground-muted">Provider state</p><p className="mt-1 font-semibold">{account.data.paymentProviderConfigured ? 'Configured' : 'Not configured'}</p></div></div> : null}</section>; }
function OnChainIntegration() { const health = trpc.onChain.adminHealth.useQuery(undefined, { retry: false }); return <section className="rounded-2xl border border-primary/25 bg-primary/5 p-5"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-primary">Admin → Integrations → On-Chain Data</p><h2 className="mt-1 text-lg font-semibold">Alchemy infrastructure health</h2><p className="mt-2 text-sm text-foreground-secondary">Read-only status from the protected server. API keys and webhook signing material are never sent to this surface.</p>{health.isLoading ? <p className="mt-4 text-sm text-foreground-secondary">Loading integration health…</p> : health.error ? <p className="mt-4 text-sm text-danger">Integration telemetry is unavailable for this session.</p> : health.data ? <div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-border bg-background/60 p-3"><p className="text-xs text-foreground-muted">Alchemy</p><p className={`mt-1 font-semibold ${health.data.networks.every((network) => network.status === 'CONNECTED') ? 'text-success' : 'text-warning'}`}>{health.data.networks.every((network) => network.status === 'CONNECTED') ? 'ALCHEMY — CONNECTED' : 'ON-CHAIN DATA PROVIDER NOT CONFIGURED'}</p><p className="mt-1 text-xs text-foreground-secondary">Webhook: {health.data.webhook.status}</p></div><div className="rounded-xl border border-border bg-background/60 p-3"><p className="text-xs text-foreground-muted">Supported networks</p><p className="mt-1 font-semibold">{health.data.networks.filter((network) => network.status === 'CONNECTED').flatMap((network) => network.supportedChains).join(', ') || 'None verified'}</p><p className="mt-1 text-xs text-foreground-secondary">Last sync: {health.data.latestSyncAt ? new Date(health.data.latestSyncAt).toLocaleString() : 'No recorded sync'}</p></div><div className="rounded-xl border border-border bg-background/60 p-3"><p className="text-xs text-foreground-muted">Recent sync receipts</p><p className="mt-1 font-semibold">{health.data.requests} requests · {health.data.errors} errors</p><p className="mt-1 text-xs text-foreground-secondary">Rate limits: {health.data.rateLimits} · receipts: {health.data.recentSyncCount}</p></div></div> : null}</section>; }
function SettingsState() { return <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]"><section className="rounded-2xl border border-border bg-card/75 p-4 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl sm:p-5"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-muted">Administration boundaries</p><h2 className="mt-1 text-lg font-semibold">No mutable controls are connected</h2><div className="mt-5 divide-y divide-border rounded-xl border border-border">{['System configuration', 'Fee policies', 'Security policies', 'Maintenance controls'].map((item) => <div key={item} className="flex items-center justify-between gap-3 px-4 py-3"><span className="text-sm font-medium">{item}</span><span className="rounded-full border border-border bg-background-secondary px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] text-foreground-muted">Unavailable</span></div>)}</div></section><aside className="rounded-2xl border border-border bg-card/75 p-4 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl"><p className="text-sm font-semibold">Safe by default</p><p className="mt-2 text-sm leading-6 text-foreground-secondary">No setting in this preview can alter platform behavior. Connect protected, auditable server procedures before enabling operational controls.</p></aside></div>; }
function Unavailable({ title, copy, icon }: { title: string; copy: string; icon: React.ReactNode }) { return <section className="flex min-h-64 flex-col items-center justify-center rounded-2xl border border-border bg-card/75 px-5 text-center shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl">{icon}<h2 className="mt-4 text-lg font-semibold">{title}</h2><p className="mt-2 max-w-lg text-sm leading-6 text-foreground-secondary">{copy}</p></section>; }
