import { AlertTriangle, CheckCircle2, Database, Eye, KeyRound, Loader2, ShieldCheck, Trash2, UploadCloud } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { trpc } from '@/lib/trpc';

export default function BinanceImport() {
  const [apiKey, setApiKey] = useState('');
  const [apiSecret, setApiSecret] = useState('');
  const [label, setLabel] = useState('');
  const [selectedKeyId, setSelectedKeyId] = useState<number | null>(null);
  const [selectedPortfolioId, setSelectedPortfolioId] = useState<number | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const { data: apiKeys, refetch: refetchKeys, isLoading: keysLoading, error: keysError } = trpc.binanceImport.getApiKeys.useQuery();
  const { data: portfolios, isLoading: portfoliosLoading } = trpc.portfolio.getPortfolios.useQuery();
  const { data: previewBalances, isLoading: previewLoading, error: previewError } = trpc.binanceImport.previewBalances.useQuery({ keyId: selectedKeyId || 0 }, { enabled: !!selectedKeyId && showPreview });
  const saveKeysMutation = trpc.binanceImport.saveApiKeys.useMutation();
  const deleteKeyMutation = trpc.binanceImport.deleteApiKey.useMutation();
  const importBalancesMutation = trpc.binanceImport.importBalances.useMutation();
  const saveKeys = async () => { if (!apiKey.trim() || !apiSecret.trim()) { toast.error('Enter both the API key and API secret.'); return; } try { await saveKeysMutation.mutateAsync({ apiKey, apiSecret, label: label || 'Read-only account' }); setApiKey(''); setApiSecret(''); setLabel(''); await refetchKeys(); toast.success('Connection credentials saved.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not save credentials.'); } };
  const deleteKey = async (keyId: number) => { try { await deleteKeyMutation.mutateAsync({ keyId }); if (selectedKeyId === keyId) { setSelectedKeyId(null); setShowPreview(false); } await refetchKeys(); toast.success('Connection removed.'); } catch { toast.error('Could not remove this connection.'); } };
  const importBalances = async () => { if (!selectedKeyId || !selectedPortfolioId) { toast.error('Choose both a connection and a destination portfolio.'); return; } try { const result = await importBalancesMutation.mutateAsync({ keyId: selectedKeyId, portfolioId: selectedPortfolioId }); toast.success(`${result.total} assets imported into the selected portfolio.`); setShowPreview(false); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not import balances.'); } };
  return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-border bg-background/70 backdrop-blur-xl"><div className="container py-5 sm:py-7"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-foreground-muted">External account connection</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Binance import</h1><p className="mt-1 max-w-2xl text-sm text-foreground-secondary">Link a read-only account connection to preview balances and import them into an existing portfolio.</p></div></header>
    <div className="container max-w-6xl py-5 sm:py-7 lg:py-8">{keysError && <Feedback tone="danger" title="Saved connections are unavailable" copy={keysError.message} />}<div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-border bg-card/75 p-4 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl sm:p-5"><div className="flex items-start gap-3"><span className="inline-flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><KeyRound className="size-5" aria-hidden="true" /></span><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-muted">New connection</p><h2 className="mt-1 text-lg font-semibold">Add read-only credentials</h2><p className="mt-1 text-sm leading-6 text-foreground-secondary">Use a key restricted to reading balances. Do not submit a trading- or withdrawal-enabled credential.</p></div></div><form onSubmit={(event) => { event.preventDefault(); void saveKeys(); }} className="mt-5 space-y-4"><Field label="API key"><input type="password" autoComplete="off" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder="Paste the account API key" className="input" /></Field><Field label="API secret"><input type="password" autoComplete="off" value={apiSecret} onChange={(event) => setApiSecret(event.target.value)} placeholder="Paste the account API secret" className="input" /></Field><Field label="Connection label (optional)"><input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="e.g. Long-term account" className="input" /></Field><button type="submit" disabled={saveKeysMutation.isPending} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground transition-transform active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-65 focus-visible:outline-none">{saveKeysMutation.isPending ? <Loader2 className="size-4 animate-spin" aria-hidden="true" /> : <ShieldCheck className="size-4" aria-hidden="true" />}{saveKeysMutation.isPending ? 'Saving connection…' : 'Save connection'}</button></form></section>
        <section className="overflow-hidden rounded-2xl border border-border bg-card/75 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl"><header className="border-b border-border p-4 sm:p-5"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-muted">Configured connections</p><h2 className="mt-1 text-lg font-semibold">Select a source account</h2></header>{keysLoading ? <LoadingRows count={3} /> : apiKeys?.length ? <div className="divide-y divide-border">{apiKeys.map((key: any) => <div key={key.id} className={`flex flex-col gap-3 p-4 transition-colors sm:flex-row sm:items-center sm:justify-between sm:p-5 ${selectedKeyId === key.id ? 'bg-primary/8' : 'hover:bg-background-secondary/45'}`}><button type="button" onClick={() => { setSelectedKeyId(key.id); setShowPreview(false); }} className="min-w-0 text-left focus-visible:outline-none" aria-pressed={selectedKeyId === key.id}><span className="flex items-center gap-2"><span className={`size-2 rounded-full ${selectedKeyId === key.id ? 'bg-success' : 'bg-foreground-muted'}`} aria-hidden="true" /><span className="truncate text-sm font-semibold">{key.label}</span></span><span className="mt-1 block text-xs text-foreground-secondary">Last synchronized: {key.lastSyncedAt ? new Date(key.lastSyncedAt).toLocaleDateString() : 'Not yet synchronized'}</span></button><button type="button" onClick={() => void deleteKey(key.id)} disabled={deleteKeyMutation.isPending} className="inline-flex w-fit items-center gap-2 rounded-lg border border-danger/25 bg-danger/8 px-3 py-2 text-xs font-semibold text-danger transition-colors hover:bg-danger/15 disabled:opacity-50 focus-visible:outline-none"><Trash2 className="size-3.5" aria-hidden="true" />Remove</button></div>)}</div> : <EmptyConnections />}</section></div>
      {selectedKeyId && <section className="mt-5 overflow-hidden rounded-2xl border border-border bg-card/75 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl"><header className="flex flex-col gap-3 border-b border-border p-4 sm:flex-row sm:items-end sm:justify-between sm:p-5"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-muted">Portfolio import</p><h2 className="mt-1 text-lg font-semibold">Preview and import balances</h2><p className="mt-1 text-sm text-foreground-secondary">This imports balance records into a chosen portfolio; it does not place trades or move funds.</p></div><span className="rounded-full border border-success/25 bg-success/8 px-3 py-1 text-xs font-semibold text-success">Source selected</span></header><div className="grid gap-4 p-4 sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-end sm:p-5"><Field label="Destination portfolio"><select value={selectedPortfolioId ?? ''} onChange={(event) => setSelectedPortfolioId(event.target.value ? Number(event.target.value) : null)} className="input" disabled={portfoliosLoading}><option value="">{portfoliosLoading ? 'Loading portfolios…' : 'Choose a portfolio'}</option>{portfolios?.map((portfolio: any) => <option key={portfolio.id} value={portfolio.id}>{portfolio.name}</option>)}</select></Field><button type="button" onClick={() => setShowPreview(true)} className="inline-flex h-[46px] items-center justify-center gap-2 rounded-xl border border-border bg-background-secondary px-4 text-sm font-semibold text-foreground-secondary transition-colors hover:text-foreground focus-visible:outline-none"><Eye className="size-4" aria-hidden="true" />Preview</button><button type="button" onClick={() => void importBalances()} disabled={!selectedPortfolioId || importBalancesMutation.isPending} className="inline-flex h-[46px] items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground transition-transform active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-65 focus-visible:outline-none">{importBalancesMutation.isPending ? <Loader2 className="size-4 animate-spin" aria-hidden="true" /> : <UploadCloud className="size-4" aria-hidden="true" />}{importBalancesMutation.isPending ? 'Importing…' : 'Import balances'}</button></div>{showPreview && <BalancePreview loading={previewLoading} error={previewError?.message} balances={previewBalances ?? []} />}</section>}</div></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-semibold text-foreground-secondary">{label}</span>{children}</label>; }
function Feedback({ tone, title, copy }: { tone: 'danger'; title: string; copy: string }) { return <div className="mb-5 flex gap-3 rounded-2xl border border-danger/30 bg-danger/10 p-4"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-danger" aria-hidden="true" /><div><p className="text-sm font-semibold text-danger">{title}</p><p className="mt-1 text-sm text-foreground-secondary">{copy}</p></div></div>; }
function LoadingRows({ count }: { count: number }) { return <div className="space-y-3 p-4 sm:p-5">{Array.from({ length: count }, (_, index) => <div key={index} className="h-12 animate-pulse rounded-xl bg-background-secondary" />)}</div>; }
function EmptyConnections() { return <div className="flex min-h-56 flex-col items-center justify-center px-5 text-center"><Database className="size-7 text-foreground-muted" aria-hidden="true" /><h3 className="mt-3 text-sm font-semibold">No connections saved</h3><p className="mt-1 max-w-sm text-sm leading-6 text-foreground-secondary">Add a read-only connection to preview eligible balances.</p></div>; }
function BalancePreview({ loading, error, balances }: { loading: boolean; error?: string; balances: any[] }) { if (loading) return <div className="border-t border-border"><LoadingRows count={4} /></div>; if (error) return <div className="border-t border-border p-4 sm:p-5"><Feedback tone="danger" title="Balance preview is unavailable" copy={error} /></div>; if (!balances.length) return <div className="flex min-h-48 flex-col items-center justify-center border-t border-border px-5 text-center"><CheckCircle2 className="size-7 text-success" aria-hidden="true" /><h3 className="mt-3 text-sm font-semibold">No balances returned</h3><p className="mt-1 max-w-sm text-sm leading-6 text-foreground-secondary">The selected connection did not return an available balance preview.</p></div>; return <div className="border-t border-border"><div className="hidden grid-cols-4 gap-3 border-b border-border px-4 py-3 text-[10px] font-semibold uppercase tracking-[0.12em] text-foreground-muted sm:grid sm:px-5"><span>Asset</span><span className="text-right">Free</span><span className="text-right">Locked</span><span className="text-right">Total</span></div><div className="divide-y divide-border">{balances.map((balance: any) => <div key={balance.asset} className="grid gap-2 px-4 py-3 sm:grid-cols-4 sm:items-center sm:gap-3 sm:px-5"><span className="font-mono text-sm font-semibold">{balance.asset}</span><Value label="Free" value={balance.free.toFixed(8)} /><Value label="Locked" value={balance.locked.toFixed(8)} /><Value label="Total" value={balance.total.toFixed(8)} emphasis /></div>)}</div></div>; }
function Value({ label, value, emphasis }: { label: string; value: string; emphasis?: boolean }) { return <span className={`flex items-center justify-between gap-3 font-mono text-xs sm:block sm:text-right ${emphasis ? 'font-semibold text-success' : 'text-foreground-secondary'}`}><span className="text-[10px] font-sans font-semibold uppercase tracking-[0.1em] text-foreground-muted sm:hidden">{label}</span>{value}</span>; }
