import React, { useState } from "react";
import { AlertTriangle, FileCheck2, KeyRound, Loader2, ShieldCheck, ShieldX, Upload } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type Interval = "5m" | "15m" | "1h" | "4h" | "1d";
type AuthResult = { status: "UNSIGNED" | "VERIFIED" | "REJECTED"; observedCsvFingerprint: string; failureCode?: string; message?: string; manifest?: { keyFingerprint: string; csvSha256: string; issuedAt: number; expiresAt: number }; publisherKeyId?: number };
function AuthEvidence({ result }: { result: AuthResult }) { const tone = result.status === "VERIFIED" ? "border-success/30 bg-success/10 text-success" : result.status === "REJECTED" ? "border-danger/30 bg-danger/10 text-danger" : "border-warning/30 bg-warning/10 text-warning"; const title = result.status === "VERIFIED" ? "Signature verified with a user-trusted key" : result.status === "REJECTED" ? "Authentication rejected" : "No signature provided"; return <div className={`mt-4 rounded-xl border p-4 text-sm ${tone}`}><div className="flex items-start gap-2"><span className="mt-0.5">{result.status === "VERIFIED" ? <ShieldCheck className="size-4" /> : <AlertTriangle className="size-4" />}</span><div><strong>{title}</strong><p className="mt-1 leading-5">{result.status === "VERIFIED" ? "The signed manifest binds this exact uploaded UTF-8 CSV fingerprint to a public key you registered in this account. This does not independently verify the publisher's real-world identity or market accuracy." : result.status === "REJECTED" ? result.message ?? "The signed manifest could not be authenticated. No authenticated dataset will be created." : "Structural CSV validation can still be used, but this file remains an unverified user import."}</p><p className="mt-2 break-all font-mono text-[11px]">CSV SHA-256: {result.observedCsvFingerprint}</p>{result.failureCode ? <p className="mt-1 text-xs">Code: {result.failureCode}</p> : null}</div></div></div>; }

export default function CsvSourceTrust() {
  const utils = trpc.useUtils(); const keys = trpc.strategyLab.listTrustedPublisherKeys.useQuery();
  const [file, setFile] = useState<File | null>(null); const [csvText, setCsvText] = useState(""); const [manifestJson, setManifestJson] = useState(""); const [sourceLabel, setSourceLabel] = useState(""); const [symbol, setSymbol] = useState("BTC"); const [interval, setInterval] = useState<Interval>("1h"); const [preview, setPreview] = useState<AuthResult | null>(null); const [keyName, setKeyName] = useState(""); const [keyText, setKeyText] = useState(""); const [expiry, setExpiry] = useState("");
  const previewMutation = trpc.strategyLab.previewCsvAuthentication.useMutation({ onSuccess: (result) => setPreview(result as AuthResult), onError: (error) => toast.error("Authentication preview failed", { description: error.message }) });
  const importMutation = trpc.strategyLab.importCsvDataset.useMutation({ onSuccess: (result) => { setPreview(result.authentication as AuthResult); if (result.validationStatus === "VERIFIED") toast.success(result.authentication?.status === "VERIFIED" ? "Authenticated CSV import completed" : "CSV structure verified; source remains unverified"); else toast.error("CSV import rejected; no dataset was created."); }, onError: (error) => toast.error("CSV import failed", { description: error.message }) });
  const registerMutation = trpc.strategyLab.registerTrustedPublisherKey.useMutation({ onSuccess: () => { setKeyName(""); setKeyText(""); setExpiry(""); void utils.strategyLab.listTrustedPublisherKeys.invalidate(); toast.success("Trusted Ed25519 key registered for this account"); }, onError: (error) => toast.error("Key registration failed", { description: error.message }) });
  const revokeMutation = trpc.strategyLab.revokeTrustedPublisherKey.useMutation({ onSuccess: () => { void utils.strategyLab.listTrustedPublisherKeys.invalidate(); toast.success("Key revoked for future imports"); }, onError: (error) => toast.error("Key revocation failed", { description: error.message }) });
  const chooseFile = async (next: File | null) => { if (!next) return; if (!next.name.toLowerCase().endsWith(".csv") || next.size > 2_000_000) { toast.error("Choose a .csv file no larger than 2 MB."); return; } setFile(next); setCsvText(await next.text()); setPreview(null); };
  const previewSource = () => { if (!csvText) { toast.error("Choose a CSV before previewing authentication."); return; } previewMutation.mutate({ csvText, symbol: symbol.trim().toUpperCase(), interval, manifestJson: manifestJson.trim() || null }); };
  const importCsv = () => { if (!file || !sourceLabel.trim()) { toast.error("Choose a CSV and provide a descriptive source label."); return; } importMutation.mutate({ fileName: file.name, sourceLabel: sourceLabel.trim(), csvText, symbol: symbol.trim().toUpperCase(), interval, manifestJson: manifestJson.trim() || null }); };
  const registerKey = () => { const expiresAt = expiry ? Date.parse(`${expiry}T00:00:00.000Z`) : null; if (!keyName.trim() || !keyText.trim()) { toast.error("Enter a publisher label and base64 SPKI public key."); return; } if (expiry && !Number.isFinite(expiresAt)) { toast.error("Expiry must be a valid UTC date."); return; } registerMutation.mutate({ displayName: keyName.trim(), publicKeySpkiBase64: keyText.trim(), expiresAt }); };
  if (keys.error) return <main className="min-h-[calc(100vh-4rem)] bg-background px-4 py-7 text-foreground sm:px-6"><section className="mx-auto max-w-5xl rounded-2xl border border-warning/25 bg-warning/10 p-5 text-warning">Private source-trust records are unavailable until an authenticated session is available. No registered publisher key is shown.</section></main>;
  return <main className="min-h-[calc(100vh-4rem)] bg-background px-4 py-7 text-foreground sm:px-6"><div className="mx-auto max-w-6xl space-y-6"><header className="border-b border-border pb-6"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Strategy Research · Source Trust</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Authenticate the exact CSV you test</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-foreground-secondary">Register only public Ed25519 keys you choose to trust. A signed manifest must match the exact CSV SHA-256, symbol, interval, key state and expiry. This proves key possession, not independent publisher identity, exchange provenance, or market-data correctness.</p></header>
    <section className="grid gap-6 xl:grid-cols-2"><Panel title="Trusted publisher public keys" icon={<KeyRound className="size-5" />}><p className="text-sm text-foreground-secondary">Only SPKI DER encoded as standard padded base64 is accepted. Never paste a private key.</p><div className="mt-4 grid gap-3"><Field label="Publisher label"><input value={keyName} onChange={(event) => setKeyName(event.target.value)} maxLength={120} className="terminal-input" placeholder="e.g. My signed archive" /></Field><Field label="Ed25519 SPKI public key (base64)"><textarea value={keyText} onChange={(event) => setKeyText(event.target.value)} className="terminal-input min-h-24 font-mono text-xs" placeholder="MI..." /></Field><Field label="Optional expiry (UTC date)"><input value={expiry} onChange={(event) => setExpiry(event.target.value)} type="date" className="terminal-input" /></Field></div><button type="button" onClick={registerKey} disabled={registerMutation.isPending} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-60 focus-visible:outline-none">{registerMutation.isPending ? <Loader2 className="size-4 animate-spin" /> : <KeyRound className="size-4" />}Register public key</button><div className="mt-5 space-y-2">{keys.isLoading ? <p className="text-sm text-foreground-muted">Loading private keys…</p> : keys.data?.length ? keys.data.map((key) => <div key={key.id} className="rounded-xl border border-border bg-background/50 p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="text-sm">{key.displayName}</strong><p className="mt-1 break-all font-mono text-[11px] text-foreground-muted">{key.keyFingerprint}</p><p className="mt-1 text-xs text-foreground-secondary">{key.status} · {key.expiresAt ? `Expires ${new Date(key.expiresAt).toLocaleDateString()}` : "No expiry"} · user-trusted only</p></div>{key.status === "ACTIVE" ? <button type="button" onClick={() => revokeMutation.mutate({ keyId: key.id })} disabled={revokeMutation.isPending} className="rounded-lg border border-danger/30 px-3 py-2 text-xs font-semibold text-danger hover:bg-danger/10 focus-visible:outline-none">Revoke</button> : <span className="text-xs text-danger">Revoked</span>}</div></div>) : <p className="rounded-xl border border-dashed border-border p-4 text-sm text-foreground-secondary">No trusted publisher key is registered for this account. Source labels alone are not proof.</p>}</div></Panel>
      <Panel title="Signed CSV authentication" icon={<FileCheck2 className="size-5" />}><p className="text-sm text-foreground-secondary">The detached manifest is JSON with version, keyFingerprint, csvSha256, symbol, interval, issuedAt, expiresAt and signature. Preview verifies it before the import attempt.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="CSV file"><input type="file" accept=".csv,text/csv" onChange={(event) => void chooseFile(event.target.files?.[0] ?? null)} className="terminal-input file:mr-2 file:rounded-md file:border-0 file:bg-primary/15 file:px-2 file:py-1 file:text-primary" /></Field><Field label="Source label"><input value={sourceLabel} onChange={(event) => setSourceLabel(event.target.value)} className="terminal-input" placeholder="Descriptive only; not proof" /></Field><Field label="Symbol"><input value={symbol} onChange={(event) => setSymbol(event.target.value.toUpperCase())} className="terminal-input" maxLength={15} /></Field><Field label="Interval"><select value={interval} onChange={(event) => setInterval(event.target.value as Interval)} className="terminal-input">{["5m", "15m", "1h", "4h", "1d"].map((item) => <option key={item}>{item}</option>)}</select></Field></div><Field label="Detached signed manifest JSON"><textarea value={manifestJson} onChange={(event) => { setManifestJson(event.target.value); setPreview(null); }} className="terminal-input mt-1 min-h-36 font-mono text-xs" placeholder='{"version":1,"keyFingerprint":"…","csvSha256":"…","symbol":"BTC","interval":"1h","issuedAt":…,"expiresAt":…, "signature":"…"}' /></Field><div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={previewSource} disabled={previewMutation.isPending || !file} className="inline-flex items-center gap-2 rounded-lg border border-primary/40 px-4 py-2.5 text-sm font-semibold text-primary disabled:opacity-60 focus-visible:outline-none">{previewMutation.isPending ? <Loader2 className="size-4 animate-spin" /> : <ShieldCheck className="size-4" />}Preview authentication</button><button type="button" onClick={importCsv} disabled={importMutation.isPending || !file} className="inline-flex items-center gap-2 rounded-lg bg-success px-4 py-2.5 text-sm font-semibold text-success-foreground disabled:opacity-60 focus-visible:outline-none">{importMutation.isPending ? <Loader2 className="size-4 animate-spin" /> : <Upload className="size-4" />}Validate and import</button></div>{file ? <p className="mt-3 text-xs text-foreground-muted">Selected locally: {file.name}. The server calculates the authoritative fingerprint when previewing or importing.</p> : null}{preview ? <AuthEvidence result={preview} /> : null}</Panel></section>
    <section className="rounded-2xl border border-warning/25 bg-warning/10 p-5 text-sm text-warning"><h2 className="flex items-center gap-2 font-semibold"><ShieldX className="size-5" />Trust boundary</h2><p className="mt-2 leading-6">A verified signature means the exact CSV matches a manifest signed by a public key you personally registered. It does not make the source platform-verified, prove the key owner's identity, validate price accuracy, or enable live execution. Revoking a key blocks future authenticated imports but preserves prior audit evidence.</p></section></div></main>;
}
function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-2xl border border-border bg-card/70 p-5"><h2 className="flex items-center gap-2 text-xl font-semibold">{icon}{title}</h2><div className="mt-3">{children}</div></section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-medium text-foreground-secondary"><span className="mb-1.5 block">{label}</span>{children}</label>; }
