import { useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, Calendar, CircleDollarSign, LockKeyhole, Sparkles, TrendingUp, Zap } from 'lucide-react';
import { toast } from 'sonner';

type EarnTab = 'staking' | 'lending' | 'launchpad';
interface StakingProduct { id: string; asset: string; symbol: string; apy: number; minAmount: number; lockPeriod: string; yourAmount: number; earned: number; status: 'active' | 'available'; }

const stakingProducts: StakingProduct[] = [
  { id: '1', asset: 'Ethereum', symbol: 'ETH', apy: 4.5, minAmount: 0.1, lockPeriod: 'Flexible', yourAmount: 15.3, earned: 2.45, status: 'active' },
  { id: '2', asset: 'Solana', symbol: 'SOL', apy: 6.2, minAmount: 1, lockPeriod: '30 days', yourAmount: 250, earned: 38.75, status: 'active' },
  { id: '3', asset: 'Polkadot', symbol: 'DOT', apy: 12.5, minAmount: 10, lockPeriod: '60 days', yourAmount: 0, earned: 0, status: 'available' },
  { id: '4', asset: 'Cardano', symbol: 'ADA', apy: 4.8, minAmount: 100, lockPeriod: 'Flexible', yourAmount: 0, earned: 0, status: 'available' },
];

const tabs: { id: EarnTab; label: string }[] = [{ id: 'staking', label: 'Staking' }, { id: 'lending', label: 'Lending' }, { id: 'launchpad', label: 'Launchpad' }];

export default function Earn() {
  const [activeTab, setActiveTab] = useState<EarnTab>('staking');
  const notify = (message: string, description: string) => toast.info(message, { description });

  return (
    <main className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border bg-background/70 backdrop-blur-xl"><div className="container flex flex-col gap-3 py-5 sm:flex-row sm:items-end sm:justify-between sm:py-7"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-foreground-muted">Yield preview</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Earn</h1><p className="mt-1 text-sm text-foreground-secondary">Explore reference product layouts and preview-only yield workflows.</p></div><span className="inline-flex items-center gap-2 self-start rounded-full border border-primary/25 bg-primary/10 px-3 py-1.5 text-xs font-semibold text-primary sm:self-auto"><Sparkles className="size-3.5" aria-hidden="true" /> Reference terms · not an offer</span></div></header>

      <div className="container py-5 sm:py-7 lg:py-8"><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.28 }} className="space-y-5 lg:space-y-6">
        <aside className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm leading-6 text-foreground-secondary" aria-label="Yield data disclosure">The balances, annualized-yield figures, terms, and rewards below are deterministic interface examples. They are not current holdings, rates, offers, or advice, and no staking, lending, claim, or notification request is submitted from this preview.</aside>

        <section className="rounded-2xl border border-border bg-card/75 p-5 shadow-[0_24px_80px_rgba(3,7,34,0.18)] backdrop-blur-xl sm:p-6" aria-labelledby="earn-summary-title"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-foreground-muted">Reference portfolio</p><h2 id="earn-summary-title" className="mt-1 text-lg font-semibold">Illustrative earnings summary</h2></div><TrendingUp className="size-5 text-primary" aria-hidden="true" /></div><dl className="mt-6 grid grid-cols-1 divide-y divide-border sm:grid-cols-3 sm:divide-x sm:divide-y-0"><SummaryMetric label="Illustrative staked value" value="$265,550" /><SummaryMetric label="Illustrative earned value" value="$41.20" tone="success" /><SummaryMetric label="Reference APY" value="5.8%" tone="primary" /></dl></section>

        <section aria-label="Earn product categories"><div className="inline-flex w-full rounded-xl border border-border bg-background-secondary p-1 sm:w-auto" role="tablist" aria-label="Earn product categories">{tabs.map((tab) => { const active = activeTab === tab.id; return <button key={tab.id} type="button" role="tab" aria-selected={active} aria-controls={`${tab.id}-panel`} onClick={() => setActiveTab(tab.id)} className={`flex-1 rounded-lg px-3 py-2.5 text-sm font-semibold transition-colors focus-visible:outline-none sm:flex-none sm:px-5 ${active ? 'bg-card text-foreground shadow-sm' : 'text-foreground-secondary hover:text-foreground'}`}>{tab.label}</button>; })}</div></section>

        {activeTab === 'staking' && <section id="staking-panel" role="tabpanel" aria-label="Staking products" className="space-y-3">{stakingProducts.map((product) => <StakingProductCard key={product.id} product={product} onAction={notify} />)}</section>}
        {activeTab === 'lending' && <AvailabilityPanel id="lending-panel" icon={CircleDollarSign} title="Lending is not configured" description="Lending products and notification delivery are unavailable in this workspace preview. Availability, terms, and eligibility cannot be inferred here." action="Review lending boundary" onAction={() => notify('Lending preview', 'No notification request was stored and no lending product is available.')} />}
        {activeTab === 'launchpad' && <AvailabilityPanel id="launchpad-panel" icon={Zap} title="Launchpad access is not configured" description="New-token offerings and registration are unavailable in this workspace preview. Do not rely on this interface for eligibility, terms, or availability." action="Review launchpad boundary" onAction={() => notify('Launchpad preview', 'No registration or notification request was stored.')} />}

        <section className="rounded-2xl border border-border bg-card/75 p-5 shadow-[0_24px_80px_rgba(3,7,34,0.18)] backdrop-blur-xl sm:p-6" aria-labelledby="how-staking-works-title"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-foreground-muted">Process</p><h2 id="how-staking-works-title" className="mt-1 text-lg font-semibold">Preview workflow structure</h2><ol className="mt-5 grid gap-3 sm:grid-cols-3">{[{ title: 'Review a reference asset', description: 'Compare illustrative terms only after verifying the actual provider and product conditions.' }, { title: 'Set a hypothetical amount', description: 'Use the workflow to understand inputs; it does not create a position or instruction.' }, { title: 'Inspect a reference outcome', description: 'Values here illustrate layout behavior and do not represent rewards or product status.' }].map((step, index) => <li key={step.title} className="rounded-xl border border-border bg-background-secondary p-4"><span className="inline-flex size-7 items-center justify-center rounded-full bg-primary/15 text-xs font-bold text-primary">{index + 1}</span><h3 className="mt-3 font-semibold text-foreground">{step.title}</h3><p className="mt-1 text-sm leading-6 text-foreground-secondary">{step.description}</p></li>)}</ol></section>
      </motion.div></div>
    </main>
  );
}

function SummaryMetric({ label, value, tone = 'default' }: { label: string; value: string; tone?: 'default' | 'success' | 'primary' }) { const tones = { default: 'text-foreground', success: 'text-success', primary: 'text-primary' }; return <div className="py-3 first:pt-0 last:pb-0 sm:px-5 sm:py-0 sm:first:pl-0 sm:last:pr-0"><dt className="text-sm text-foreground-secondary">{label}</dt><dd className={`mt-2 font-mono text-2xl font-semibold sm:text-3xl ${tones[tone]}`}>{value}</dd></div>; }

function StakingProductCard({ product, onAction }: { product: StakingProduct; onAction: (title: string, description: string) => void }) {
  const active = product.status === 'active';
  return <article className="rounded-2xl border border-border bg-card/75 p-4 shadow-[0_18px_50px_rgba(3,7,34,0.15)] transition-colors hover:border-primary/35 sm:p-5"><div className="grid gap-5 lg:grid-cols-[minmax(0,1.7fr)_minmax(90px,.65fr)_minmax(110px,.9fr)_minmax(110px,.9fr)_auto] lg:items-center"><div className="flex min-w-0 items-center gap-3"><span className="inline-flex size-11 shrink-0 items-center justify-center rounded-xl bg-primary/15 font-bold text-primary">{product.symbol.slice(0, 1)}</span><div className="min-w-0"><h3 className="truncate font-semibold text-foreground">{product.asset} <span className="text-foreground-secondary">({product.symbol})</span></h3><p className="mt-1 flex items-center gap-1 text-xs text-foreground-muted"><Calendar className="size-3.5" aria-hidden="true" /> Reference {product.lockPeriod} term · Min. {product.minAmount} {product.symbol}</p></div></div><Metric label="Reference APY" value={`${product.apy}%`} className="text-primary" /><Metric label="Illustrative amount" value={active ? `${product.yourAmount.toLocaleString()} ${product.symbol}` : '—'} /><Metric label="Illustrative reward" value={active ? `$${product.earned.toFixed(2)}` : '—'} /><div className="grid grid-cols-2 gap-2 lg:flex lg:justify-end">{active ? <><button type="button" onClick={() => onAction('Unstake preview', `No ${product.asset} unstake request will be submitted from this preview.`)} className="rounded-lg border border-border px-3 py-2.5 text-xs font-semibold text-foreground-secondary transition-colors hover:border-danger/50 hover:text-danger focus-visible:outline-none">Review unstake</button><button type="button" onClick={() => toast.info(`${product.asset} claim preview`, { description: `No reward claim will be submitted. Reference value: $${product.earned.toFixed(2)}.` })} className="inline-flex items-center justify-center gap-1.5 rounded-lg bg-primary px-3 py-2.5 text-xs font-semibold text-primary-foreground transition-transform duration-150 hover:bg-primary/90 active:scale-[0.98] focus-visible:outline-none">Review claim <ArrowRight className="size-3.5" aria-hidden="true" /></button></> : <button type="button" onClick={() => onAction(`${product.asset} stake preview`, `No position will be created. Reference minimum: ${product.minAmount} ${product.symbol}.`)} className="col-span-2 inline-flex items-center justify-center gap-1.5 rounded-lg bg-primary px-3 py-2.5 text-xs font-semibold text-primary-foreground transition-transform duration-150 hover:bg-primary/90 active:scale-[0.98] focus-visible:outline-none">Review stake <ArrowRight className="size-3.5" aria-hidden="true" /></button>}</div></div></article>;
}
function Metric({ label, value, className = '' }: { label: string; value: string; className?: string }) { return <div><p className="text-xs font-medium uppercase tracking-[0.1em] text-foreground-muted">{label}</p><p className={`mt-1.5 font-mono text-sm font-semibold ${className || 'text-foreground'}`}>{value}</p></div>; }
function AvailabilityPanel({ id, icon: Icon, title, description, action, onAction }: { id: string; icon: typeof CircleDollarSign; title: string; description: string; action: string; onAction: () => void }) { return <section id={id} role="tabpanel" className="rounded-2xl border border-border bg-card/75 p-6 text-center shadow-[0_24px_80px_rgba(3,7,34,0.18)] backdrop-blur-xl sm:p-10"><span className="mx-auto inline-flex size-12 items-center justify-center rounded-2xl bg-primary/15 text-primary"><Icon className="size-6" aria-hidden="true" /></span><h2 className="mt-4 text-xl font-semibold text-foreground">{title}</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-foreground-secondary">{description}</p><button type="button" onClick={onAction} className="mt-5 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground transition-transform duration-150 hover:bg-primary/90 active:scale-[0.98] focus-visible:outline-none">{action}</button></section>; }
