import React from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { Activity, CheckCircle2, Clock3, Radar, ShieldAlert, ShieldCheck, TriangleAlert } from "lucide-react";

const statusTone = (status: string) => status === "OPERATIONAL" || status === "SAFE" ? "text-success border-success/30 bg-success/10" : status === "DEGRADED" || status === "REVIEW_REQUIRED" ? "text-warning border-warning/30 bg-warning/10" : "text-danger border-danger/30 bg-danger/10";

export default function NexusCommand() {
  const { user } = useAuth();
  const { language } = useLanguage();
  const ar = language === "ar";
  const copy = ar ? {
    eyebrow: "نظام تشغيل المخاطر والأدلة", title: "Nexus Command", description: "راقب ما حدث، سبب أهميته، ودليله قبل اعتماد أي إجراء حساس.", signin: "سجّل الدخول لعرض أدلة حسابك ومراكزك الورقية وسجل الموافقات.", health: "صحة المراقبة", score: "درجة المخاطر", timeline: "الخط الزمني الذكي", shield: "Nexus Shield", evaluate: "فحص Shield الآن", actions: "معاينة إجراء", enable: "معاينة تفعيل وضع الحماية", disable: "معاينة إيقاف وضع الحماية", approve: "اعتماد", reject: "رفض", cancel: "إلغاء", insufficient: "دليل غير كافٍ", active: "نشط", positions: "المراكز النشطة", incidents: "الحوادث المفتوحة", alerts: "التنبيهات", approvals: "الموافقات المعلقة", source: "دليل محفوظ", heartbeat: "فحص Heartbeat مُدار", noTimeline: "لا توجد أحداث محفوظة بعد. لن ينشئ Nexus حدثًا أو نتيجة من دون دليل." } : {
    eyebrow: "Evidence and risk operating system", title: "Nexus Command", description: "Observe what happened, why it matters, and the stored evidence before approving a sensitive action.", signin: "Sign in to inspect your account evidence, paper positions, and approval history.", health: "Monitoring health", score: "Risk score", timeline: "Intelligent activity timeline", shield: "Nexus Shield", evaluate: "Evaluate Shield now", actions: "Action preview", enable: "Preview enabling Security Mode", disable: "Preview disabling Security Mode", approve: "Approve", reject: "Reject", cancel: "Cancel", insufficient: "Insufficient evidence", active: "Active", positions: "Active positions", incidents: "Open incidents", alerts: "Alerts", approvals: "Pending approvals", source: "Stored evidence", heartbeat: "Managed Heartbeat check", noTimeline: "No stored events yet. Nexus will not invent an event or outcome without evidence." };
  const utils = trpc.useUtils();
  const overview = trpc.nexusCommand.overview.useQuery(undefined, { enabled: Boolean(user), refetchInterval: user ? 30_000 : false });
  const timeline = trpc.nexusCommand.timeline.useQuery({ limit: 30 }, { enabled: Boolean(user), refetchInterval: user ? 30_000 : false });
  const shield = trpc.nexusCommand.evaluateShield.useMutation({ onSuccess: () => { void utils.nexusCommand.overview.invalidate(); void utils.nexusCommand.timeline.invalidate(); } });
  const preview = trpc.nexusCommand.previewAction.useMutation({ onSuccess: () => { void utils.nexusCommand.overview.invalidate(); } });
  const resolve = trpc.nexusCommand.resolveApproval.useMutation({ onSuccess: () => { void utils.nexusCommand.overview.invalidate(); void utils.nexusCommand.timeline.invalidate(); } });
  const pending = preview.data?.approvalId ? { id: preview.data.approvalId, status: preview.data.previewStatus } : null;
  const health = overview.data?.health;
  const risk = overview.data?.risk;
  const counts = overview.data?.counts;

  return <main className="nexus-surface min-h-full text-foreground"><section className="container py-5 sm:py-7 lg:py-8">
    <header id="monitoring" className="nx-panel scroll-mt-20 p-4 sm:p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div className="max-w-3xl"><p className="nexus-eyebrow">{copy.eyebrow}</p><h1 className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">{copy.title}</h1><p className="mt-2 text-sm leading-6 text-foreground-secondary">{copy.description}</p></div><span className={`inline-flex w-fit items-center gap-2 rounded-md border px-3 py-1.5 text-xs font-bold ${statusTone(health?.engineStatus ?? "UNCONFIGURED")}`}><Activity className="size-3.5" />{health?.engineStatus ?? copy.insufficient}</span></div></header>
    {!user ? <div className="mt-5 rounded-md border border-warning/25 bg-warning/10 p-5 text-sm text-foreground-secondary">{copy.signin}</div> : <div className="mt-5 space-y-4">
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label={copy.score} value={risk?.overallScore === null || risk?.overallScore === undefined ? copy.insufficient : `${risk.overallScore}/100`} icon={<Radar className="size-4" />} /><Metric label={copy.positions} value={String(counts?.activePositions ?? 0)} icon={<Activity className="size-4" />} /><Metric label={copy.incidents} value={String(counts?.openIncidents ?? 0)} icon={<ShieldAlert className="size-4" />} /><Metric label={copy.alerts} value={String(counts?.activeAlerts ?? 0)} icon={<TriangleAlert className="size-4" />} /><Metric label={copy.approvals} value={String(counts?.pendingApprovals ?? 0)} icon={<Clock3 className="size-4" />} /><Metric label={copy.health} value={health?.dataFreshnessState ?? copy.insufficient} icon={<CheckCircle2 className="size-4" />} /></section>
      <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]"><div id="activity" className="nx-panel scroll-mt-20 p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="nexus-eyebrow">Activity</p><h2 className="mt-1 text-base font-bold">{copy.timeline}</h2><p className="mt-1 text-xs text-foreground-secondary">{copy.source} · {copy.heartbeat}</p></div><Button size="sm" variant="outline" onClick={() => shield.mutate()} disabled={shield.isPending}><ShieldCheck className="size-4" />{copy.evaluate}</Button></div><div id="evidence" className="mt-4 scroll-mt-20 space-y-2">{timeline.data?.length ? timeline.data.map((event) => <details key={event.id} className="rounded-md border border-border bg-background-secondary/50 p-3"><summary className="cursor-pointer list-none"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{event.eventType}</p><p className="mt-1 text-xs text-foreground-secondary">{event.source} · {new Date(event.occurredAt).toLocaleString()}</p></div><span className="rounded-md border border-border px-2 py-1 text-[10px] font-bold text-foreground-secondary">{event.severity}</span></div></summary><pre dir="ltr" className="mt-3 max-h-40 overflow-auto rounded-md bg-background p-2 text-[10px] leading-5 text-foreground-secondary">{event.evidenceJson}</pre></details>) : <p className="rounded-md border border-dashed border-border p-4 text-sm text-foreground-secondary">{copy.noTimeline}</p>}</div></div>
      <aside className="space-y-4"><section className="nx-panel p-4"><h2 className="flex items-center gap-2 text-base font-bold"><ShieldCheck className="size-4 text-primary" />{copy.shield}</h2><p className="mt-2 text-xs leading-5 text-foreground-secondary">{ar ? "يفحص Shield سجلات المراقبة المحفوظة فقط. لا يضيف سببًا أو نتيجة دون دليل." : "Shield evaluates stored monitoring records only. It never creates a reason or outcome without evidence."}</p><div className="mt-3 grid gap-2 text-xs text-foreground-secondary"><span>{ar ? "المخاطر السوقية" : "Market risk"}: {risk?.marketRisk ?? copy.insufficient}</span><span>{ar ? "مخاطر المركز" : "Position risk"}: {risk?.positionRisk ?? copy.insufficient}</span><span>{ar ? "مخاطر النظام" : "System risk"}: {risk?.systemRisk ?? copy.insufficient}</span><span>{ar ? "مخاطر المراقبة" : "Monitoring risk"}: {risk?.monitoringRisk ?? copy.insufficient}</span></div></section><section id="actions" className="nx-panel scroll-mt-20 p-4"><h2 className="text-base font-bold">{copy.actions}</h2><p className="mt-2 text-xs leading-5 text-foreground-secondary">{ar ? "كل معاينة تشرح الأثر والدليل قبل الموافقة. لا تمنح أي صلاحية تنفيذ تداول." : "Each preview explains impact and evidence before approval. It grants no trading-execution permission."}</p><div className="mt-3 grid gap-2"><Button size="sm" variant="outline" onClick={() => preview.mutate({ actionType: "ENABLE_SECURITY_MODE" })} disabled={preview.isPending}>{copy.enable}</Button><Button size="sm" variant="outline" onClick={() => preview.mutate({ actionType: "DISABLE_SECURITY_MODE" })} disabled={preview.isPending}>{copy.disable}</Button></div>{pending ? <div id="approvals" className="mt-3 scroll-mt-20 rounded-md border border-border bg-background-secondary/60 p-3"><p className="text-xs font-semibold">#{pending.id} · {pending.status}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={() => resolve.mutate({ approvalId: pending.id, decision: "APPROVE" })} disabled={resolve.isPending}>{copy.approve}</Button><Button size="sm" variant="outline" onClick={() => resolve.mutate({ approvalId: pending.id, decision: "REJECT" })} disabled={resolve.isPending}>{copy.reject}</Button><Button size="sm" variant="ghost" onClick={() => resolve.mutate({ approvalId: pending.id, decision: "CANCEL" })} disabled={resolve.isPending}>{copy.cancel}</Button></div></div> : <div id="approvals" className="scroll-mt-20" />}</section></aside></section>
    </div>}</section></main>;
}

function Metric({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <article className="nx-panel p-3"><div className="flex items-center justify-between text-foreground-secondary">{icon}<span className="text-[10px] font-bold uppercase tracking-[0.12em]">{label}</span></div><p className="mt-3 text-lg font-bold text-foreground">{value}</p></article>; }
