import { ArrowUpRight, Download, Eye, EyeOff, LockKeyhole, PieChart, Send, TrendingDown, TrendingUp, Wallet } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'wouter';

type Asset = { id: string; name: string; symbol: string; amount: number; price: number; value: number; change24h: number; percentage: number; };
const assets: Asset[] = [
  { id: 'btc', name: 'Bitcoin', symbol: 'BTC', amount: 2.5, price: 45230.50, value: 113076.25, change24h: 2.45, percentage: 45 },
  { id: 'eth', name: 'Ethereum', symbol: 'ETH', amount: 15.3, price: 2450.75, value: 37516.48, change24h: 1.85, percentage: 15 },
  { id: 'sol', name: 'Solana', symbol: 'SOL', amount: 250, price: 98.45, value: 24612.50, change24h: -1.23, percentage: 10 },
  { id: 'xrp', name: 'XRP', symbol: 'XRP', amount: 5000, price: 2.15, value: 10750.00, change24h: 3.12, percentage: 4 },
  { id: 'ada', name: 'Cardano', symbol: 'ADA', amount: 3500, price: 0.92, value: 3220.00, change24h: 0.45, percentage: 1 },
  { id: 'usdt', name: 'Tether', symbol: 'USDT', amount: 15000, price: 1, value: 15000.00, change24h: 0, percentage: 6 },
];

export default function PortfolioPremium() {
  const [showValues, setShowValues] = useState(true);
  const summary = useMemo(() => { const total = assets.reduce((sum, asset) => sum + asset.value, 0); const change = assets.reduce((sum, asset) => sum + (asset.value * asset.change24h) / 100, 0); const largest = assets.reduce((largestAsset, asset) => asset.percentage > largestAsset.percentage ? asset : largestAsset, assets[0]); return { total, change, percent: (change / total) * 100, largest }; }, []);
  const value = (amount: number) => showValues ? formatCurrency(amount) : '••••••';
  return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-border bg-background/70 backdrop-blur-xl"><div className="container flex flex-col gap-4 py-5 sm:flex-row sm:items-end sm:justify-between sm:py-7"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-foreground-muted">Premium portfolio view</p><h1 className="mt-1 flex items-center gap-2 text-2xl font-semibold tracking-tight sm:text-3xl"><Wallet className="size-6 text-primary" aria-hidden="true" />Portfolio premium</h1><p className="mt-1 max-w-2xl text-sm text-foreground-secondary">A privacy-aware, high-context preview of allocation and holdings.</p></div><button type="button" onClick={() => setShowValues((visible) => !visible)} className="inline-flex w-fit items-center gap-2 rounded-xl border border-border bg-background-secondary px-4 py-2.5 text-sm font-semibold text-foreground-secondary transition-colors hover:text-foreground focus-visible:outline-none" aria-pressed={!showValues} aria-label={showValues ? 'Hide portfolio values' : 'Show portfolio values'}>{showValues ? <EyeOff className="size-4" aria-hidden="true" /> : <Eye className="size-4" aria-hidden="true" />}{showValues ? 'Hide values' : 'Show values'}</button></div></header>
    <div className="container max-w-6xl py-5 sm:py-7 lg:py-8"><div className="flex gap-3 rounded-2xl border border-border bg-card/75 p-4 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl"><LockKeyhole className="mt-0.5 size-5 shrink-0 text-primary" aria-hidden="true" /><p className="text-sm leading-6 text-foreground-secondary"><span className="font-semibold text-foreground">Illustrative portfolio data.</span> Values are deterministic preview data, not connected account balances or live prices. Privacy mode only hides values in this browser view.</p></div>
      <section className="mt-5 rounded-2xl border border-border bg-card/75 p-4 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl sm:p-5"><div className="grid gap-6 sm:grid-cols-3"><Metric label="Total reference value" value={value(summary.total)} detail={<Movement value={summary.percent} secondary={showValues ? `${summary.change >= 0 ? '+' : ''}${formatCurrency(summary.change)} illustrative change` : 'Privacy mode active'} />} /><Metric label="Largest allocation" value={`${summary.largest.percentage}%`} detail={`${summary.largest.symbol} reference allocation`} /><Metric label="Tracked assets" value={`${assets.length}`} detail="Six deterministic asset snapshots" /></div></section>
      <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-border bg-card/75 p-4 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl sm:p-5"><div className="flex items-center gap-2"><PieChart className="size-5 text-primary" aria-hidden="true" /><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-muted">Distribution</p><h2 className="mt-1 text-lg font-semibold">Reference allocation</h2></div></div><div className="mt-5 space-y-4">{assets.map((asset) => <div key={asset.id}><div className="flex items-center justify-between gap-4"><span className="font-mono text-sm font-semibold">{asset.symbol}</span><span className="text-sm text-foreground-secondary">{asset.percentage}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-background-secondary"><div className="h-full rounded-full bg-gradient-to-r from-primary to-violet-400" style={{ width: `${asset.percentage}%` }} aria-label={`${asset.symbol} allocation ${asset.percentage}%`} /></div></div>)}</div></section>
        <section className="rounded-2xl border border-border bg-card/75 p-4 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl sm:p-5"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-muted">Existing actions</p><h2 className="mt-1 text-lg font-semibold">Continue in a workspace</h2><p className="mt-1 text-sm leading-6 text-foreground-secondary">These actions route to their configured application workflows; this preview does not initiate a transfer or order.</p><div className="mt-5 grid grid-cols-2 gap-3"><Action href="/deposit" icon={<Download className="size-4" aria-hidden="true" />} label="Deposit" /><Action href="/withdraw" icon={<Send className="size-4" aria-hidden="true" />} label="Withdraw" /><Action href="/trading" icon={<TrendingUp className="size-4" aria-hidden="true" />} label="Trade" /><Action href="/wallet" icon={<Wallet className="size-4" aria-hidden="true" />} label="Wallet" /></div></section></div>
      <section className="mt-5 overflow-hidden rounded-2xl border border-border bg-card/75 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl"><header className="border-b border-border p-4 sm:p-5"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-muted">Reference ledger</p><h2 className="mt-1 text-lg font-semibold">Asset holdings</h2></header><div className="hidden grid-cols-[minmax(0,1.2fr)_minmax(90px,0.7fr)_minmax(100px,0.85fr)_minmax(110px,0.95fr)_minmax(95px,0.75fr)] gap-3 border-b border-border px-4 py-3 text-[10px] font-semibold uppercase tracking-[0.11em] text-foreground-muted lg:grid"><span>Asset</span><span className="text-right">Amount</span><span className="text-right">Reference price</span><span className="text-right">Reference value</span><span className="text-right">24h change</span></div><div className="divide-y divide-border">{assets.map((asset) => <article key={asset.id} className="p-4 transition-colors hover:bg-background-secondary/45 sm:p-5"><div className="hidden grid-cols-[minmax(0,1.2fr)_minmax(90px,0.7fr)_minmax(100px,0.85fr)_minmax(110px,0.95fr)_minmax(95px,0.75fr)] items-center gap-3 lg:grid"><AssetName asset={asset} /><p className="text-right font-mono text-sm text-foreground-secondary">{asset.amount.toLocaleString('en-US')}</p><p className="text-right font-mono text-sm text-foreground-secondary">{formatCurrency(asset.price)}</p><p className="text-right font-mono text-sm font-semibold">{value(asset.value)}</p><Movement value={asset.change24h} className="justify-end" /></div><div className="lg:hidden"><div className="flex items-start justify-between gap-3"><AssetName asset={asset} /><Movement value={asset.change24h} /></div><div className="mt-4 grid grid-cols-2 gap-3 border-t border-border pt-4"><Data label="Amount" value={asset.amount.toLocaleString('en-US')} /><Data label="Reference price" value={formatCurrency(asset.price)} /><Data label="Reference value" value={value(asset.value)} /><Data label="Allocation" value={`${asset.percentage}%`} /></div></div></article>)}</div></section></div></main>;
}
function Metric({ label, value, detail }: { label: string; value: string; detail: React.ReactNode }) { return <div className="min-w-0"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-foreground-muted">{label}</p><p className="mt-2 truncate font-mono text-2xl font-semibold sm:text-3xl">{value}</p><div className="mt-2 text-sm text-foreground-secondary">{detail}</div></div>; }
function Movement({ value, secondary, className = '' }: { value: number; secondary?: string; className?: string }) { const positive = value >= 0; const neutral = value === 0; const tone = neutral ? 'text-foreground-secondary' : positive ? 'text-success' : 'text-danger'; return <span className={`flex items-center gap-1.5 text-sm font-semibold ${tone} ${className}`}>{neutral ? <span className="size-1.5 rounded-full bg-foreground-muted" aria-hidden="true" /> : positive ? <TrendingUp className="size-4" aria-hidden="true" /> : <TrendingDown className="size-4" aria-hidden="true" />}{secondary ?? `${positive ? '+' : ''}${value.toFixed(2)}%`}</span>; }
function AssetName({ asset }: { asset: Asset }) { return <div className="min-w-0"><p className="font-mono text-sm font-semibold">{asset.symbol}/USDT</p><p className="mt-1 truncate text-sm text-foreground-secondary">{asset.name}</p></div>; }
function Data({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-foreground-muted">{label}</p><p className="mt-1 truncate font-mono text-sm font-semibold text-foreground-secondary">{value}</p></div>; }
function Action({ href, icon, label }: { href: string; icon: React.ReactNode; label: string }) { return <Link href={href} className="inline-flex min-h-24 flex-col items-start justify-between rounded-xl border border-border bg-background-secondary p-3 text-left transition-colors hover:border-primary/35 hover:bg-primary/8 focus-visible:outline-none"><span className="inline-flex size-8 items-center justify-center rounded-lg bg-primary/10 text-primary">{icon}</span><span className="mt-4 flex w-full items-center justify-between gap-2 text-sm font-semibold">{label}<ArrowUpRight className="size-4 text-foreground-muted" aria-hidden="true" /></span></Link>; }
function formatCurrency(value: number) { return `$${value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
