import { type ReactNode } from 'react';
import { AlertTriangle, ChevronRight, Info, KeyRound, Laptop, Lock, ShieldAlert, ShieldCheck, Smartphone } from 'lucide-react';
import { toast } from 'sonner';

type SecurityControl = { id: string; title: string; description: string; icon: typeof ShieldCheck; action: string };

const controls: SecurityControl[] = [
  { id: 'twoFactor', title: 'Additional-factor layout', description: 'A real account would expose configuration and verified state here.', icon: Smartphone, action: 'Review boundary' },
  { id: 'passkey', title: 'Passkey layout', description: 'A real account would expose supported-device enrollment here.', icon: Lock, action: 'Review boundary' },
  { id: 'allowlist', title: 'Destination allowlist layout', description: 'A real custody service would expose approved transfer destinations here.', icon: ShieldCheck, action: 'Review boundary' },
  { id: 'antiPhishing', title: 'Anti-phishing layout', description: 'A real provider would expose an account-scoped anti-phishing setting here.', icon: AlertTriangle, action: 'Review boundary' },
];

export default function Security() {
  const unavailable = (label: string) => toast.info(`${label} is unavailable`, { description: 'This preview is not connected to an account, device, custody, identity, credential, or security-management provider.' });

  return (
    <main className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border bg-background/70 backdrop-blur-xl">
        <div className="container py-5 sm:py-7"><div className="flex items-start gap-3"><span className="inline-flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/15 text-primary"><ShieldCheck className="size-5" aria-hidden="true" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-foreground-muted">Account protection preview</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Security</h1><p className="mt-1 text-sm text-foreground-secondary">Review security-control, session, credential, and sensitive-action layouts without an operational account connection.</p></div></div></div>
      </header>

      <div className="container max-w-6xl py-5 sm:py-7 lg:py-8">
        <aside className="mb-5 rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm leading-6 text-foreground-secondary" aria-label="Security preview disclosure">Security posture, authentication state, device history, IP details, API keys, allowlists, identity checks, and account status are unavailable in this preview. Nothing on this page represents a verified protection state or a saved security configuration.</aside>
        <div className="space-y-5">
          <section className="grid gap-4 overflow-hidden rounded-2xl border border-border bg-card/75 p-5 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl sm:grid-cols-[1fr_auto] sm:items-center sm:p-6"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-foreground-muted">Security posture</p><div className="mt-2 flex items-end gap-3"><strong className="text-3xl font-semibold tracking-tight">Unavailable</strong><span className="mb-1 inline-flex items-center gap-1.5 rounded-full border border-border bg-background-secondary px-2.5 py-1 text-xs font-semibold text-foreground-secondary"><Info className="size-3.5" aria-hidden="true" />No source connected</span></div><p className="mt-2 max-w-xl text-sm leading-6 text-foreground-secondary">Connect a verified account and security-management provider before relying on a posture score, device history, credential inventory, or authentication status.</p></div><div className="flex size-24 items-center justify-center rounded-full border-8 border-border bg-background-secondary text-foreground-muted"><ShieldAlert className="size-8" aria-hidden="true" /></div></section>

          <SecurityCard eyebrow="Controls preview" title="Security-control layouts"><div className="divide-y divide-border">{controls.map((control) => { const Icon = control.icon; return <div key={control.id} className="flex flex-col gap-4 px-4 py-4 transition-colors hover:bg-background-secondary/50 sm:flex-row sm:items-center sm:px-5"><span className="inline-flex size-10 shrink-0 items-center justify-center rounded-xl border border-border bg-background-secondary text-foreground-muted"><Icon className="size-4.5" aria-hidden="true" /></span><div className="min-w-0 flex-1"><h3 className="text-sm font-semibold">{control.title}</h3><p className="mt-1 text-sm leading-5 text-foreground-secondary">{control.description}</p></div><div className="flex items-center gap-2 sm:justify-end"><span className="inline-flex rounded-full bg-background-secondary px-2.5 py-1 text-xs font-semibold text-foreground-secondary">Not connected</span><button type="button" onClick={() => unavailable(control.title)} className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs font-semibold text-foreground-secondary transition-colors hover:border-primary/50 hover:text-foreground focus-visible:outline-none">{control.action}<ChevronRight className="size-3.5" aria-hidden="true" /></button></div></div>; })}</div></SecurityCard>

          <SecurityCard eyebrow="Sessions" title="Recent sign-ins"><div className="flex min-h-40 flex-col items-center justify-center px-5 py-8 text-center"><span className="inline-flex size-11 items-center justify-center rounded-xl bg-background-secondary text-foreground-muted"><Laptop className="size-5" aria-hidden="true" /></span><h3 className="mt-3 text-sm font-semibold">Session data unavailable</h3><p className="mt-1 max-w-sm text-sm leading-6 text-foreground-secondary">No device, browser, location, IP address, current session, or trusted-session record is loaded in this preview.</p><button type="button" onClick={() => unavailable('Session management')} className="mt-4 rounded-lg border border-border px-3 py-2 text-xs font-semibold text-foreground-secondary hover:border-primary/50 hover:text-foreground focus-visible:outline-none">Review boundary</button></div></SecurityCard>

          <SecurityCard eyebrow="Access" title="API keys"><div className="flex min-h-44 flex-col items-center justify-center px-5 py-8 text-center"><span className="inline-flex size-11 items-center justify-center rounded-xl bg-background-secondary text-foreground-muted"><KeyRound className="size-5" aria-hidden="true" /></span><h3 className="mt-3 text-sm font-semibold">Credential data unavailable</h3><p className="mt-1 max-w-sm text-sm leading-6 text-foreground-secondary">No API key identifiers, scopes, secrets, permissions, or rotation state is created or displayed in this preview.</p><button type="button" onClick={() => unavailable('API-key creation')} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-primary px-3.5 py-2.5 text-xs font-semibold text-primary-foreground transition-transform active:scale-[0.98] focus-visible:outline-none"><KeyRound className="size-3.5" aria-hidden="true" />Review boundary</button></div></SecurityCard>

          <section className="rounded-2xl border border-destructive/35 bg-destructive/8 p-5"><div className="flex gap-3"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-destructive" aria-hidden="true" /><div><p className="text-sm font-semibold text-destructive">Sensitive account actions</p><p className="mt-1 max-w-2xl text-sm leading-6 text-foreground-secondary">Password changes, account deactivation, and deletion require a connected account plus secure identity verification. They are intentionally unavailable in this preview.</p><div className="mt-4 flex flex-wrap gap-2"><DangerButton label="Change password" onClick={unavailable} /><DangerButton label="Disable account" onClick={unavailable} /><DangerButton label="Delete account" onClick={unavailable} /></div></div></div></section>
        </div>
      </div>
    </main>
  );
}

function SecurityCard({ eyebrow, title, children }: { eyebrow: string; title: string; children: ReactNode }) { return <section className="overflow-hidden rounded-2xl border border-border bg-card/75 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl"><header className="border-b border-border px-4 py-4 sm:px-5"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-muted">{eyebrow}</p><h2 className="mt-0.5 text-base font-semibold">{title}</h2></header>{children}</section>; }
function DangerButton({ label, onClick }: { label: string; onClick: (label: string) => void }) { return <button type="button" onClick={() => onClick(label)} className="rounded-lg border border-destructive/45 px-3 py-2 text-xs font-semibold text-destructive transition-colors hover:bg-destructive/10 focus-visible:outline-none">{label}</button>; }
