import React, { useEffect, useState } from 'react';
import { Bell, Eye, Globe, KeyRound, Lock, Moon, Settings as SettingsIcon, Sun, Volume2, Zap } from 'lucide-react';
import { toast } from 'sonner';
import { useTheme } from '@/contexts/ThemeContext';
import { useLanguage } from '@/contexts/LanguageContext';
import { useWorkspaceDensity } from '@/contexts/WorkspaceDensityContext';
import { WORKSPACE_PREFERENCES_KEY, type WorkspaceDensity } from '@/lib/workspaceDensity';
import { NexusDensityControl } from '@/components/NexusDensityControl';
import { languageMetadata, type Language } from '@/i18n/messages';

type SettingKey = 'twoFA' | 'emailNotifications' | 'soundNotifications' | 'showBalances' | 'autoLogout';
type NotificationKey = 'trades' | 'prices' | 'security' | 'system';

export default function Settings() {
  const { theme, toggleTheme } = useTheme();
  const { language, setLanguage, t } = useLanguage();
  const languageOptions = Object.keys(languageMetadata) as Language[];
  const languageLabels = Object.fromEntries(languageOptions.map((value) => [value, languageMetadata[value].nativeName]));
  const { density } = useWorkspaceDensity();
  const [settings, setSettings] = useState<Record<SettingKey, boolean>>({ twoFA: false, emailNotifications: false, soundNotifications: false, showBalances: true, autoLogout: false });
  const [notifications, setNotifications] = useState<Record<NotificationKey, boolean>>({ trades: true, prices: true, security: true, system: true });
  const [currency, setCurrency] = useState('USD (US Dollar)');
  const [savedAt, setSavedAt] = useState<number | null>(null);
  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      const saved = window.localStorage.getItem(WORKSPACE_PREFERENCES_KEY);
      if (!saved) return;
      const parsed = JSON.parse(saved) as { settings?: Record<SettingKey, boolean>; notifications?: Record<NotificationKey, boolean>; currency?: string; density?: WorkspaceDensity; savedAt?: number };
      if (parsed.settings) setSettings((current) => ({ ...current, ...parsed.settings }));
      if (parsed.notifications) setNotifications((current) => ({ ...current, ...parsed.notifications }));
      if (typeof parsed.currency === 'string') setCurrency(parsed.currency);
      if (typeof parsed.savedAt === 'number') setSavedAt(parsed.savedAt);
    } catch {
      window.localStorage.removeItem(WORKSPACE_PREFERENCES_KEY);
    }
  }, []);
  const setSetting = (key: SettingKey) => setSettings((current) => ({ ...current, [key]: !current[key] }));
  const setNotification = (key: NotificationKey) => setNotifications((current) => ({ ...current, [key]: !current[key] }));
  const chooseTheme = (next: 'dark' | 'light') => { if (theme !== next) toggleTheme?.(); };
  const saveSettings = () => {
    const now = Date.now();
    window.localStorage.setItem(WORKSPACE_PREFERENCES_KEY, JSON.stringify({ settings, notifications, currency, density, savedAt: now }));
    setSavedAt(now);
    toast.success('Browser preferences saved', { description: 'Saved locally to this browser. Delivery, account security, and execution services remain unavailable.' });
  };

  return <main className="nexus-surface min-h-screen text-foreground"><header className="border-b border-border bg-background/72 backdrop-blur-xl"><div className="container py-6 sm:py-8"><div className="flex items-start gap-3"><span className="inline-flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/15 text-primary"><SettingsIcon className="size-5" aria-hidden="true" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Workspace controls</p><h1 className="mt-1 text-3xl font-semibold tracking-[-0.035em] sm:text-4xl">Settings</h1><p className="mt-1 text-sm text-foreground-secondary">Adjust browser-local display preferences and inspect non-operational delivery and protection patterns.</p></div></div></div></header>
    <div className="container max-w-5xl py-5 sm:py-7 lg:py-8"><div className="space-y-5"><aside className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm leading-6 text-foreground-secondary" aria-label="Settings scope">Theme and the preferences below save to this browser only. No account, email-delivery, execution, API, or security service is connected from this page.</aside><SettingsCard icon={Eye} eyebrow="Workspace" title="Display preferences"><PreferenceRow title="Theme" description="Set the interface color mode for this device."><div className="inline-flex rounded-xl border border-border bg-background-secondary p-1" role="group" aria-label="Theme preference"><ThemeButton active={theme === 'dark'} onClick={() => chooseTheme('dark')} icon={Moon} label="Dark" /><ThemeButton active={theme === 'light'} onClick={() => chooseTheme('light')} icon={Sun} label="Light" /></div></PreferenceRow><PreferenceRow title="Workspace density" description="Choose compact, comfortable, or spacious information density for the market command center and workspaces. This preference saves locally to this browser."><NexusDensityControl /></PreferenceRow><PreferenceRow title="Reference values preference" description="Saves a browser-local preference for reference-value presentation. It does not change protected balances or any execution behavior."><Toggle checked={settings.showBalances} onChange={() => setSetting('showBalances')} label="Reference values preference" /></PreferenceRow></SettingsCard>
        <SettingsCard icon={Bell} eyebrow="Delivery preview" title="Reference message preferences">{([{ key: 'trades', label: 'Reference trade messages', desc: 'Controls deterministic layout messages; no execution or delivery service is connected.' }, { key: 'prices', label: 'Reference price signals', desc: 'Controls reference market-signal presentation; no market alert service is connected.' }, { key: 'security', label: 'Reference security notices', desc: 'Controls security-pattern presentation; no sign-in or protection feed is connected.' }, { key: 'system', label: 'Reference platform notices', desc: 'Controls product-message presentation; no live service announcements are delivered.' }] as const).map((item) => <PreferenceRow key={item.key} title={item.label} description={item.desc}><Toggle checked={notifications[item.key]} onChange={() => setNotification(item.key)} label={item.label} /></PreferenceRow>)}</SettingsCard>
        <SettingsCard icon={Volume2} eyebrow="Signals preview" title="Sound and email patterns"><PreferenceRow title="Reference sound cue" description="Toggles the visual preference only; this terminal does not play an operational event alert."><Toggle checked={settings.soundNotifications} onChange={() => setSetting('soundNotifications')} label="Reference sound cue" /></PreferenceRow><PreferenceRow title="Reference email delivery" description="Toggles the visual preference only; this terminal does not send email."><Toggle checked={settings.emailNotifications} onChange={() => setSetting('emailNotifications')} label="Reference email delivery" /></PreferenceRow></SettingsCard>
        <SettingsCard icon={Lock} eyebrow="Protection preview" title="Security patterns"><PreferenceRow title="Two-factor layout" description="Displays a protection preference only; no authentication factor is configured here."><Toggle checked={settings.twoFA} onChange={() => setSetting('twoFA')} label="Two-factor layout" /></PreferenceRow><PreferenceRow title="Automatic sign-out layout" description="Displays a session-timeout preference only; no active session policy is changed."><Toggle checked={settings.autoLogout} onChange={() => setSetting('autoLogout')} label="Automatic sign-out layout" /></PreferenceRow></SettingsCard>
        <SettingsCard icon={Zap} eyebrow="Unavailable services" title="API access"><UnavailableRow icon={KeyRound} title="API-key management" description="Unavailable: no API-key management service or credentials are connected." /><UnavailableRow icon={Lock} title="IP allowlist" description="Unavailable: no network-policy service is connected." /></SettingsCard>
        <SettingsCard icon={Globe} eyebrow="Local display" title="Language and currency"><div className="grid gap-4 sm:grid-cols-2"><SelectField label={t('language')} value={language} onChange={(value) => setLanguage(value as Language)} options={languageOptions} optionLabels={languageLabels} /><SelectField label="Reference currency" value={currency} onChange={setCurrency} options={['USD (US Dollar)', 'EUR (Euro)', 'GBP (British Pound)', 'JPY (Japanese Yen)', 'CNY (Chinese Yuan)']} /></div></SettingsCard>
        <button type="button" onClick={saveSettings} className="w-full rounded-xl bg-primary px-4 py-3.5 text-sm font-semibold text-primary-foreground transition-transform duration-150 hover:bg-primary/90 active:scale-[0.98] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/40">Save browser preferences</button>{savedAt ? <p className="text-center text-xs text-foreground-muted" aria-live="polite">Saved locally {new Date(savedAt).toLocaleString()}.</p> : null}</div></div></main>;
}

function SettingsCard({ icon: Icon, eyebrow, title, children }: { icon: typeof SettingsIcon; eyebrow: string; title: string; children: React.ReactNode }) { return <section className="overflow-hidden rounded-2xl border border-border bg-card/75 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl"><header className="flex items-center gap-3 border-b border-border px-4 py-4 sm:px-5"><span className="inline-flex size-9 items-center justify-center rounded-lg bg-primary/12 text-primary"><Icon className="size-4.5" aria-hidden="true" /></span><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-muted">{eyebrow}</p><h2 className="mt-0.5 text-base font-semibold">{title}</h2></div></header><div className="divide-y divide-border">{children}</div></section>; }
function PreferenceRow({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="flex flex-col gap-4 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div className="max-w-xl"><h3 className="text-sm font-semibold text-foreground">{title}</h3><p className="mt-1 text-sm leading-5 text-foreground-secondary">{description}</p></div><div className="shrink-0">{children}</div></div>; }
function Toggle({ checked, onChange, label }: { checked: boolean; onChange: () => void; label: string }) { return <button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={onChange} className={`relative inline-flex h-7 w-12 items-center rounded-full transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 ${checked ? 'bg-primary' : 'bg-background-secondary ring-1 ring-border'}`}><span className={`inline-block size-5 rounded-full bg-white shadow-sm transition-transform ${checked ? 'translate-x-6' : 'translate-x-1'}`} /></button>; }
function ThemeButton({ active, onClick, icon: Icon, label }: { active: boolean; onClick: () => void; icon: typeof Moon; label: string }) { return <button type="button" aria-pressed={active} onClick={onClick} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-semibold transition-colors focus-visible:outline-none ${active ? 'bg-primary text-primary-foreground shadow-sm' : 'text-foreground-secondary hover:bg-card hover:text-foreground'}`}><Icon className="size-3.5" aria-hidden="true" />{label}</button>; }
function UnavailableRow({ icon: Icon, title, description }: { icon: typeof KeyRound; title: string; description: string }) { return <div className="flex w-full items-center gap-3 px-4 py-4 text-start sm:px-5" aria-label={`${title}: unavailable`}><span className="inline-flex size-9 shrink-0 items-center justify-center rounded-lg border border-border bg-background-secondary text-foreground-secondary"><Icon className="size-4" aria-hidden="true" /></span><span><span className="block text-sm font-semibold text-foreground">{title} <span className="ms-1 rounded bg-warning/15 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-warning">Unavailable</span></span><span className="mt-1 block text-sm text-foreground-secondary">{description}</span></span></div>; }
function SelectField({ label, value, onChange, options, optionLabels }: { label: string; value: string; onChange: (value: string) => void; options: string[]; optionLabels?: Record<string, string> }) { return <label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-[0.1em] text-foreground-muted">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-xl border border-border bg-background-secondary px-3.5 py-3 text-sm text-foreground outline-none transition-colors focus:border-primary focus:ring-2 focus:ring-primary/25">{options.map((option) => <option key={option} value={option}>{optionLabels?.[option] ?? option}</option>)}</select></label>; }
