import React, { useMemo, useState } from "react";
import { Activity, Archive, Beaker, Copy, LineChart, Play, Plus, Save, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import ProgressiveHistoricalCandles from "@/components/ProgressiveHistoricalCandles";
import { useLanguage } from "@/contexts/LanguageContext";

type EntryKind = "SMA_CROSSOVER" | "RSI_RECOVERY" | "BREAKOUT";
type ExitKind = "NONE" | "SMA_CROSSUNDER" | "RSI_OVERBOUGHT";
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const numeric = (value: string, fallback: number) => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; };

export default function StrategyLab() {
  const { language } = useLanguage();
  const tr = (en: string, ar: string) => language === "ar" ? ar : en;
  const utils = trpc.useUtils();
  const defaults = trpc.strategyLab.getDefaults.useQuery();
  const strategies = trpc.strategyLab.list.useQuery();
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const detail = trpc.strategyLab.get.useQuery({ strategyId: selectedId ?? 1 }, { enabled: selectedId !== null });
  const [name, setName] = useState(""); const [symbol, setSymbol] = useState("BTC"); const [interval, setInterval] = useState<"5m" | "15m" | "1h" | "4h" | "1d">("1h");
  const [entryKind, setEntryKind] = useState<EntryKind>("SMA_CROSSOVER"); const [exitKind, setExitKind] = useState<ExitKind>("NONE"); const [fast, setFast] = useState("10"); const [slow, setSlow] = useState("30"); const [threshold, setThreshold] = useState("30"); const [lookback, setLookback] = useState("20"); const [quantity, setQuantity] = useState("1"); const [stopMethod, setStopMethod] = useState<"fixed" | "atr" | "structure">("fixed"); const [initialEquity, setInitialEquity] = useState("100000"); const [riskPercent, setRiskPercent] = useState("1");
  const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [runResult, setRunResult] = useState<ReturnType<typeof useRunResult> | null>(null);
  const selected = detail.data;
  const refresh = () => { void utils.strategyLab.list.invalidate(); if (selectedId) void utils.strategyLab.get.invalidate({ strategyId: selectedId }); };
  const payload = useMemo(() => {
    const base = defaults.data?.risk;
    if (!base) return null;
    const entry = entryKind === "SMA_CROSSOVER" ? { type: "SMA_CROSSOVER" as const, fastPeriod: numeric(fast, 10), slowPeriod: numeric(slow, 30) } : entryKind === "RSI_RECOVERY" ? { type: "RSI_RECOVERY" as const, period: numeric(fast, 14), oversoldThreshold: numeric(threshold, 30) } : { type: "BREAKOUT" as const, lookback: numeric(lookback, 20) };
    const exit = exitKind === "SMA_CROSSUNDER" ? { type: "SMA_CROSSUNDER" as const, fastPeriod: numeric(fast, 10), slowPeriod: numeric(slow, 30) } : exitKind === "RSI_OVERBOUGHT" ? { type: "RSI_OVERBOUGHT" as const, period: numeric(fast, 14), overboughtThreshold: numeric(threshold, 70) } : { type: "NONE" as const };
    return { name: name.trim(), symbol: symbol.trim().toUpperCase(), interval, status: "ACTIVE" as const, rules: { version: 1 as const, entry, exit, requestedQuantity: numeric(quantity, 1) }, risk: { ...base, initialEquityUsd: numeric(initialEquity, base.initialEquityUsd), riskPerTradePercent: numeric(riskPercent, base.riskPerTradePercent), stopMethod } };
  }, [defaults.data, entryKind, exitKind, fast, initialEquity, interval, lookback, name, quantity, riskPercent, slow, stopMethod, symbol, threshold]);
  const create = trpc.strategyLab.create.useMutation({ onSuccess: (strategy) => { setSelectedId(strategy.id); refresh(); toast.success(tr("Paper strategy saved", "تم حفظ الاستراتيجية الورقية")); }, onError: (error) => toast.error(tr("Strategy was not saved", "لم يتم حفظ الاستراتيجية"), { description: error.message }) });
  const update = trpc.strategyLab.update.useMutation({ onSuccess: () => { refresh(); toast.success(tr("New immutable strategy revision saved", "تم حفظ نسخة استراتيجية جديدة غير قابلة للتعديل")); }, onError: (error) => toast.error(tr("Strategy was not updated", "لم يتم تحديث الاستراتيجية"), { description: error.message }) });
  const duplicate = trpc.strategyLab.duplicate.useMutation({ onSuccess: (strategy) => { setSelectedId(strategy.id); refresh(); toast.success(tr("Strategy duplicated as a draft", "تم نسخ الاستراتيجية كمسودة")); }, onError: (error) => toast.error(tr("Strategy was not duplicated", "لم يتم نسخ الاستراتيجية"), { description: error.message }) });
  const archive = trpc.strategyLab.archive.useMutation({ onSuccess: () => { setSelectedId(null); refresh(); toast.success(tr("Strategy archived; historical runs were retained", "تمت أرشفة الاستراتيجية مع الاحتفاظ بالتشغيلات التاريخية")); }, onError: (error) => toast.error(tr("Strategy was not archived", "لم تتم أرشفة الاستراتيجية"), { description: error.message }) });
  const run = trpc.strategyLab.run.useMutation({ onSuccess: (result) => { setRunResult(result as ReturnType<typeof useRunResult>); toast.success(tr("Historical paper simulation completed", "اكتملت المحاكاة الورقية التاريخية")); }, onError: (error) => toast.error(tr("Backtest was not started", "لم يبدأ الاختبار التاريخي"), { description: error.message }) });
  const selectStrategy = (id: number) => { setSelectedId(id); setRunResult(null); };
  const loadSelected = () => { if (!selected) return; setName(selected.name); setSymbol(selected.symbol); setInterval(selected.interval); setQuantity(String(selected.revision.rules.requestedQuantity)); setStopMethod(selected.revision.risk.stopMethod); setInitialEquity(String(selected.revision.risk.initialEquityUsd)); setRiskPercent(String(selected.revision.risk.riskPerTradePercent)); const entry = selected.revision.rules.entry; setEntryKind(entry.type); if (entry.type === "BREAKOUT") setLookback(String(entry.lookback)); else { setFast(String(entry.type === "SMA_CROSSOVER" ? entry.fastPeriod : entry.period)); if (entry.type === "SMA_CROSSOVER") setSlow(String(entry.slowPeriod)); else setThreshold(String(entry.oversoldThreshold)); } const exit = selected.revision.rules.exit; setExitKind(exit.type); };
  const submit = () => { if (!payload) return; if (!payload.name) { toast.error(tr("Name the strategy before saving.", "سمِّ الاستراتيجية قبل حفظها.")); return; } if (selectedId) update.mutate({ strategyId: selectedId, strategy: payload }); else create.mutate(payload); };
  const launch = () => { if (!selectedId || !startDate || !endDate) { toast.error(tr("Select a saved strategy and an explicit UTC date range.", "اختر استراتيجية محفوظة ونطاق تاريخ UTC صريحًا.")); return; } const startTime = Date.parse(`${startDate}T00:00:00.000Z`); const endTime = Date.parse(`${endDate}T00:00:00.000Z`); if (!Number.isFinite(startTime) || !Number.isFinite(endTime) || startTime >= endTime) { toast.error(tr("Historical end date must be after start date.", "يجب أن يكون تاريخ النهاية التاريخي بعد تاريخ البداية.")); return; } run.mutate({ strategyId: selectedId, dataset: { startTime, endTime } }); };
  const busy = create.isPending || update.isPending;
  return <main className="min-h-[calc(100vh-4rem)] bg-background px-4 py-7 text-foreground sm:px-6"><div className="mx-auto max-w-7xl"><header className="flex flex-col justify-between gap-5 border-b border-border pb-6 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">{tr("Strategy Lab · Historical paper simulation", "مختبر الاستراتيجيات · محاكاة ورقية تاريخية")}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{tr("Rule-based research with the 2.1 safety gate", "بحث قائم على القواعد مع بوابة السلامة 2.1")}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-foreground-secondary">{tr("Strategies run only against stored closed public candles. Each eligible entry passes the same sizing, stop, exposure, daily-protection and safety rules used by the paper-trading workspace. No exchange order can be placed here.", "تعمل الاستراتيجيات على شموع عامة مغلقة ومحفوظة فقط. ويمر كل دخول مؤهل بقواعد التحجيم والوقف والتعرض والحماية اليومية والسلامة نفسها المستخدمة في مساحة التداول الورقي. ولا يمكن تنفيذ أي أمر في بورصة من هنا.")}</p></div><div className="rounded-xl border border-warning/25 bg-warning/10 px-4 py-3 text-sm text-warning"><strong>{tr("Historical simulation only.", "محاكاة تاريخية فقط.")}</strong> {tr("Results are not a forecast or investment advice.", "النتائج ليست توقعًا أو نصيحة استثمارية.")}</div></header>
    <div className="mt-6 grid gap-6 xl:grid-cols-[300px_minmax(0,1fr)]"><aside className="rounded-2xl border border-border bg-card/70 p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">{tr("Saved strategies", "الاستراتيجيات المحفوظة")}</h2><button type="button" onClick={() => { setSelectedId(null); setName(""); setRunResult(null); }} className="rounded-lg border border-primary/30 p-2 text-primary hover:bg-primary/10 focus-visible:outline-none" aria-label={tr("Create new strategy", "إنشاء استراتيجية جديدة")}><Plus className="size-4" /></button></div><div className="mt-4 space-y-2">{strategies.isLoading ? <p className="text-sm text-foreground-muted">{tr("Loading private strategies…", "جارٍ تحميل الاستراتيجيات الخاصة…")}</p> : strategies.error ? <p className="rounded-xl border border-warning/25 bg-warning/10 p-4 text-sm text-warning">{tr("Private strategy data is unavailable until an authenticated session is available. No account records are shown here.", "بيانات الاستراتيجية الخاصة غير متاحة حتى تتوفر جلسة مصادقة. ولا تظهر أي سجلات حساب هنا.")}</p> : strategies.data?.length ? strategies.data.map((strategy) => <button type="button" key={strategy.id} onClick={() => selectStrategy(strategy.id)} className={`w-full rounded-xl border p-3 text-start transition-colors focus-visible:outline-none ${selectedId === strategy.id ? "border-primary/50 bg-primary/10" : "border-border hover:border-primary/30"}`}><span className="flex items-center justify-between gap-2"><strong>{strategy.name}</strong><span className="text-[10px] font-semibold text-foreground-muted">{strategy.status}</span></span><span dir="ltr" className="mt-1 block text-xs text-foreground-secondary">{strategy.symbol} · {strategy.interval} · rev {strategy.currentRevisionNumber}</span></button>) : <p className="rounded-xl border border-dashed border-border p-4 text-sm text-foreground-secondary">{tr("No strategy is stored for this account. Start with a bounded rule; no sample strategy is fabricated.", "لا توجد استراتيجية محفوظة لهذا الحساب. ابدأ بقاعدة محددة؛ ولا توجد استراتيجية نموذجية مصطنعة.")}</p>}</div></aside>
      <section className="min-w-0 space-y-6"><section className="rounded-2xl border border-border bg-card/70 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">{selected ? `${tr("Edit", "تعديل")} ${selected.name}` : tr("New paper strategy", "استراتيجية ورقية جديدة")}</h2><p className="mt-1 text-sm text-foreground-secondary">{tr("Saving an existing strategy creates a new immutable revision. Historical runs retain their original revision.", "يؤدي حفظ استراتيجية قائمة إلى إنشاء نسخة جديدة غير قابلة للتعديل. وتحتفظ التشغيلات التاريخية بنسختها الأصلية.")}</p></div>{selected ? <div className="flex flex-wrap gap-2"><button type="button" onClick={loadSelected} className="rounded-lg border border-border px-3 py-2 text-xs font-medium hover:border-primary/40 focus-visible:outline-none">{tr("Load revision", "تحميل النسخة")}</button><button type="button" onClick={() => duplicate.mutate({ strategyId: selected.id, name: `${selected.name} copy` })} className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs font-medium hover:border-primary/40 focus-visible:outline-none"><Copy className="size-3.5" />{tr("Duplicate", "نسخ")}</button><button type="button" onClick={() => archive.mutate({ strategyId: selected.id })} className="inline-flex items-center gap-1 rounded-lg border border-danger/30 px-3 py-2 text-xs font-medium text-danger hover:bg-danger/10 focus-visible:outline-none"><Archive className="size-3.5" />{tr("Archive", "أرشفة")}</button></div> : null}</div>
        <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label={tr("Strategy name", "اسم الاستراتيجية")}><input value={name} onChange={(event) => setName(event.target.value)} className="terminal-input" maxLength={100} placeholder={tr("e.g. BTC breakout research", "مثال: بحث اختراق BTC")} /></Field><Field label={tr("Asset", "الأصل")}><input dir="ltr" value={symbol} onChange={(event) => setSymbol(event.target.value.toUpperCase())} className="terminal-input" maxLength={15} /></Field><Field label={tr("Candle interval", "فاصل الشموع")}><select dir="ltr" value={interval} onChange={(event) => setInterval(event.target.value as typeof interval)} className="terminal-input">{["5m", "15m", "1h", "4h", "1d"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label={tr("Requested quantity", "الكمية المطلوبة")}><input dir="ltr" value={quantity} onChange={(event) => setQuantity(event.target.value)} type="number" min="0" step="any" className="terminal-input" /></Field></div>
        <div className="mt-5 grid gap-4 lg:grid-cols-2"><RuleCard title={tr("Entry rule", "قاعدة الدخول")} icon={<Activity className="size-4" />}><select dir="ltr" value={entryKind} onChange={(event) => setEntryKind(event.target.value as EntryKind)} className="terminal-input"><option value="SMA_CROSSOVER">{tr("SMA crossover", "تقاطع SMA")}</option><option value="RSI_RECOVERY">{tr("RSI recovery", "تعافي RSI")}</option><option value="BREAKOUT">{tr("Breakout above prior high", "اختراق أعلى القمة السابقة")}</option></select><RuleFields kind={entryKind} fast={fast} slow={slow} threshold={threshold} lookback={lookback} setFast={setFast} setSlow={setSlow} setThreshold={setThreshold} setLookback={setLookback} /></RuleCard><RuleCard title={tr("Optional rule exit", "قاعدة خروج اختيارية")} icon={<LineChart className="size-4" />}><select dir="ltr" value={exitKind} onChange={(event) => setExitKind(event.target.value as ExitKind)} className="terminal-input"><option value="NONE">{tr("Risk stop / target only", "وقف/هدف المخاطرة فقط")}</option><option value="SMA_CROSSUNDER">{tr("SMA cross-under", "تقاطع SMA هابط")}</option><option value="RSI_OVERBOUGHT">{tr("RSI overbought", "RSI في تشبع شرائي")}</option></select>{exitKind !== "NONE" ? <RuleFields kind={exitKind} fast={fast} slow={slow} threshold={threshold} lookback={lookback} setFast={setFast} setSlow={setSlow} setThreshold={setThreshold} setLookback={setLookback} /> : <p className="mt-3 text-xs text-foreground-muted">{tr("Every accepted position still has a Version 2.1 protective stop and reward/risk target.", "يظل لكل مركز مقبول وقف حماية وهدف عائد/مخاطرة من الإصدار 2.1.")}</p>}</RuleCard></div>
        <div className="mt-5 grid gap-4 md:grid-cols-3"><Field label={tr("Stop method", "طريقة الوقف")}><select dir="ltr" value={stopMethod} onChange={(event) => setStopMethod(event.target.value as typeof stopMethod)} className="terminal-input"><option value="fixed">{tr("Fixed %", "نسبة ثابتة")}</option><option value="atr">{tr("ATR-based", "مبني على ATR")}</option><option value="structure">{tr("Market structure", "بنية السوق")}</option></select></Field><Field label={tr("Initial virtual equity (USD)", "رأس المال الافتراضي الأولي (USD)")}><input dir="ltr" value={initialEquity} onChange={(event) => setInitialEquity(event.target.value)} type="number" min="1000" className="terminal-input" /></Field><Field label={tr("Risk per trade (%)", "المخاطرة لكل صفقة (%)")}><input dir="ltr" value={riskPercent} onChange={(event) => setRiskPercent(event.target.value)} type="number" min="0" step="0.1" className="terminal-input" /></Field></div><button type="button" onClick={submit} disabled={!payload || busy} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-60 focus-visible:outline-none"><Save className="size-4" />{busy ? tr("Saving…", "جارٍ الحفظ…") : selected ? tr("Save new revision", "حفظ نسخة جديدة") : tr("Save strategy", "حفظ الاستراتيجية")}</button></section>
        <section className="rounded-2xl border border-border bg-card/70 p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-xl font-semibold">{tr("Run a reproducible historical test", "تشغيل اختبار تاريخي قابل لإعادة الإنتاج")}</h2><p className="mt-1 text-sm text-foreground-secondary">{tr("The range must contain 60–300 complete candles. The server records the actual provider, candle fingerprint and engine version with the result.", "يجب أن يحتوي النطاق على 60–300 شمعة مكتملة. ويسجل الخادم المزوّد الفعلي وبصمة الشموع ونسخة المحرك مع النتيجة.")}</p></div><span className="inline-flex items-center gap-2 text-xs text-success"><ShieldCheck className="size-4" />{tr("Risk Engine 2.1 enforced", "يُفرض محرك المخاطر 2.1")}</span></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label={tr("UTC start date", "تاريخ البداية UTC")}><input dir="ltr" value={startDate} onChange={(event) => setStartDate(event.target.value)} type="date" className="terminal-input" /></Field><Field label={tr("UTC end date (exclusive)", "تاريخ النهاية UTC (حصري)")}><input dir="ltr" value={endDate} onChange={(event) => setEndDate(event.target.value)} type="date" className="terminal-input" /></Field></div><button type="button" onClick={launch} disabled={!selectedId || run.isPending} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-success px-4 py-2.5 text-sm font-semibold text-success-foreground disabled:opacity-60 focus-visible:outline-none"><Play className="size-4" />{run.isPending ? tr("Capturing and running…", "جارٍ التقاط البيانات والتشغيل…") : tr("Run historical paper test", "تشغيل الاختبار الورقي التاريخي")}</button>{!selectedId ? <p className="mt-3 text-xs text-foreground-muted">{tr("Save or select a strategy before selecting a real historical range.", "احفظ أو اختر استراتيجية قبل تحديد نطاق تاريخي فعلي.")}</p> : null}</section>
        {runResult ? <ResultPanel result={runResult} /> : null}</section></div></div></main>;
}
function useRunResult() { return { id: 0, datasetId: 0, metrics: { initialEquityUsd: 0, finalEquityUsd: 0, netPnlUsd: 0, netPnlPercent: 0, tradeCount: 0, winRatePercent: null as number | null, maxDrawdownPercent: 0, maximumExposurePercent: 0, stopEventCount: 0, targetEventCount: 0, rejectedDecisionCount: 0 }, trades: [] as Array<{ sequence: number; decision: string; exitReason: string; netPnlUsd: number | null; entryPriceUsd: number | null; stopPriceUsd: number | null; targetPriceUsd: number | null }>, equityCurve: [] as Array<{ observedAt: number; equityUsd: number; drawdownPercent: number }> }; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-medium text-foreground-secondary"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function RuleCard({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <div className="rounded-xl border border-border bg-background/50 p-4"><h3 className="flex items-center gap-2 text-sm font-semibold">{icon}{title}</h3><div className="mt-3">{children}</div></div>; }
function RuleFields({ kind, fast, slow, threshold, lookback, setFast, setSlow, setThreshold, setLookback }: { kind: EntryKind | ExitKind; fast: string; slow: string; threshold: string; lookback: string; setFast: (value: string) => void; setSlow: (value: string) => void; setThreshold: (value: string) => void; setLookback: (value: string) => void }) { const { language } = useLanguage(); const tr = (en: string, ar: string) => language === "ar" ? ar : en; if (kind === "BREAKOUT") return <Field label={tr("Prior-high lookback", "فترة الرجوع للقمة السابقة")}><input dir="ltr" value={lookback} onChange={(event) => setLookback(event.target.value)} type="number" className="terminal-input mt-1" /></Field>; if (kind === "RSI_RECOVERY" || kind === "RSI_OVERBOUGHT") return <div className="mt-3 grid grid-cols-2 gap-3"><Field label={tr("RSI period", "فترة RSI")}><input dir="ltr" value={fast} onChange={(event) => setFast(event.target.value)} type="number" className="terminal-input mt-1" /></Field><Field label={kind === "RSI_RECOVERY" ? tr("Oversold threshold", "حد التشبع البيعي") : tr("Overbought threshold", "حد التشبع الشرائي")}><input dir="ltr" value={threshold} onChange={(event) => setThreshold(event.target.value)} type="number" className="terminal-input mt-1" /></Field></div>; return <div className="mt-3 grid grid-cols-2 gap-3"><Field label={tr("Fast period", "الفترة السريعة")}><input dir="ltr" value={fast} onChange={(event) => setFast(event.target.value)} type="number" className="terminal-input mt-1" /></Field><Field label={tr("Slow period", "الفترة البطيئة")}><input dir="ltr" value={slow} onChange={(event) => setSlow(event.target.value)} type="number" className="terminal-input mt-1" /></Field></div>; }
function ResultPanel({ result }: { result: ReturnType<typeof useRunResult> }) { const { language } = useLanguage(); const tr = (en: string, ar: string) => language === "ar" ? ar : en; const moneyFormat = new Intl.NumberFormat(language === "ar" ? "ar-EG-u-nu-latn" : "en-US", { style: "currency", currency: "USD" }); const metrics = result.metrics; return <section className="rounded-2xl border border-primary/25 bg-card/75 p-5"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">{tr("Stored historical run", "تشغيل تاريخي محفوظ")}</p><h2 className="mt-1 text-xl font-semibold">{tr("Simulation results", "نتائج المحاكاة")}</h2></div><Beaker className="size-7 text-primary" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label={tr("Net P/L", "صافي الربح/الخسارة")} value={`${moneyFormat.format(metrics.netPnlUsd)} (${metrics.netPnlPercent.toFixed(2)}%)`} tone={metrics.netPnlUsd >= 0 ? "success" : "danger"} /><Metric label={tr("Final equity", "رأس المال النهائي")} value={moneyFormat.format(metrics.finalEquityUsd)} /><Metric label={tr("Win rate", "نسبة الربح")} value={metrics.winRatePercent === null ? tr("Unavailable", "غير متاح") : `${metrics.winRatePercent.toFixed(1)}%`} /><Metric label={tr("Max drawdown", "أقصى تراجع")} value={`${metrics.maxDrawdownPercent.toFixed(2)}%`} tone="warning" /><Metric label={tr("Closed trades", "الصفقات المغلقة")} value={String(metrics.tradeCount)} /><Metric label={tr("Max exposure", "أقصى تعرض")} value={`${metrics.maximumExposurePercent.toFixed(1)}%`} /><Metric label={tr("Stops / targets", "الوقف / الأهداف")} value={`${metrics.stopEventCount} / ${metrics.targetEventCount}`} /><Metric label={tr("Gate rejections", "رفض البوابة")} value={String(metrics.rejectedDecisionCount)} /></div><ProgressiveHistoricalCandles datasetId={result.datasetId} trades={result.trades} /><EquityCurve points={result.equityCurve} /><div dir="ltr" className="mt-5 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-wide text-foreground-muted"><tr><th className="p-3">#</th><th className="p-3">{tr("Decision", "القرار")}</th><th className="p-3">{tr("Exit", "الخروج")}</th><th className="p-3 text-right">{tr("Net P/L", "صافي الربح/الخسارة")}</th></tr></thead><tbody>{result.trades.slice(0, 20).map((trade) => <tr key={trade.sequence} className="border-b border-border/60"><td className="p-3">{trade.sequence}</td><td className={`p-3 font-medium ${trade.decision === "ACCEPTED" ? "text-success" : "text-danger"}`}>{trade.decision}</td><td className="p-3 text-foreground-secondary">{trade.exitReason}</td><td className="p-3 text-right font-mono">{trade.netPnlUsd === null ? "—" : moneyFormat.format(trade.netPnlUsd)}</td></tr>)}</tbody></table></div></section>; }
function EquityCurve({ points }: { points: Array<{ observedAt: number; equityUsd: number; drawdownPercent: number }> }) { const { language } = useLanguage(); const tr = (en: string, ar: string) => language === "ar" ? ar : en; if (points.length < 2) return <p className="mt-5 rounded-xl border border-dashed border-border p-4 text-sm text-foreground-secondary">{tr("Equity curve is unavailable until this stored run has at least two measured points.", "منحنى رأس المال غير متاح حتى يحتوي هذا التشغيل المحفوظ على نقطتين مقاستين على الأقل.")}</p>; const values = points.map((point) => point.equityUsd); const minimum = Math.min(...values); const maximum = Math.max(...values); const span = maximum - minimum || 1; const polyline = points.map((point, index) => `${(index / (points.length - 1)) * 100},${100 - ((point.equityUsd - minimum) / span) * 100}`).join(" "); return <figure className="mt-5 rounded-xl border border-border bg-background/50 p-4" aria-label={tr("Measured equity curve", "منحنى رأس المال المقاس")}><figcaption className="flex items-center justify-between gap-3 text-sm"><span className="font-semibold">{tr("Measured equity curve", "منحنى رأس المال المقاس")}</span><span dir="ltr" className="font-mono text-xs text-foreground-muted">{money.format(minimum)} — {money.format(maximum)}</span></figcaption><svg style={{ direction: "ltr" }} viewBox="0 0 100 100" role="img" aria-label={tr("Equity values over the stored historical test", "قيم رأس المال على الاختبار التاريخي المحفوظ")} className="mt-3 h-40 w-full overflow-visible"><line x1="0" y1="100" x2="100" y2="100" stroke="currentColor" className="text-border" vectorEffect="non-scaling-stroke" /><polyline fill="none" stroke="currentColor" className="text-primary" strokeWidth="2" vectorEffect="non-scaling-stroke" points={polyline} /></svg><p className="mt-2 text-xs text-foreground-muted">{tr("Each point is persisted from the closed-candle simulation; it is not a forecast.", "تحفظ كل نقطة من محاكاة الشموع المغلقة؛ وهي ليست توقعًا.")}</p></figure>; }
function Metric({ label, value, tone = "default" }: { label: string; value: string; tone?: "default" | "success" | "danger" | "warning" }) { const color = tone === "success" ? "text-success" : tone === "danger" ? "text-danger" : tone === "warning" ? "text-warning" : "text-foreground"; return <div className="rounded-xl border border-border bg-background/50 p-3"><p className="text-xs text-foreground-muted">{label}</p><p className={`mt-1 font-mono text-sm font-semibold ${color}`}>{value}</p></div>; }
