import { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowDownLeft, ArrowUpRight, CircleOff, Download, Send, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';

interface WalletBalance { symbol: string; name: string; balance: number; value: number; }
interface Transaction { id: string; type: 'send' | 'receive'; asset: string; amount: number; reference: string; timestamp: string; status: 'reference'; }

const wallets: WalletBalance[] = [
  { symbol: 'BTC', name: 'Bitcoin', balance: 2.5, value: 113076.25 },
  { symbol: 'ETH', name: 'Ethereum', balance: 15.3, value: 37516.48 },
  { symbol: 'SOL', name: 'Solana', balance: 250, value: 24612.5 },
  { symbol: 'USDT', name: 'Tether', balance: 15000, value: 15000 },
];

const transactions: Transaction[] = [
  { id: '1', type: 'receive', asset: 'BTC', amount: 0.5, reference: 'Reference entry A', timestamp: 'Reference sequence 01', status: 'reference' },
  { id: '2', type: 'send', asset: 'ETH', amount: 2.5, reference: 'Reference entry B', timestamp: 'Reference sequence 02', status: 'reference' },
  { id: '3', type: 'receive', asset: 'USDT', amount: 5000, reference: 'Reference entry C', timestamp: 'Reference sequence 03', status: 'reference' },
  { id: '4', type: 'send', asset: 'SOL', amount: 100, reference: 'Reference entry D', timestamp: 'Reference sequence 04', status: 'reference' },
];

export default function Wallet() {
  const [selectedWallet, setSelectedWallet] = useState('BTC');
  const [network, setNetwork] = useState('Ethereum (ERC-20)');
  const currentWallet = useMemo(() => wallets.find((wallet) => wallet.symbol === selectedWallet) ?? wallets[0], [selectedWallet]);

  const action = (label: string) => toast.info(`${label} preview`, { description: 'No wallet operation, transfer, address, or custody service is connected in this interface preview.' });

  return (
    <main className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border bg-background/70 backdrop-blur-xl"><div className="container flex flex-col gap-3 py-5 sm:flex-row sm:items-end sm:justify-between sm:py-7"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-foreground-muted">Custody preview</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Wallet</h1></div><div className="inline-flex items-center gap-2 self-start rounded-full border border-primary/25 bg-primary/10 px-3 py-1.5 text-xs font-semibold text-primary sm:self-auto"><ShieldCheck className="size-3.5" aria-hidden="true" /> No wallet connected</div></div></header>

      <div className="container py-5 sm:py-7 lg:py-8">
        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.28 }} className="space-y-5 lg:space-y-6">
          <aside className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm leading-6 text-foreground-secondary" aria-label="Wallet preview disclosure">Asset quantities, fiat values, activity rows, and network choices are deterministic interface examples. No custody account, wallet address, transfer, deposit, withdrawal, QR code, or export is connected; do not send funds based on this page.</aside>
          <section className="rounded-2xl border border-border bg-card/75 p-4 shadow-[0_24px_80px_rgba(3,7,34,0.18)] backdrop-blur-xl sm:p-5" aria-labelledby="wallet-selector-title"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-foreground-muted">Assets</p><h2 id="wallet-selector-title" className="mt-1 text-lg font-semibold">Select wallet</h2></div><span className="text-xs text-foreground-muted">{wallets.length} assets</span></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{wallets.map((wallet) => { const active = wallet.symbol === selectedWallet; return <button key={wallet.symbol} type="button" aria-pressed={active} onClick={() => setSelectedWallet(wallet.symbol)} className={`rounded-xl border p-3.5 text-left focus-visible:outline-none sm:p-4 ${active ? 'border-primary/70 bg-primary/12 shadow-[0_0_0_1px_rgba(112,75,255,0.18)]' : 'border-border bg-background-secondary hover:border-primary/40 hover:bg-card'}`}><div className="flex items-center justify-between gap-2"><span className="text-sm font-semibold text-foreground">{wallet.symbol}</span>{active && <span className="size-2 rounded-full bg-primary" aria-label="Selected" />}</div><p className="mt-1 text-xs text-foreground-secondary">{wallet.name}</p><p className="mt-3 font-mono text-sm font-semibold text-foreground">{wallet.balance.toLocaleString()} {wallet.symbol}</p><p className="mt-1 text-xs text-foreground-muted">{wallet.value.toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })}</p></button>; })}</div></section>

          <div className="grid grid-cols-1 gap-5 xl:grid-cols-12 xl:gap-6">
            <section className="min-w-0 rounded-2xl border border-border bg-card/75 p-5 shadow-[0_24px_80px_rgba(3,7,34,0.18)] backdrop-blur-xl sm:p-6 xl:col-span-8" aria-labelledby="wallet-detail-title"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-foreground-muted">{currentWallet.name} reference wallet</p><h2 id="wallet-detail-title" className="mt-2 font-mono text-3xl font-semibold tracking-tight text-foreground sm:text-5xl">{currentWallet.balance.toLocaleString()} {currentWallet.symbol}</h2><p className="mt-2 text-lg text-foreground-secondary">Illustrative value: {currentWallet.value.toLocaleString('en-US', { style: 'currency', currency: 'USD' })}</p><div className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_150px] lg:items-center"><div className="min-w-0 rounded-xl border border-border bg-background-secondary p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-foreground-muted">Wallet address</p><span className="inline-flex size-9 shrink-0 items-center justify-center rounded-lg border border-border text-foreground-muted" aria-label="No wallet address is configured"><CircleOff className="size-4" aria-hidden="true" /></span></div><p className="mt-3 font-mono text-sm leading-6 text-foreground-secondary">Address unavailable — no custody wallet is configured for this preview.</p></div><div className="rounded-xl border border-border bg-background-secondary p-4 text-center"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-foreground-muted">Receive code</p><div className="mx-auto mt-3 flex size-28 items-center justify-center rounded-lg border border-dashed border-border bg-card text-foreground-muted" aria-label="No receiving QR code is available"><CircleOff className="size-10" aria-hidden="true" /></div><p className="mt-2 text-xs text-foreground-muted">No code connected</p></div></div></section>

            <section className="rounded-2xl border border-border bg-card/75 p-5 shadow-[0_24px_80px_rgba(3,7,34,0.18)] backdrop-blur-xl sm:p-6 xl:col-span-4" aria-labelledby="wallet-actions-title"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-foreground-muted">Operations</p><h2 id="wallet-actions-title" className="mt-1 text-lg font-semibold">Preview actions</h2><div className="mt-5 grid grid-cols-2 gap-3"><ActionButton label="Deposit preview" icon={Download} tone="success" onClick={() => action('Deposit')} /><ActionButton label="Withdraw preview" icon={Send} tone="primary" onClick={() => action('Withdraw')} /><ActionButton label="Send preview" icon={ArrowUpRight} tone="accent" onClick={() => action('Send')} /><ActionButton label="Receive preview" icon={ArrowDownLeft} tone="warning" onClick={() => action('Receive')} /></div><label className="mt-6 block"><span className="mb-2 block text-xs font-semibold uppercase tracking-[0.12em] text-foreground-muted">Reference network</span><select value={network} onChange={(event) => setNetwork(event.target.value)} className="w-full rounded-xl border border-border bg-background-secondary px-3.5 py-3 text-sm text-foreground outline-none focus:border-primary focus:ring-2 focus:ring-primary/25"><option value="Ethereum (ERC-20)">Ethereum (ERC-20)</option><option value="BNB Smart Chain (BEP-20)">BNB Smart Chain (BEP-20)</option><option value="Polygon (MATIC)">Polygon (MATIC)</option><option value="Solana (SPL)">Solana (SPL)</option></select></label></section>
          </div>

          <section className="overflow-hidden rounded-2xl border border-border bg-card/75 shadow-[0_24px_80px_rgba(3,7,34,0.18)] backdrop-blur-xl" aria-labelledby="wallet-transactions-title"><div className="flex items-center justify-between border-b border-border px-4 py-4 sm:px-5"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-foreground-muted">Reference activity</p><h2 id="wallet-transactions-title" className="mt-1 text-lg font-semibold">Illustrative transaction layout</h2></div><button type="button" onClick={() => toast.info('Export unavailable', { description: 'No account activity is connected to export from this preview.' })} className="text-xs font-semibold text-primary hover:text-primary/80 focus-visible:outline-none">Review export boundary</button></div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[780px] text-sm"><thead className="border-b border-border bg-background-secondary/60 text-left text-xs font-medium uppercase tracking-[0.1em] text-foreground-muted"><tr><th className="px-5 py-3">Type</th><th className="px-5 py-3">Asset</th><th className="px-5 py-3">Reference</th><th className="px-5 py-3 text-right">Illustrative amount</th><th className="px-5 py-3 text-right">Sequence</th><th className="px-5 py-3 text-right">State</th></tr></thead><tbody className="divide-y divide-border">{transactions.map((transaction) => <TransactionTableRow key={transaction.id} transaction={transaction} />)}</tbody></table></div><div className="divide-y divide-border md:hidden">{transactions.map((transaction) => <TransactionMobileCard key={transaction.id} transaction={transaction} />)}</div></section>
        </motion.div>
      </div>
    </main>
  );
}

function ActionButton({ label, icon: Icon, tone, onClick }: { label: string; icon: typeof Download; tone: 'success' | 'primary' | 'accent' | 'warning'; onClick: () => void }) {
  const tones = { success: 'border-success/35 bg-success/10 text-success hover:bg-success/15', primary: 'border-primary/35 bg-primary/10 text-primary hover:bg-primary/15', accent: 'border-accent/35 bg-accent/10 text-accent hover:bg-accent/15', warning: 'border-warning/35 bg-warning/10 text-warning hover:bg-warning/15' };
  return <button type="button" onClick={onClick} className={`inline-flex min-h-20 flex-col items-center justify-center gap-2 rounded-xl border p-3 text-sm font-semibold focus-visible:outline-none ${tones[tone]}`}><Icon className="size-5" aria-hidden="true" />{label}</button>;
}

function TransactionTableRow({ transaction }: { transaction: Transaction }) { const receiving = transaction.type === 'receive'; return <tr className="hover:bg-background-secondary/55"><td className="px-5 py-4"><span className={`inline-flex size-8 items-center justify-center rounded-lg ${receiving ? 'bg-success/15 text-success' : 'bg-danger/15 text-danger'}`}>{receiving ? <ArrowDownLeft className="size-4" aria-hidden="true" /> : <ArrowUpRight className="size-4" aria-hidden="true" />}</span></td><td className="px-5 py-4 font-semibold text-foreground">{transaction.asset}</td><td className="max-w-48 truncate px-5 py-4 font-mono text-xs text-foreground-secondary">{transaction.reference}</td><td className={`px-5 py-4 text-right font-mono font-semibold ${receiving ? 'text-success' : 'text-danger'}`}>{receiving ? '+' : '-'}{transaction.amount}</td><td className="px-5 py-4 text-right text-foreground-secondary">{transaction.timestamp}</td><td className="px-5 py-4 text-right"><StatusBadge status={transaction.status} /></td></tr>; }
function TransactionMobileCard({ transaction }: { transaction: Transaction }) { const receiving = transaction.type === 'receive'; return <article className="p-4"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className={`inline-flex size-9 items-center justify-center rounded-lg ${receiving ? 'bg-success/15 text-success' : 'bg-danger/15 text-danger'}`}>{receiving ? <ArrowDownLeft className="size-4" aria-hidden="true" /> : <ArrowUpRight className="size-4" aria-hidden="true" />}</span><div><h3 className="font-semibold text-foreground">{receiving ? 'Reference received' : 'Reference sent'} {transaction.asset}</h3><p className="mt-0.5 text-xs text-foreground-muted">{transaction.timestamp}</p></div></div><div className="text-right"><p className={`font-mono font-semibold ${receiving ? 'text-success' : 'text-danger'}`}>{receiving ? '+' : '-'}{transaction.amount}</p><div className="mt-1"><StatusBadge status={transaction.status} /></div></div></div><p className="mt-3 truncate font-mono text-xs text-foreground-secondary">{transaction.reference}</p></article>; }
function StatusBadge({ status }: { status: Transaction['status'] }) { return <span className="inline-flex rounded-full bg-primary/15 px-2 py-1 text-[11px] font-semibold text-primary">{status === 'reference' ? 'Reference' : 'Unavailable'}</span>; }
