import { Heart, LineChart, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';

type WatchlistItem = { id: string; symbol: string; name: string; price: number | null; change24h: number | null; source: 'reference' | 'local' };
const snapshots: Record<string, Omit<WatchlistItem, 'id' | 'source'>> = {
  BTC: { symbol: 'BTC', name: 'Bitcoin', price: 63592.74, change24h: -3.02 },
  ETH: { symbol: 'ETH', name: 'Ethereum', price: 1881.50, change24h: -3.32 },
  SOL: { symbol: 'SOL', name: 'Solana', price: 137.33, change24h: -4.09 },
  BNB: { symbol: 'BNB', name: 'BNB', price: 566.59, change24h: -1.11 },
};
const initialItems: WatchlistItem[] = ['BTC', 'ETH'].map((symbol) => ({ id: `asset-${symbol}`, ...snapshots[symbol], source: 'reference' }));

export default function Watchlist() {
  const [watchlist, setWatchlist] = useState<WatchlistItem[]>(initialItems);
  const [newSymbol, setNewSymbol] = useState('');
  const addAsset = () => { const symbol = newSymbol.trim().replace(/[^a-z0-9]/gi, '').toUpperCase(); if (!symbol) { toast.error('Enter a market symbol to add.'); return; } if (watchlist.some((item) => item.symbol === symbol)) { toast.info(`${symbol} is already in this watchlist.`); return; } const reference = snapshots[symbol]; setWatchlist((items) => [...items, reference ? { id: `asset-${symbol}`, ...reference, source: 'reference' } : { id: `asset-${symbol}`, symbol, name: `${symbol} local asset`, price: null, change24h: null, source: 'local' }]); setNewSymbol(''); toast.success(reference ? `${symbol} added with an illustrative reference snapshot.` : `${symbol} added as an unpriced local preview.`); };
  return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-border bg-background/70 backdrop-blur-xl"><div className="container py-5 sm:py-7"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-foreground-muted">Research workspace</p><h1 className="mt-1 flex items-center gap-2 text-2xl font-semibold tracking-tight sm:text-3xl"><Heart className="size-6 text-primary" aria-hidden="true" />Watchlist</h1><p className="mt-1 text-sm text-foreground-secondary">Organize the markets you want to revisit in this local terminal session.</p></div></header>
    <div className="container max-w-6xl py-5 sm:py-7 lg:py-8"><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><section className="rounded-2xl border border-border bg-card/75 p-4 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl sm:p-5"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-muted">Add local asset</p><h2 className="mt-1 text-lg font-semibold">Track a market</h2><form onSubmit={(event) => { event.preventDefault(); addAsset(); }} className="mt-4 flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="asset-symbol">Market symbol</label><input id="asset-symbol" value={newSymbol} onChange={(event) => setNewSymbol(event.target.value)} placeholder="e.g. BTC, ETH, or SOL" className="input flex-1" /><button type="submit" className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground transition-transform active:scale-[0.98] focus-visible:outline-none"><Plus className="size-4" aria-hidden="true" />Add asset</button></form></section><aside className="rounded-2xl border border-border bg-card/75 p-4 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl"><div className="flex items-start gap-3"><LineChart className="mt-0.5 size-5 text-primary" aria-hidden="true" /><div><p className="text-sm font-semibold">Local research only</p><p className="mt-1 text-xs leading-5 text-foreground-secondary">Reference prices are illustrative static snapshots. Custom symbols are intentionally unpriced until a market-data connection is configured.</p></div></div></aside></div>
      <section className="mt-5 overflow-hidden rounded-2xl border border-border bg-card/75 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl"><header className="flex items-center justify-between border-b border-border p-4 sm:p-5"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-muted">Current session</p><h2 className="mt-1 text-lg font-semibold">Tracked markets</h2></div><span className="text-xs text-foreground-muted">{watchlist.length} {watchlist.length === 1 ? 'asset' : 'assets'}</span></header>{watchlist.length ? <div className="grid gap-3 p-4 sm:grid-cols-2 sm:p-5 lg:grid-cols-3">{watchlist.map((item) => <article key={item.id} className="rounded-xl border border-border bg-card/95 p-4 transition-colors hover:bg-background-secondary/55 sm:p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-mono text-lg font-semibold">{item.symbol}/USDT</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.1em] ${item.source === 'reference' ? 'bg-primary/10 text-primary' : 'bg-background-secondary text-foreground-muted'}`}>{item.source === 'reference' ? 'Reference' : 'Local'}</span></div><p className="mt-1 truncate text-sm text-foreground-secondary">{item.name}</p></div><button type="button" onClick={() => { setWatchlist((items) => items.filter((entry) => entry.id !== item.id)); toast.success(`${item.symbol} removed from watchlist.`); }} className="rounded-lg border border-danger/25 bg-danger/8 p-2 text-danger transition-colors hover:bg-danger/15 focus-visible:outline-none" aria-label={`Remove ${item.symbol} from watchlist`}><Trash2 className="size-4" aria-hidden="true" /></button></div><div className="mt-6 border-t border-border pt-4">{item.price !== null && item.change24h !== null ? <><p className="font-mono text-xl font-semibold sm:text-2xl">${item.price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p><p className={`mt-2 text-sm font-semibold ${item.change24h >= 0 ? 'text-success' : 'text-danger'}`}>{item.change24h >= 0 ? '+' : ''}{item.change24h.toFixed(2)}% <span className="font-normal text-foreground-muted">illustrative 24h</span></p></> : <><p className="text-lg font-semibold text-foreground-secondary">Price unavailable</p><p className="mt-2 text-sm text-foreground-muted">Connect market data to populate this local asset.</p></>}</div></article>)}</div> : <div className="flex min-h-64 flex-col items-center justify-center px-5 text-center"><Heart className="size-8 text-foreground-muted" aria-hidden="true" /><h3 className="mt-4 text-base font-semibold">Your watchlist is empty</h3><p className="mt-1 max-w-md text-sm leading-6 text-foreground-secondary">Add a market above to create a local research shortcut.</p></div>}</section></div></main>;
}
