import { ArrowUpRight, Heart, LineChart, Plus, Star, Trash2, TrendingDown, TrendingUp } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { Link } from 'wouter';
import { trpc } from '@/lib/trpc';
import { useAuth } from '@/_core/hooks/useAuth';

type WatchlistItem = { id: string; symbol: string; name: string; price: number; change24h: number; volume: string; marketCap: string; isFavorite: boolean; };
const initialItems: WatchlistItem[] = [
  { id: 'btc', symbol: 'BTC', name: 'Bitcoin', price: 45230.50, change24h: 2.45, volume: '$28.50B', marketCap: '$890B', isFavorite: true },
  { id: 'eth', symbol: 'ETH', name: 'Ethereum', price: 2450.75, change24h: 1.85, volume: '$15.20B', marketCap: '$294B', isFavorite: true },
  { id: 'sol', symbol: 'SOL', name: 'Solana', price: 98.45, change24h: -1.23, volume: '$2.10B', marketCap: '$42B', isFavorite: false },
  { id: 'xrp', symbol: 'XRP', name: 'XRP', price: 2.15, change24h: 3.12, volume: '$1.80B', marketCap: '$115B', isFavorite: false },
];

export default function WatchlistPremium() {
  const auth = useAuth();
  const realWatchlist = trpc.commodityMarket.watchlist.useQuery(undefined, { enabled: auth.isAuthenticated, staleTime: 30_000 });
  const [watchlist, setWatchlist] = useState(initialItems);
  const favorites = watchlist.filter((item) => item.isFavorite);
  const others = watchlist.filter((item) => !item.isFavorite);
  const toggleFavorite = (id: string) => setWatchlist((items) => items.map((item) => item.id === id ? { ...item, isFavorite: !item.isFavorite } : item));
  const remove = (item: WatchlistItem) => { setWatchlist((items) => items.filter((entry) => entry.id !== item.id)); toast.success(`${item.symbol} removed from the local premium watchlist.`); };
  return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-border bg-background/70 backdrop-blur-xl"><div className="container flex flex-col gap-4 py-5 sm:flex-row sm:items-end sm:justify-between sm:py-7"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-foreground-muted">Premium research view</p><h1 className="mt-1 flex items-center gap-2 text-2xl font-semibold tracking-tight sm:text-3xl"><Star className="size-6 text-primary" aria-hidden="true" />Watchlist premium</h1><p className="mt-1 max-w-2xl text-sm text-foreground-secondary">A high-context view of the local markets you are following.</p></div><Link href="/watchlist" className="inline-flex w-fit items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground transition-transform active:scale-[0.98] focus-visible:outline-none"><Plus className="size-4" aria-hidden="true" />Manage assets<ArrowUpRight className="size-4" aria-hidden="true" /></Link></div></header>
    <div className="container max-w-6xl py-5 sm:py-7 lg:py-8"><div className="grid gap-4 rounded-2xl border border-border bg-card/75 p-4 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl sm:grid-cols-[auto_minmax(0,1fr)] sm:p-5"><span className="inline-flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><LineChart className="size-5" aria-hidden="true" /></span><div><p className="text-sm font-semibold">Illustrative research snapshot</p><p className="mt-1 text-sm leading-6 text-foreground-secondary">Prices, 24-hour movement, volume, and capitalization are deterministic display values for this preview. They are not live quotes or trading guidance.</p></div></div><div className="mt-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-muted">Current session</p><h2 className="mt-1 text-xl font-semibold">Tracked markets</h2></div><span className="rounded-full border border-border bg-background-secondary px-3 py-1.5 text-xs font-semibold text-foreground-secondary">{watchlist.length} {watchlist.length === 1 ? 'asset' : 'assets'} tracked</span></div>
      <div className="mt-5 space-y-6"><LiveGoldWatchlist enabled={Boolean(realWatchlist.data?.some((entry) => entry.assetId === 'xau-usd'))} />{favorites.length > 0 && <WatchlistSection title="Favorites" icon={<Star className="size-4 text-primary" aria-hidden="true" />} items={favorites} onToggle={toggleFavorite} onRemove={remove} />}{others.length > 0 && <WatchlistSection title="Other markets" icon={<Heart className="size-4 text-foreground-muted" aria-hidden="true" />} items={others} onToggle={toggleFavorite} onRemove={remove} />}{!watchlist.length && <section className="flex min-h-72 flex-col items-center justify-center rounded-2xl border border-border bg-card/75 px-5 text-center shadow-[0_20px_64px_rgba(3,7,34,0.16)]"><Heart className="size-9 text-foreground-muted" aria-hidden="true" /><h2 className="mt-4 text-lg font-semibold">No tracked markets</h2><p className="mt-1 max-w-md text-sm leading-6 text-foreground-secondary">Add a local asset from the research watchlist to continue.</p><Link href="/watchlist" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Manage assets<ArrowUpRight className="size-4" aria-hidden="true" /></Link></section>}</div></div></main>;
}

function LiveGoldWatchlist({ enabled }: { enabled: boolean }) {
  const quote = trpc.commodityMarket.quote.useQuery({ assetId: 'xau-usd' }, { enabled, staleTime: 60_000, retry: 1 });
  const remove = trpc.commodityMarket.removeGoldFromWatchlist.useMutation();
  if (!enabled) return null;
  const data = quote.data?.success ? quote.data.data : null;
  const error = quote.data?.success === false ? quote.data.error.message : null;
  return <section className="overflow-hidden rounded-2xl border border-warning/25 bg-card/75 shadow-[0_20px_64px_rgba(3,7,34,0.16)]"><header className="flex items-center gap-2 border-b border-border p-4 sm:p-5"><span className="inline-flex size-8 items-center justify-center rounded-lg bg-warning/10 font-bold text-warning">Au</span><div><h2 className="text-base font-semibold">Gold · XAU/USD</h2><p className="text-xs text-foreground-muted">Saved commodity monitoring preference · Twelve Data</p></div><button type="button" onClick={() => remove.mutate()} disabled={remove.isPending} className="ml-auto rounded-lg border border-danger/25 bg-danger/8 p-2 text-danger hover:bg-danger/15 disabled:opacity-50 focus-visible:outline-none" aria-label="Remove Gold from watchlist"><Trash2 className="size-4" /></button></header><div className="grid gap-3 p-4 sm:grid-cols-4 sm:p-5"><Metric label="Current price" value={data ? formatPrice(data.currentPrice) : error ?? 'DATA UNAVAILABLE'} /><Metric label="24h movement" value={data?.change24hPercent === null || data?.change24hPercent === undefined ? 'DATA UNAVAILABLE' : <Change value={data.change24hPercent} />} /><Metric label="Market status" value={data?.marketStatus ?? 'DATA UNAVAILABLE'} /><Metric label="Ownership" value="Monitoring only" /></div><div className="border-t border-border px-4 py-3 text-xs text-foreground-muted">No broker, RWA, vault, or portfolio holding is inferred from this watchlist entry.</div></section>;
}

function WatchlistSection({ title, icon, items, onToggle, onRemove }: { title: string; icon: React.ReactNode; items: WatchlistItem[]; onToggle: (id: string) => void; onRemove: (item: WatchlistItem) => void; }) { return <section className="overflow-hidden rounded-2xl border border-border bg-card/75 shadow-[0_20px_64px_rgba(3,7,34,0.16)] backdrop-blur-xl"><header className="flex items-center gap-2 border-b border-border p-4 sm:p-5">{icon}<h2 className="text-base font-semibold">{title}</h2><span className="ml-auto text-xs text-foreground-muted">{items.length}</span></header><div className="hidden grid-cols-[minmax(0,1.5fr)_minmax(100px,0.8fr)_minmax(110px,0.85fr)_minmax(88px,0.65fr)_minmax(88px,0.65fr)_auto] gap-3 border-b border-border px-4 py-3 text-[10px] font-semibold uppercase tracking-[0.11em] text-foreground-muted lg:grid"><span>Asset</span><span className="text-right">Reference price</span><span className="text-right">24h movement</span><span className="text-right">Volume</span><span className="text-right">Market cap</span><span>Actions</span></div><div className="divide-y divide-border">{items.map((item) => <article key={item.id} className="p-4 transition-colors hover:bg-background-secondary/45 sm:p-5"><div className="hidden grid-cols-[minmax(0,1.5fr)_minmax(100px,0.8fr)_minmax(110px,0.85fr)_minmax(88px,0.65fr)_minmax(88px,0.65fr)_auto] items-center gap-3 lg:grid"><AssetName item={item} /><p className="text-right font-mono text-sm font-semibold">{formatPrice(item.price)}</p><Change value={item.change24h} className="justify-end" /><p className="text-right font-mono text-sm text-foreground-secondary">{item.volume}</p><p className="text-right font-mono text-sm text-foreground-secondary">{item.marketCap}</p><Actions item={item} onToggle={onToggle} onRemove={onRemove} /></div><div className="lg:hidden"><div className="flex items-start justify-between gap-3"><AssetName item={item} /><Actions item={item} onToggle={onToggle} onRemove={onRemove} /></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-border pt-4"><Metric label="Reference price" value={formatPrice(item.price)} /><Metric label="24h movement" value={<Change value={item.change24h} />} /><Metric label="Volume" value={item.volume} /><Metric label="Market cap" value={item.marketCap} /></div></div></article>)}</div></section>; }
function AssetName({ item }: { item: WatchlistItem }) { return <div className="min-w-0"><p className="font-mono text-sm font-semibold">{item.symbol}/USDT</p><p className="mt-1 truncate text-sm text-foreground-secondary">{item.name}</p></div>; }
function Change({ value, className = '' }: { value: number; className?: string }) { const positive = value >= 0; return <span className={`flex items-center gap-1 text-sm font-semibold ${positive ? 'text-success' : 'text-danger'} ${className}`}>{positive ? <TrendingUp className="size-4" aria-hidden="true" /> : <TrendingDown className="size-4" aria-hidden="true" />}{positive ? '+' : ''}{value.toFixed(2)}%</span>; }
function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <div><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-foreground-muted">{label}</p><div className="mt-1 font-mono text-sm font-semibold text-foreground-secondary">{value}</div></div>; }
function Actions({ item, onToggle, onRemove }: { item: WatchlistItem; onToggle: (id: string) => void; onRemove: (item: WatchlistItem) => void; }) { return <div className="flex shrink-0 items-center gap-2"><button type="button" onClick={() => onToggle(item.id)} className={`rounded-lg border p-2 transition-colors focus-visible:outline-none ${item.isFavorite ? 'border-primary/35 bg-primary/10 text-primary hover:bg-primary/15' : 'border-border bg-background-secondary text-foreground-muted hover:text-primary'}`} aria-label={item.isFavorite ? `Remove ${item.symbol} from favorites` : `Add ${item.symbol} to favorites`} aria-pressed={item.isFavorite}><Star className="size-4" fill={item.isFavorite ? 'currentColor' : 'none'} aria-hidden="true" /></button><button type="button" onClick={() => onRemove(item)} className="rounded-lg border border-danger/25 bg-danger/8 p-2 text-danger transition-colors hover:bg-danger/15 focus-visible:outline-none" aria-label={`Remove ${item.symbol} from the watchlist`}><Trash2 className="size-4" aria-hidden="true" /></button></div>; }
function formatPrice(value: number) { return `$${value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
