import { createHash } from "node:crypto";
import { and, desc, eq, lt } from "drizzle-orm";
import { backtestDatasetCandles, backtestDatasetImports, backtestDatasets, csvSourceAuthentications, csvTrustedPublisherKeys, paperStrategies, paperStrategyRevisions, strategyBacktestEquityPoints, strategyBacktestRuns, strategyBacktestTrades, strategyLabAuditEvents, userFeatureEntitlements } from "../../drizzle/schema";
import { getDb } from "../db";
import { DEFAULT_RISK_SETTINGS, normalizeRiskSettings } from "../risk/settings";
import { getHistoricalCandles, type ExchangeInterval } from "./marketData";
import { fingerprintHistoricalCandles, runDeterministicBacktest, validateHistoricalCandles } from "../strategy/backtest";
import { validateRuleConfig } from "../strategy/rules";
import { validateHistoricalOhlcvCsv } from "../strategy/csvImport";
import { pageDescendingSequences } from "../strategy/pagination";
import { fingerprintCsvAuthenticationPublicKey, verifyCsvAuthentication } from "../strategy/csvAuth";
import type { BacktestResult, HistoricalCandle, StrategyInterval, StrategyRiskConfig, StrategyRuleConfig } from "../strategy/types";
import { StrategyValidationError } from "../strategy/types";

const ENGINE_VERSION = "2.2.0";
const FEATURE_KEY = "strategy_lab";
const MAX_STRATEGIES = 100;

export class StrategyLabError extends Error {
  constructor(public readonly code: "INVALID" | "NOT_FOUND" | "UNAVAILABLE" | "FORBIDDEN", message: string) { super(message); this.name = "StrategyLabError"; }
}
export interface StrategyDefinitionInput { name: string; description?: string | null; symbol: string; interval: StrategyInterval; status?: "DRAFT" | "ACTIVE"; rules: StrategyRuleConfig; risk: StrategyRiskConfig; }
export interface HistoricalDatasetInput { symbol: string; interval: StrategyInterval; startTime: number; endTime: number; }
export interface CsvDatasetImportInput { fileName: string; sourceLabel: string; symbol: string; interval: StrategyInterval; csvText: string; manifestJson?: string | null; }
export interface TrustedPublisherKeyInput { displayName: string; publicKeySpkiBase64: string; expiresAt?: number | null; }

function finite(value: number, label: string): void { if (!Number.isFinite(value)) throw new StrategyLabError("INVALID", `${label} must be finite.`); }
function date(value: number): Date { finite(value, "UTC timestamp"); return new Date(value); }
function numberValue(value: unknown): number { const parsed = typeof value === "number" ? value : Number(value); return Number.isFinite(parsed) ? parsed : 0; }
function toJson(value: unknown): string { return JSON.stringify(value); }
function hash(value: unknown): string { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function idFrom(result: unknown): number { const row = Array.isArray(result) ? result[0] : result; const id = row && typeof row === "object" && "insertId" in row ? Number((row as { insertId?: unknown }).insertId) : Number.NaN; if (!Number.isInteger(id) || id <= 0) throw new StrategyLabError("UNAVAILABLE", "The database did not return a persistent record identifier."); return id; }
function serializeRisk(risk: StrategyRiskConfig): StrategyRiskConfig { const settings = normalizeRiskSettings(risk); if (!Number.isFinite(risk.initialEquityUsd) || risk.initialEquityUsd < 1_000 || risk.initialEquityUsd > 100_000_000) throw new StrategyValidationError("Initial virtual equity must be between 1,000 and 100,000,000 USD."); return { ...settings, initialEquityUsd: risk.initialEquityUsd }; }
function normalizeDefinition(input: StrategyDefinitionInput): StrategyDefinitionInput { const name = input.name.trim(); const symbol = input.symbol.trim().toUpperCase(); if (!name || name.length > 100) throw new StrategyValidationError("Strategy name is required and must be at most 100 characters."); if (!/^[A-Z0-9]{2,15}$/.test(symbol)) throw new StrategyValidationError("Strategy symbol must contain 2 to 15 uppercase letters or numbers."); return { name, description: input.description?.trim().slice(0, 2000) || null, symbol, interval: input.interval, status: input.status ?? "DRAFT", rules: validateRuleConfig(input.rules), risk: serializeRisk(input.risk) }; }
function candleToHistorical(row: typeof backtestDatasetCandles.$inferSelect): HistoricalCandle { return { openTime: row.openTime.getTime(), closeTime: row.closeTime.getTime(), open: numberValue(row.open), high: numberValue(row.high), low: numberValue(row.low), close: numberValue(row.close), volume: numberValue(row.volume), quoteVolumeUsd: numberValue(row.quoteVolumeUsd), tradeCount: row.tradeCount }; }
function strategySummary(row: typeof paperStrategies.$inferSelect) { return { id: row.id, name: row.name, description: row.description, symbol: row.symbol, interval: row.interval as StrategyInterval, status: row.status, currentRevisionNumber: row.currentRevisionNumber, requiredEntitlement: row.requiredEntitlement, createdAt: row.createdAt, updatedAt: row.updatedAt }; }
async function dbOrThrow() { const db = await getDb(); if (!db) throw new StrategyLabError("UNAVAILABLE", "Strategy Lab storage is temporarily unavailable."); return db; }
async function audit(userId: number, eventKey: string, eventType: typeof strategyLabAuditEvents.$inferInsert["eventType"], details: unknown, ids: { strategyId?: number; strategyRevisionId?: number; datasetId?: number; runId?: number } = {}) { const db = await dbOrThrow(); try { await db.insert(strategyLabAuditEvents).values({ userId, eventKey, eventType, detailsJson: toJson(details), ...ids }); } catch { /* idempotent audit key */ } }

/** Entitlement seam only: no billing or checkout exists. Missing records receive the product's current default access. */
export async function getStrategyLabEntitlement(userId: number) { const db = await dbOrThrow(); const row = (await db.select().from(userFeatureEntitlements).where(and(eq(userFeatureEntitlements.userId, userId), eq(userFeatureEntitlements.featureKey, FEATURE_KEY))).limit(1))[0]; return { featureKey: FEATURE_KEY, enabled: row ? row.enabled === 1 : true, tier: row?.tier ?? "FREE", source: row ? "stored" as const : "default" as const }; }
async function requireEntitlement(userId: number) { const entitlement = await getStrategyLabEntitlement(userId); if (!entitlement.enabled) throw new StrategyLabError("FORBIDDEN", "Strategy Lab is not enabled for this account."); return entitlement; }

export function defaultStrategyRiskConfig(): StrategyRiskConfig { return { ...DEFAULT_RISK_SETTINGS, initialEquityUsd: 100_000 }; }

export async function listPaperStrategies(userId: number) { await requireEntitlement(userId); const db = await dbOrThrow(); return (await db.select().from(paperStrategies).where(eq(paperStrategies.userId, userId)).orderBy(desc(paperStrategies.updatedAt)).limit(MAX_STRATEGIES)).map(strategySummary); }
export async function getPaperStrategy(userId: number, strategyId: number) { await requireEntitlement(userId); const db = await dbOrThrow(); const strategy = (await db.select().from(paperStrategies).where(and(eq(paperStrategies.userId, userId), eq(paperStrategies.id, strategyId))).limit(1))[0]; if (!strategy) throw new StrategyLabError("NOT_FOUND", "Strategy not found."); const revision = (await db.select().from(paperStrategyRevisions).where(and(eq(paperStrategyRevisions.userId, userId), eq(paperStrategyRevisions.strategyId, strategy.id), eq(paperStrategyRevisions.revisionNumber, strategy.currentRevisionNumber))).limit(1))[0]; if (!revision) throw new StrategyLabError("UNAVAILABLE", "The current strategy revision is unavailable."); return { ...strategySummary(strategy), revision: { id: revision.id, number: revision.revisionNumber, rules: JSON.parse(revision.ruleConfigJson) as StrategyRuleConfig, risk: JSON.parse(revision.riskConfigJson) as StrategyRiskConfig, fingerprint: revision.contentFingerprint, createdAt: revision.createdAt } }; }

async function createRevision(userId: number, strategyId: number, revisionNumber: number, rules: StrategyRuleConfig, risk: StrategyRiskConfig): Promise<number> { const db = await dbOrThrow(); const contentFingerprint = hash({ rules, risk, revisionNumber }); return idFrom(await db.insert(paperStrategyRevisions).values({ strategyId, userId, revisionNumber, ruleConfigJson: toJson(rules), riskConfigJson: toJson(risk), contentFingerprint })); }
export async function createPaperStrategy(userId: number, raw: StrategyDefinitionInput) { await requireEntitlement(userId); const input = normalizeDefinition(raw); const db = await dbOrThrow(); const strategyId = idFrom(await db.insert(paperStrategies).values({ userId, name: input.name, description: input.description, symbol: input.symbol, interval: input.interval, status: input.status, currentRevisionNumber: 1, requiredEntitlement: FEATURE_KEY })); const revisionId = await createRevision(userId, strategyId, 1, input.rules, input.risk); await audit(userId, `strategy-created:${strategyId}`, "STRATEGY_CREATED", { strategyId, revisionId, input }, { strategyId, strategyRevisionId: revisionId }); return getPaperStrategy(userId, strategyId); }
export async function revisePaperStrategy(userId: number, strategyId: number, raw: StrategyDefinitionInput) { await requireEntitlement(userId); const existing = await getPaperStrategy(userId, strategyId); if (existing.status === "ARCHIVED") throw new StrategyLabError("INVALID", "Archived strategies cannot be revised."); const input = normalizeDefinition(raw); const db = await dbOrThrow(); const nextNumber = existing.currentRevisionNumber + 1; await db.update(paperStrategies).set({ name: input.name, description: input.description, symbol: input.symbol, interval: input.interval, status: input.status, currentRevisionNumber: nextNumber }).where(and(eq(paperStrategies.userId, userId), eq(paperStrategies.id, strategyId))); const revisionId = await createRevision(userId, strategyId, nextNumber, input.rules, input.risk); await audit(userId, `strategy-revised:${strategyId}:${nextNumber}`, "STRATEGY_REVISED", { strategyId, revisionId, input }, { strategyId, strategyRevisionId: revisionId }); return getPaperStrategy(userId, strategyId); }
export async function duplicatePaperStrategy(userId: number, strategyId: number, name: string) { const existing = await getPaperStrategy(userId, strategyId); return createPaperStrategy(userId, { name, description: existing.description, symbol: existing.symbol, interval: existing.interval, status: "DRAFT", rules: existing.revision.rules, risk: existing.revision.risk }); }
export async function archivePaperStrategy(userId: number, strategyId: number) { await requireEntitlement(userId); const db = await dbOrThrow(); const result = await db.update(paperStrategies).set({ status: "ARCHIVED" }).where(and(eq(paperStrategies.userId, userId), eq(paperStrategies.id, strategyId))); if (Number((result as { rowsAffected?: unknown }).rowsAffected) === 0) throw new StrategyLabError("NOT_FOUND", "Strategy not found."); await audit(userId, `strategy-archived:${strategyId}`, "STRATEGY_ARCHIVED", { strategyId }, { strategyId }); return { archived: true as const }; }

export async function captureHistoricalDataset(userId: number, input: HistoricalDatasetInput) {
  await requireEntitlement(userId); const symbol = input.symbol.trim().toUpperCase(); const interval = input.interval; finite(input.startTime, "Dataset start"); finite(input.endTime, "Dataset end"); const intervalMs: Record<StrategyInterval, number> = { "5m": 300_000, "15m": 900_000, "1h": 3_600_000, "4h": 14_400_000, "1d": 86_400_000 }; const requested = Math.floor((input.endTime - input.startTime) / intervalMs[interval]); if (requested < 60 || requested > 300) throw new StrategyLabError("INVALID", "Historical range must contain from 60 to 300 complete candles."); const response = await getHistoricalCandles({ symbol, interval: interval as ExchangeInterval, startTime: input.startTime, endTime: input.endTime, limit: requested }); const candles = response.candles.map((candle) => ({ openTime: candle.openTime, closeTime: candle.closeTime, open: candle.open, high: candle.high, low: candle.low, close: candle.close, volume: candle.volume, quoteVolumeUsd: candle.quoteVolumeUsd, tradeCount: candle.tradeCount })); validateHistoricalCandles(candles, interval, 60); const fingerprint = fingerprintHistoricalCandles({ symbol, interval, source: response.source, candles }); const db = await dbOrThrow(); const existing = (await db.select().from(backtestDatasets).where(and(eq(backtestDatasets.userId, userId), eq(backtestDatasets.candleFingerprint, fingerprint))).limit(1))[0]; if (existing) return { id: existing.id, fingerprint, reused: true as const, source: existing.provider, candleCount: existing.candleCount, rangeStart: existing.rangeStart, rangeEnd: existing.rangeEnd };
  const datasetId = idFrom(await db.insert(backtestDatasets).values({ userId, symbol, interval, provider: response.source, rangeStart: date(input.startTime), rangeEnd: date(input.endTime), candleCount: candles.length, candleFingerprint: fingerprint, schemaVersion: 1, fetchedAt: new Date() })); await db.insert(backtestDatasetCandles).values(candles.map((candle, sequence) => ({ datasetId, sequence: sequence + 1, openTime: date(candle.openTime), closeTime: date(candle.closeTime), open: candle.open.toFixed(8), high: candle.high.toFixed(8), low: candle.low.toFixed(8), close: candle.close.toFixed(8), volume: candle.volume.toFixed(12), quoteVolumeUsd: candle.quoteVolumeUsd.toFixed(8), tradeCount: Math.floor(candle.tradeCount) }))); await audit(userId, `dataset-captured:${datasetId}`, "DATASET_CAPTURED", { fingerprint, source: response.source, candleCount: candles.length, rangeStart: input.startTime, rangeEnd: input.endTime }, { datasetId }); return { id: datasetId, fingerprint, reused: false as const, source: response.source, candleCount: candles.length, rangeStart: date(input.startTime), rangeEnd: date(input.endTime) };
}

export async function registerTrustedCsvPublisherKey(userId: number, input: TrustedPublisherKeyInput) {
  await requireEntitlement(userId); const displayName = input.displayName.trim().slice(0, 120); if (!displayName) throw new StrategyLabError("INVALID", "Trusted publisher display name is required."); const expiresAt = input.expiresAt ?? null; if (expiresAt !== null && (!Number.isSafeInteger(expiresAt) || expiresAt <= Date.now())) throw new StrategyLabError("INVALID", "Trusted publisher key expiry must be a future UTC timestamp."); let keyFingerprint: string; try { keyFingerprint = fingerprintCsvAuthenticationPublicKey(input.publicKeySpkiBase64); } catch (error) { throw new StrategyLabError("INVALID", error instanceof Error ? error.message : "Invalid Ed25519 public key."); } const db = await dbOrThrow(); const existing = (await db.select().from(csvTrustedPublisherKeys).where(and(eq(csvTrustedPublisherKeys.userId, userId), eq(csvTrustedPublisherKeys.keyFingerprint, keyFingerprint))).limit(1))[0]; if (existing) return { id: existing.id, displayName: existing.displayName, keyFingerprint: existing.keyFingerprint, status: existing.status, expiresAt: existing.expiresAt, reused: true as const }; const id = idFrom(await db.insert(csvTrustedPublisherKeys).values({ userId, displayName, publicKeySpkiBase64: input.publicKeySpkiBase64.trim(), keyFingerprint, status: "ACTIVE", expiresAt: expiresAt === null ? null : date(expiresAt), revokedAt: null })); await audit(userId, `csv-publisher-key-registered:${keyFingerprint}`, "DATASET_CAPTURED", { keyId: id, keyFingerprint, displayName, trustScope: "USER_TRUSTED_KEY" }); return { id, displayName, keyFingerprint, status: "ACTIVE" as const, expiresAt: expiresAt === null ? null : date(expiresAt), reused: false as const };
}
export async function listTrustedCsvPublisherKeys(userId: number) { await requireEntitlement(userId); const db = await dbOrThrow(); return (await db.select().from(csvTrustedPublisherKeys).where(eq(csvTrustedPublisherKeys.userId, userId)).orderBy(desc(csvTrustedPublisherKeys.createdAt))).map((key) => ({ id: key.id, displayName: key.displayName, keyFingerprint: key.keyFingerprint, status: key.status, expiresAt: key.expiresAt, revokedAt: key.revokedAt, createdAt: key.createdAt, trustScope: "USER_TRUSTED_KEY" as const })); }
export async function revokeTrustedCsvPublisherKey(userId: number, keyId: number) { await requireEntitlement(userId); const db = await dbOrThrow(); const result = await db.update(csvTrustedPublisherKeys).set({ status: "REVOKED", revokedAt: new Date() }).where(and(eq(csvTrustedPublisherKeys.userId, userId), eq(csvTrustedPublisherKeys.id, keyId), eq(csvTrustedPublisherKeys.status, "ACTIVE"))); if (Number((result as { rowsAffected?: unknown }).rowsAffected) === 0) throw new StrategyLabError("NOT_FOUND", "Active trusted publisher key was not found."); await audit(userId, `csv-publisher-key-revoked:${keyId}`, "DATASET_CAPTURED", { keyId, action: "REVOKED" }); return { revoked: true as const };
}
export async function previewCsvSourceAuthentication(userId: number, input: { csvText: string; symbol: string; interval: StrategyInterval; manifestJson?: string | null }) { await requireEntitlement(userId); const symbol = input.symbol.trim().toUpperCase(); if (!/^[A-Z0-9]{2,15}$/.test(symbol)) throw new StrategyLabError("INVALID", "CSV symbol must contain 2 to 15 uppercase letters or numbers."); const db = await dbOrThrow(); const trustedKeys = (await db.select().from(csvTrustedPublisherKeys).where(eq(csvTrustedPublisherKeys.userId, userId))).map((key) => ({ id: key.id, keyFingerprint: key.keyFingerprint, publicKeySpkiBase64: key.publicKeySpkiBase64, status: key.status, expiresAt: key.expiresAt?.getTime() ?? null })); return verifyCsvAuthentication({ csvText: input.csvText, manifestJson: input.manifestJson, symbol, interval: input.interval, trustedKeys }); }
async function recordCsvAuthentication(userId: number, importId: number, datasetId: number | null, result: ReturnType<typeof verifyCsvAuthentication>, manifestJson: string | null | undefined) { const db = await dbOrThrow(); const base = { userId, importId, datasetId, observedCsvFingerprint: result.observedCsvFingerprint, manifestJson: manifestJson?.trim() || null, authenticationStatus: result.status, requiredKeyFingerprint: result.status === "UNSIGNED" ? null : result.manifest?.keyFingerprint ?? null, declaredCsvFingerprint: result.status === "UNSIGNED" ? null : result.manifest?.csvSha256 ?? null, publisherKeyId: result.status === "VERIFIED" ? result.publisherKeyId : null, failureCode: result.status === "REJECTED" ? result.failureCode : null, verifiedAt: result.status === "VERIFIED" ? new Date() : null }; await db.insert(csvSourceAuthentications).values(base); }

export async function importHistoricalOhlcvCsv(userId: number, input: CsvDatasetImportInput) {
  await requireEntitlement(userId);
  const fileName = input.fileName.trim().slice(0, 255); const sourceLabel = input.sourceLabel.trim().slice(0, 120); const symbol = input.symbol.trim().toUpperCase();
  if (!fileName.toLowerCase().endsWith(".csv")) throw new StrategyLabError("INVALID", "Only .csv files are accepted for historical import.");
  if (!sourceLabel) throw new StrategyLabError("INVALID", "A source label is required; labels alone are never treated as source proof.");
  if (!/^[A-Z0-9]{2,15}$/.test(symbol)) throw new StrategyLabError("INVALID", "CSV symbol must contain 2 to 15 uppercase letters or numbers.");
  const validation = validateHistoricalOhlcvCsv(input.csvText, input.interval); const db = await dbOrThrow();
  const trustedKeys = (await db.select().from(csvTrustedPublisherKeys).where(eq(csvTrustedPublisherKeys.userId, userId))).map((key) => ({ id: key.id, keyFingerprint: key.keyFingerprint, publicKeySpkiBase64: key.publicKeySpkiBase64, status: key.status, expiresAt: key.expiresAt?.getTime() ?? null }));
  const authentication = verifyCsvAuthentication({ csvText: input.csvText, manifestJson: input.manifestJson, symbol, interval: input.interval, trustedKeys });
  const prior = (await db.select().from(backtestDatasetImports).where(and(eq(backtestDatasetImports.userId, userId), eq(backtestDatasetImports.csvFingerprint, validation.rawFingerprint))).limit(1))[0];
  if (prior && !(prior.datasetId === null && validation.valid && validation.rangeStart !== null && validation.rangeEnd !== null && authentication.status === "VERIFIED")) { await recordCsvAuthentication(userId, prior.id, prior.datasetId, authentication, input.manifestJson); return { importId: prior.id, datasetId: prior.datasetId, validationStatus: prior.validationStatus, reused: true as const, sourceClassification: prior.sourceClassification, authentication, errors: JSON.parse(prior.validationErrorsJson) }; }
  const authenticationError = authentication.status === "REJECTED" ? [{ code: "SOURCE_AUTHENTICATION_FAILED", row: null, message: authentication.message }] : [];
  const common = { userId, fileName, sourceLabel, sourceClassification: "USER_IMPORTED_UNVERIFIED" as const, csvFingerprint: validation.rawFingerprint, validationErrorsJson: toJson([...validation.errors, ...authenticationError]), rowCount: validation.rowCount };
  if (!validation.valid || validation.rangeStart === null || validation.rangeEnd === null) {
    const importId = idFrom(await db.insert(backtestDatasetImports).values({ ...common, datasetId: null, validationStatus: "REJECTED", verifiedAt: null }));
    await recordCsvAuthentication(userId, importId, null, authentication, input.manifestJson); await audit(userId, `csv-import-rejected:${validation.rawFingerprint}`, "DATASET_CAPTURED", { importId, validationStatus: "REJECTED", sourceLabel, errors: validation.errors, authentication });
    return { importId, datasetId: null, validationStatus: "REJECTED" as const, reused: false as const, sourceClassification: "USER_IMPORTED_UNVERIFIED" as const, authentication, errors: validation.errors };
  }
  if (authentication.status === "REJECTED") { const importId = idFrom(await db.insert(backtestDatasetImports).values({ ...common, datasetId: null, validationStatus: "REJECTED", verifiedAt: null })); await recordCsvAuthentication(userId, importId, null, authentication, input.manifestJson); await audit(userId, `csv-import-auth-rejected:${validation.rawFingerprint}`, "DATASET_CAPTURED", { importId, validationStatus: "REJECTED", sourceLabel, authentication }); return { importId, datasetId: null, validationStatus: "REJECTED" as const, reused: false as const, sourceClassification: "USER_IMPORTED_UNVERIFIED" as const, authentication, errors: authenticationError }; }
  const provider = authentication.status === "VERIFIED" ? "user_imported_authenticated" : "user_imported_unverified";
  const sourceClassification = authentication.status === "VERIFIED" ? "USER_TRUSTED_KEY_AUTHENTICATED" as const : "USER_IMPORTED_UNVERIFIED" as const;
  const fingerprint = fingerprintHistoricalCandles({ symbol, interval: input.interval, source: provider, candles: validation.candles });
  const existingDataset = (await db.select().from(backtestDatasets).where(and(eq(backtestDatasets.userId, userId), eq(backtestDatasets.candleFingerprint, fingerprint))).limit(1))[0];
  const datasetId = existingDataset?.id ?? idFrom(await db.insert(backtestDatasets).values({ userId, symbol, interval: input.interval, provider, rangeStart: date(validation.rangeStart), rangeEnd: date(validation.rangeEnd + 1), candleCount: validation.candles.length, candleFingerprint: fingerprint, schemaVersion: 1, fetchedAt: new Date() }));
  if (!existingDataset) await db.insert(backtestDatasetCandles).values(validation.candles.map((candle, sequence) => ({ datasetId, sequence: sequence + 1, openTime: date(candle.openTime), closeTime: date(candle.closeTime), open: candle.open.toFixed(8), high: candle.high.toFixed(8), low: candle.low.toFixed(8), close: candle.close.toFixed(8), volume: candle.volume.toFixed(12), quoteVolumeUsd: candle.quoteVolumeUsd.toFixed(8), tradeCount: 0 })));
  const importId = prior ? prior.id : idFrom(await db.insert(backtestDatasetImports).values({ ...common, datasetId, validationStatus: "VERIFIED", verifiedAt: new Date() }));
  if (prior) await db.update(backtestDatasetImports).set({ datasetId, validationStatus: "VERIFIED", validationErrorsJson: toJson([]), verifiedAt: new Date() }).where(and(eq(backtestDatasetImports.userId, userId), eq(backtestDatasetImports.id, prior.id)));
  await recordCsvAuthentication(userId, importId, datasetId, authentication, input.manifestJson); await audit(userId, `csv-import-verified:${validation.rawFingerprint}`, "DATASET_CAPTURED", { importId, datasetId, validationStatus: "VERIFIED", sourceLabel, sourceClassification, fingerprint, candleCount: validation.candles.length, authentication }, { datasetId });
  return { importId, datasetId, validationStatus: "VERIFIED" as const, reused: false as const, sourceClassification, authentication, datasetFingerprint: fingerprint, errors: [] };
}

export async function runPaperStrategyBacktest(userId: number, strategyId: number, datasetInput: HistoricalDatasetInput) {
  const strategy = await getPaperStrategy(userId, strategyId); const entitlement = await requireEntitlement(userId); const dataset = await captureHistoricalDataset(userId, { ...datasetInput, symbol: strategy.symbol, interval: strategy.interval }); const db = await dbOrThrow(); const rows = await db.select().from(backtestDatasetCandles).where(eq(backtestDatasetCandles.datasetId, dataset.id)).orderBy(backtestDatasetCandles.sequence); const candles = rows.map(candleToHistorical); const runFingerprint = hash({ strategyRevision: strategy.revision.fingerprint, dataset: dataset.fingerprint, engine: ENGINE_VERSION }); const existing = (await db.select().from(strategyBacktestRuns).where(and(eq(strategyBacktestRuns.userId, userId), eq(strategyBacktestRuns.runFingerprint, runFingerprint))).limit(1))[0]; if (existing) return getBacktestRun(userId, existing.id);
  const result = runDeterministicBacktest({ symbol: strategy.symbol, interval: strategy.interval, source: dataset.source as "binance" | "coinbase", datasetFingerprint: dataset.fingerprint, candles, rules: strategy.revision.rules, risk: strategy.revision.risk }); const runId = idFrom(await db.insert(strategyBacktestRuns).values({ userId, strategyId, strategyRevisionId: strategy.revision.id, datasetId: dataset.id, engineVersion: ENGINE_VERSION, entitlementKey: entitlement.featureKey, status: "COMPLETED", initialEquityUsd: result.metrics.initialEquityUsd.toFixed(2), feeBps: strategy.revision.risk.feeBps, slippageBps: strategy.revision.risk.slippageBps, runConfigJson: toJson({ symbol: strategy.symbol, interval: strategy.interval, strategyRevisionFingerprint: strategy.revision.fingerprint, datasetFingerprint: dataset.fingerprint }), resultJson: toJson(result.metrics), runFingerprint, startedAt: date(result.startedAt), completedAt: date(result.completedAt) }));
  if (result.trades.length) await db.insert(strategyBacktestTrades).values(result.trades.map((trade) => ({ runId, sequence: trade.sequence, decision: trade.decision, signalTime: date(trade.signalTime), entryTime: trade.entryTime === null ? null : date(trade.entryTime), exitTime: trade.exitTime === null ? null : date(trade.exitTime), entryPriceUsd: trade.entryPriceUsd === null ? null : trade.entryPriceUsd.toFixed(8), exitPriceUsd: trade.exitPriceUsd === null ? null : trade.exitPriceUsd.toFixed(8), quantity: trade.quantity.toFixed(12), stopPriceUsd: trade.stopPriceUsd === null ? null : trade.stopPriceUsd.toFixed(8), targetPriceUsd: trade.targetPriceUsd === null ? null : trade.targetPriceUsd.toFixed(8), plannedRiskUsd: trade.plannedRiskUsd === null ? null : trade.plannedRiskUsd.toFixed(2), plannedRiskPercent: trade.plannedRiskPercent === null ? null : trade.plannedRiskPercent.toFixed(4), grossPnlUsd: trade.grossPnlUsd === null ? null : trade.grossPnlUsd.toFixed(2), netPnlUsd: trade.netPnlUsd === null ? null : trade.netPnlUsd.toFixed(2), estimatedFeesUsd: trade.estimatedFeesUsd.toFixed(2), maxExposureUsd: trade.maxExposureUsd === null ? null : trade.maxExposureUsd.toFixed(2), exitReason: trade.exitReason, gateJson: toJson(trade.gate), evidenceJson: toJson(trade.evidence), rejectionReason: trade.rejectionReason }))); if (result.equityCurve.length) await db.insert(strategyBacktestEquityPoints).values(result.equityCurve.map((point) => ({ runId, sequence: point.sequence, observedAt: date(point.observedAt), cashUsd: point.cashUsd.toFixed(2), positionValueUsd: point.positionValueUsd.toFixed(2), equityUsd: point.equityUsd.toFixed(2), drawdownPercent: point.drawdownPercent.toFixed(4), exposurePercent: point.exposurePercent.toFixed(4) }))); await audit(userId, `backtest-completed:${runId}`, "BACKTEST_COMPLETED", { runId, runFingerprint, metrics: result.metrics }, { strategyId, strategyRevisionId: strategy.revision.id, datasetId: dataset.id, runId }); return { id: runId, datasetId: dataset.id, ...result };
}

export async function getBacktestRun(userId: number, runId: number) { await requireEntitlement(userId); const db = await dbOrThrow(); const run = (await db.select().from(strategyBacktestRuns).where(and(eq(strategyBacktestRuns.userId, userId), eq(strategyBacktestRuns.id, runId))).limit(1))[0]; if (!run) throw new StrategyLabError("NOT_FOUND", "Backtest run not found."); const [trades, equityCurve] = await Promise.all([db.select().from(strategyBacktestTrades).where(eq(strategyBacktestTrades.runId, runId)).orderBy(strategyBacktestTrades.sequence), db.select().from(strategyBacktestEquityPoints).where(eq(strategyBacktestEquityPoints.runId, runId)).orderBy(strategyBacktestEquityPoints.sequence)]); return { id: run.id, strategyId: run.strategyId, datasetId: run.datasetId, engineVersion: run.engineVersion, status: run.status, initialEquityUsd: numberValue(run.initialEquityUsd), metrics: run.resultJson ? JSON.parse(run.resultJson) : null, createdAt: run.createdAt, completedAt: run.completedAt, trades: trades.map((trade) => ({ ...trade, quantity: numberValue(trade.quantity), entryPriceUsd: trade.entryPriceUsd === null ? null : numberValue(trade.entryPriceUsd), exitPriceUsd: trade.exitPriceUsd === null ? null : numberValue(trade.exitPriceUsd), netPnlUsd: trade.netPnlUsd === null ? null : numberValue(trade.netPnlUsd) })), equityCurve: equityCurve.map((point) => ({ observedAt: point.observedAt, equityUsd: numberValue(point.equityUsd), drawdownPercent: numberValue(point.drawdownPercent), exposurePercent: numberValue(point.exposurePercent) })), disclaimer: "Historical paper simulation only. No external order is submitted." }; }
export async function getBacktestDatasetCandles(userId: number, datasetId: number, limit: number, beforeSequence: number | null = null) { await requireEntitlement(userId); const db = await dbOrThrow(); const dataset = (await db.select().from(backtestDatasets).where(and(eq(backtestDatasets.userId, userId), eq(backtestDatasets.id, datasetId))).limit(1))[0]; if (!dataset) throw new StrategyLabError("NOT_FOUND", "Historical dataset not found."); const filter = beforeSequence === null ? eq(backtestDatasetCandles.datasetId, datasetId) : and(eq(backtestDatasetCandles.datasetId, datasetId), lt(backtestDatasetCandles.sequence, beforeSequence)); const rows = await db.select().from(backtestDatasetCandles).where(filter).orderBy(desc(backtestDatasetCandles.sequence)).limit(limit + 1); const { hasMoreOlder, page } = pageDescendingSequences(rows, limit); const candles = page.map((row) => ({ sequence: row.sequence, ...candleToHistorical(row) })); const expectedMs: Record<StrategyInterval, number> = { "5m": 300_000, "15m": 900_000, "1h": 3_600_000, "4h": 14_400_000, "1d": 86_400_000 }; const intervalMs = expectedMs[dataset.interval as StrategyInterval]; const gaps = candles.slice(1).flatMap((candle, index) => { const previous = candles[index]!; const expectedOpenTime = previous.openTime + intervalMs; return candle.openTime === expectedOpenTime ? [] : [{ afterSequence: previous.sequence, beforeSequence: candle.sequence, expectedOpenTime, observedOpenTime: candle.openTime }]; }); return { dataset: { id: dataset.id, symbol: dataset.symbol, interval: dataset.interval as StrategyInterval, provider: dataset.provider, candleFingerprint: dataset.candleFingerprint, candleCount: dataset.candleCount, rangeStart: dataset.rangeStart, rangeEnd: dataset.rangeEnd }, candles, page: { limit, beforeSequence, nextBeforeSequence: hasMoreOlder && candles.length ? candles[0]!.sequence : null, hasMoreOlder, expectedIntervalMs: intervalMs, gaps }, disclaimer: "Persisted historical OHLCV evidence only. Pagination does not alter the backtest dataset or its result." }; }

export async function getStrategyLabAuditHistory(userId: number, page: number, pageSize: number) { await requireEntitlement(userId); const db = await dbOrThrow(); const take = (page + 1) * pageSize; const rows = await db.select().from(strategyLabAuditEvents).where(eq(strategyLabAuditEvents.userId, userId)).orderBy(desc(strategyLabAuditEvents.createdAt)).limit(take); return { page, pageSize, events: rows.slice(page * pageSize, take), hasMore: rows.length === take }; }
