import { and, desc, eq, inArray } from "drizzle-orm";
import { backtestDatasetCandles, backtestDatasets, backtestRunComparisons, parameterSearchCandidates, parameterSearchPeriodResults, parameterSearches, strategyBacktestRuns, strategyBacktestTrades } from "../../drizzle/schema";
import { getDb } from "../db";
import { compareBacktestRuns, executeControlledParameterSearch, type ParameterSearchPlan } from "../strategy/research";
import { defaultFeatureAccess, featureEntitlementDefinitions, featureEntitlementKeys, type FeatureEntitlementKey } from "../strategy/entitlements";
import type { HistoricalCandle } from "../strategy/types";
import { getPaperStrategy, StrategyLabError } from "./strategyLab";
import { createHash } from "node:crypto";

const ENGINE_VERSION = "2.3.0";
function hash(value: unknown) { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function numberValue(value: unknown): number { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }
function idFrom(result: unknown): number { const row = Array.isArray(result) ? result[0] : result; const id = row && typeof row === "object" && "insertId" in row ? Number((row as { insertId?: unknown }).insertId) : NaN; if (!Number.isInteger(id) || id <= 0) throw new StrategyLabError("UNAVAILABLE", "Database did not return a persistent identifier."); return id; }
async function dbOrThrow() { const db = await getDb(); if (!db) throw new StrategyLabError("UNAVAILABLE", "Strategy Lab storage is temporarily unavailable."); return db; }
function candles(rows: Array<typeof backtestDatasetCandles.$inferSelect>): HistoricalCandle[] { return rows.map((row) => ({ openTime: row.openTime.getTime(), closeTime: row.closeTime.getTime(), open: numberValue(row.open), high: numberValue(row.high), low: numberValue(row.low), close: numberValue(row.close), volume: numberValue(row.volume), quoteVolumeUsd: numberValue(row.quoteVolumeUsd), tradeCount: row.tradeCount })); }
export function getFeatureEntitlementDefinitions() { return featureEntitlementKeys.map((key) => ({ ...featureEntitlementDefinitions[key], ...defaultFeatureAccess(key) })); }

export async function launchControlledParameterSearch(userId: number, input: { strategyId: number; datasetId: number; plan: ParameterSearchPlan }) {
  const strategy = await getPaperStrategy(userId, input.strategyId); const db = await dbOrThrow(); const dataset = (await db.select().from(backtestDatasets).where(and(eq(backtestDatasets.id, input.datasetId), eq(backtestDatasets.userId, userId))).limit(1))[0]; if (!dataset) throw new StrategyLabError("NOT_FOUND", "Verified dataset not found for this account."); const rows = await db.select().from(backtestDatasetCandles).where(eq(backtestDatasetCandles.datasetId, dataset.id)).orderBy(backtestDatasetCandles.sequence); const datasetCandles = candles(rows); const fingerprint = hash({ strategyRevision: strategy.revision.fingerprint, dataset: dataset.candleFingerprint, plan: input.plan, engine: ENGINE_VERSION }); const existing = (await db.select().from(parameterSearches).where(and(eq(parameterSearches.userId, userId), eq(parameterSearches.searchFingerprint, fingerprint))).limit(1))[0]; if (existing) return getControlledParameterSearch(userId, existing.id);
  const output = executeControlledParameterSearch({ symbol: strategy.symbol, interval: strategy.interval, source: dataset.provider as "binance" | "coinbase" | "user_imported_unverified", datasetFingerprint: dataset.candleFingerprint, candles: datasetCandles, rules: strategy.revision.rules, risk: strategy.revision.risk, plan: input.plan }); const searchId = idFrom(await db.insert(parameterSearches).values({ userId, strategyId: strategy.id, strategyRevisionId: strategy.revision.id, datasetId: dataset.id, entitlementKey: "parameter_search", engineVersion: ENGINE_VERSION, searchFingerprint: fingerprint, status: "COMPLETED", parameterPlanJson: JSON.stringify(input.plan), periodPlanJson: JSON.stringify(output.periods.map((period) => ({ label: period.label, startIndex: period.startIndex, endIndexExclusive: period.endIndexExclusive }))), candidateCount: output.candidates.length, robustnessJson: JSON.stringify(output.robustness), startedAt: new Date(datasetCandles[0]!.openTime), completedAt: new Date(datasetCandles.at(-1)!.closeTime) }));
  for (const candidate of output.candidates) { const candidateId = idFrom(await db.insert(parameterSearchCandidates).values({ searchId, sequence: candidate.sequence, candidateFingerprint: candidate.fingerprint, parameterJson: JSON.stringify(candidate.parameters), status: "COMPLETED", resultJson: JSON.stringify({ warnings: candidate.warnings }), rejectionReason: null })); await db.insert(parameterSearchPeriodResults).values(candidate.results.map((period) => ({ candidateId, period: period.period, rangeStart: new Date(period.result.startedAt), rangeEnd: new Date(period.result.completedAt), candleCount: period.result.equityCurve.length, metricsJson: JSON.stringify(period.result.metrics), warningJson: JSON.stringify(period.warnings) }))); }
  return getControlledParameterSearch(userId, searchId);
}

export async function getControlledParameterSearch(userId: number, searchId: number) { const db = await dbOrThrow(); const search = (await db.select().from(parameterSearches).where(and(eq(parameterSearches.id, searchId), eq(parameterSearches.userId, userId))).limit(1))[0]; if (!search) throw new StrategyLabError("NOT_FOUND", "Parameter search not found."); const candidates = await db.select().from(parameterSearchCandidates).where(eq(parameterSearchCandidates.searchId, search.id)).orderBy(parameterSearchCandidates.sequence); const ids = candidates.map((candidate) => candidate.id); const periods = ids.length ? await db.select().from(parameterSearchPeriodResults).where(inArray(parameterSearchPeriodResults.candidateId, ids)) : []; return { id: search.id, status: search.status, strategyId: search.strategyId, strategyRevisionId: search.strategyRevisionId, datasetId: search.datasetId, candidateCount: search.candidateCount, plan: JSON.parse(search.parameterPlanJson), robustness: search.robustnessJson ? JSON.parse(search.robustnessJson) : null, candidates: candidates.map((candidate) => ({ id: candidate.id, sequence: candidate.sequence, parameters: JSON.parse(candidate.parameterJson), status: candidate.status, warnings: candidate.resultJson ? JSON.parse(candidate.resultJson).warnings : [], periods: periods.filter((period) => period.candidateId === candidate.id).map((period) => ({ period: period.period, rangeStart: period.rangeStart, rangeEnd: period.rangeEnd, candleCount: period.candleCount, metrics: JSON.parse(period.metricsJson), warnings: JSON.parse(period.warningJson) })) })), disclaimer: "Controlled historical parameter research only. It does not prove future performance." };
}

export async function saveBacktestRunComparison(userId: number, runIds: number[]) { const uniqueIds = Array.from(new Set(runIds)).sort((left, right) => left - right); if (uniqueIds.length < 2 || uniqueIds.length > 5) throw new StrategyLabError("INVALID", "Select from 2 to 5 completed runs for comparison."); const db = await dbOrThrow(); const runs = await db.select().from(strategyBacktestRuns).where(and(eq(strategyBacktestRuns.userId, userId), inArray(strategyBacktestRuns.id, uniqueIds))); if (runs.length !== uniqueIds.length || runs.some((run) => run.status !== "COMPLETED" || !run.resultJson)) throw new StrategyLabError("INVALID", "Only completed owned runs with stored results can be compared."); const tradeRows = await db.select().from(strategyBacktestTrades).where(inArray(strategyBacktestTrades.runId, uniqueIds)); const datasets = await db.select().from(backtestDatasets).where(inArray(backtestDatasets.id, runs.map((run) => run.datasetId))); const datasetById = new Map(datasets.map((dataset) => [dataset.id, dataset])); const comparable = runs.sort((left, right) => uniqueIds.indexOf(left.id) - uniqueIds.indexOf(right.id)).map((run) => { const net = tradeRows.filter((trade) => trade.runId === run.id && trade.netPnlUsd !== null).map((trade) => numberValue(trade.netPnlUsd)); const metrics = JSON.parse(run.resultJson!); const dataset = datasetById.get(run.datasetId); return { id: run.id, strategyRevisionNumber: run.strategyRevisionId, datasetFingerprint: dataset?.candleFingerprint ?? "UNAVAILABLE", rangeStart: dataset?.rangeStart.getTime() ?? 0, rangeEnd: dataset?.rangeEnd.getTime() ?? 0, interval: dataset?.interval ?? "UNAVAILABLE", runConfig: JSON.parse(run.runConfigJson), metrics, averageTradeUsd: net.length ? net.reduce((sum, value) => sum + value, 0) / net.length : null, returnToDrawdownRatio: metrics.maxDrawdownPercent > 0 ? metrics.netPnlPercent / metrics.maxDrawdownPercent : null }; }); const comparison = compareBacktestRuns(comparable); const fingerprint = hash({ runIds: uniqueIds, comparison }); const existing = (await db.select().from(backtestRunComparisons).where(and(eq(backtestRunComparisons.userId, userId), eq(backtestRunComparisons.comparisonFingerprint, fingerprint))).limit(1))[0]; if (existing) return { id: existing.id, ...JSON.parse(existing.comparisonJson), reused: true as const }; const id = idFrom(await db.insert(backtestRunComparisons).values({ userId, comparisonFingerprint: fingerprint, runIdsJson: JSON.stringify(uniqueIds), comparisonJson: JSON.stringify(comparison) })); return { id, ...comparison, reused: false as const };
}

export async function listVerifiedDatasets(userId: number) { const db = await dbOrThrow(); const datasets = await db.select().from(backtestDatasets).where(eq(backtestDatasets.userId, userId)).orderBy(desc(backtestDatasets.createdAt)).limit(100); return datasets.map((dataset) => ({ id: dataset.id, symbol: dataset.symbol, interval: dataset.interval, provider: dataset.provider, rangeStart: dataset.rangeStart, rangeEnd: dataset.rangeEnd, candleCount: dataset.candleCount, fingerprint: dataset.candleFingerprint, sourceStatus: dataset.provider === "user_imported_unverified" ? "USER_IMPORTED_UNVERIFIED" : "PUBLIC_PROVIDER" })); }
export async function listRecentBacktestRuns(userId: number) { const db = await dbOrThrow(); const rows = await db.select().from(strategyBacktestRuns).where(eq(strategyBacktestRuns.userId, userId)).orderBy(desc(strategyBacktestRuns.createdAt)).limit(50); return rows.map((run) => ({ id: run.id, strategyId: run.strategyId, strategyRevisionId: run.strategyRevisionId, datasetId: run.datasetId, status: run.status, createdAt: run.createdAt, metrics: run.resultJson ? JSON.parse(run.resultJson) : null, runConfig: JSON.parse(run.runConfigJson) })); }
