export interface CandleAnalysisInput { open: number; high: number; low: number; close: number; volume?: number; }
export type CandleDirection = "BULLISH" | "BEARISH" | "FLAT";
export type CandlePattern = "DOJI" | "BULLISH" | "BEARISH" | "FLAT" | "UNAVAILABLE";
function validPeriod(period: number) { return Number.isSafeInteger(period) && period >= 2 && period <= 300; }
function validCandle(candle: CandleAnalysisInput) { return Number.isFinite(candle.open) && Number.isFinite(candle.high) && Number.isFinite(candle.low) && Number.isFinite(candle.close) && candle.low <= candle.open && candle.low <= candle.close && candle.high >= candle.open && candle.high >= candle.close; }
function round(value: number, precision = 8) { const factor = 10 ** precision; return Math.round((value + Number.EPSILON) * factor) / factor; }
export function calculateSmaSeries(candles: CandleAnalysisInput[], period: number): Array<number | null> { const output: Array<number | null> = Array(candles.length).fill(null); if (!validPeriod(period) || candles.some((candle) => !validCandle(candle))) return output; let sum = 0; for (let index = 0; index < candles.length; index += 1) { sum += candles[index]!.close; if (index >= period) sum -= candles[index - period]!.close; if (index >= period - 1) output[index] = round(sum / period); } return output; }
export function calculateAtrSeries(candles: CandleAnalysisInput[], period: number): Array<number | null> { const output: Array<number | null> = Array(candles.length).fill(null); if (!validPeriod(period) || candles.some((candle) => !validCandle(candle)) || candles.length < period + 1) return output; const ranges: number[] = []; for (let index = 1; index < candles.length; index += 1) { const current = candles[index]!; const previous = candles[index - 1]!; ranges.push(Math.max(current.high - current.low, Math.abs(current.high - previous.close), Math.abs(current.low - previous.close))); } let atr = ranges.slice(0, period).reduce((sum, value) => sum + value, 0) / period; output[period] = round(atr); for (let index = period; index < ranges.length; index += 1) { atr = ((atr * (period - 1)) + ranges[index]!) / period; output[index + 1] = round(atr); } return output; }
export function classifyCandleEvidence(candle: CandleAnalysisInput) { if (!validCandle(candle)) return { status: "UNAVAILABLE" as const, direction: null, pattern: "UNAVAILABLE" as CandlePattern, bodySize: null, upperWick: null, lowerWick: null, range: null, reason: "Candle OHLC is invalid." }; const bodySize = Math.abs(candle.close - candle.open); const upperWick = candle.high - Math.max(candle.open, candle.close); const lowerWick = Math.min(candle.open, candle.close) - candle.low; const range = candle.high - candle.low; const direction: CandleDirection = candle.close > candle.open ? "BULLISH" : candle.close < candle.open ? "BEARISH" : "FLAT"; const pattern: CandlePattern = range > 0 && bodySize / range <= 0.1 ? "DOJI" : direction; return { status: "AVAILABLE" as const, direction, pattern, bodySize: round(bodySize), upperWick: round(upperWick), lowerWick: round(lowerWick), range: round(range), reason: pattern === "DOJI" ? "Body is at most 10% of the observed candle range." : "Direction is derived from the observed open and close." }; }
