import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { RadioTower } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import CandlestickChart, { type ChartAnnotation } from "@/components/CandlestickChart";
import ProviderCoverageTimeline from "@/components/ProviderCoverageTimeline";
import ChartTimeRangeSelector from "@/components/ChartTimeRangeSelector";
import VerifiedGapReportPanel from "@/components/VerifiedGapReportPanel";
import { trpc } from "@/lib/trpc";
import { mergeProgressiveCandles, type CandleGap, type ProgressiveCandle } from "@/lib/progressiveCandles";
import { clampSavedChartView } from "@/lib/chartViewRange";
import { type ChartViewport } from "@/lib/chartRangeSelection";
import { buildVerifiedGapReport } from "@/lib/verifiedGapReport";
import { mergeIncrementalOhlcv } from "@shared/liveCandleUpdate";
import { useLiveActiveCandle } from "@/hooks/useLiveMarketData";

type ExchangeInterval = "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
type ExchangeSource = "binance" | "coinbase";
type LiveInputCandle = { openTime: number; closeTime: number; open: number; high: number; low: number; close: number; volume: number; };
const intervalMs: Record<ExchangeInterval, number> = { "1m": 60_000, "5m": 300_000, "15m": 900_000, "1h": 3_600_000, "4h": 14_400_000, "1d": 86_400_000 };
const pageSize: Record<ExchangeInterval, number> = { "1m": 180, "5m": 180, "15m": 160, "1h": 120, "4h": 75, "1d": 120 };
const asProgressive = (candle: LiveInputCandle): ProgressiveCandle => ({ sequence: candle.openTime, ...candle });
const requestKey = (request: { direction: "older" | "newer"; startTime: number; endTime: number }) => `${request.direction}:${request.startTime}:${request.endTime}`;

export default function ProgressiveLiveCandles({ symbol, interval, source, initialCandles, initialSnapshotAt = null, sourceLabel, isStale = false, annotations = [] }: { symbol: string; interval: ExchangeInterval; source: ExchangeSource; initialCandles: LiveInputCandle[]; initialSnapshotAt?: number | null; sourceLabel?: string; isStale?: boolean; annotations?: ChartAnnotation[] }) {
  const { user } = useAuth(); const normalizedSymbol = symbol.trim().toUpperCase(); const expectedMs = intervalMs[interval]; const limit = pageSize[interval]; const key = useMemo(() => ({ assetSymbol: normalizedSymbol, source, interval }), [interval, normalizedSymbol, source]);
  const activeQuery = useLiveActiveCandle({ symbol: normalizedSymbol, interval, source, enabled: initialCandles.length > 0 }); const activeResponse = activeQuery.data; const activeResult = activeResponse?.success ? activeResponse.data : null;
  const initialCandleKey = initialCandles.map((candle) => `${candle.openTime}:${candle.closeTime}:${candle.open}:${candle.high}:${candle.low}:${candle.close}:${candle.volume}`).join("|"); const initialProgressive = useMemo(() => initialCandles.map(asProgressive), [initialCandleKey]); const activeCandleKey = activeResult ? `${activeResult.candle.openTime}:${activeResult.candle.closeTime}:${activeResult.candle.open}:${activeResult.candle.high}:${activeResult.candle.low}:${activeResult.candle.close}:${activeResult.candle.volume}` : ""; const activeProgressive = useMemo(() => activeResult ? asProgressive(activeResult.candle) : null, [activeCandleKey]);
  const [candles, setCandles] = useState<ProgressiveCandle[]>(() => initialCandles.map(asProgressive)); const [gaps, setGaps] = useState<CandleGap[]>([]); const [request, setRequest] = useState<{ direction: "older" | "newer"; startTime: number; endTime: number } | null>(null); const [hasMoreOlder, setHasMoreOlder] = useState(true); const [hasMoreNewer, setHasMoreNewer] = useState(true); const [integrityError, setIntegrityError] = useState<string | null>(null); const [providerMessage, setProviderMessage] = useState<string | null>(null); const [temporaryFailure, setTemporaryFailure] = useState<string | null>(null); const [invalidRange, setInvalidRange] = useState<string | null>(null); const [earliestBoundary, setEarliestBoundary] = useState(false); const [latestBoundary, setLatestBoundary] = useState(false); const [restoredViewport, setRestoredViewport] = useState<ChartViewport | null>(null); const [activeViewport, setActiveViewport] = useState<ChartViewport | null>(null); const [rangeAdjustment, setRangeAdjustment] = useState<string | null>(null); const handledRequest = useRef<string | null>(null); const appliedPreference = useRef<string | null>(null); const lastSavedViewport = useRef<string | null>(null); const latestActiveSnapshot = useRef(0); const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const preference = trpc.marketData.getChartViewPreference.useQuery(key, { enabled: Boolean(user), retry: false }); const savePreference = trpc.marketData.saveChartViewPreference.useMutation();
  const queryInput = useMemo(() => request ? { symbol: normalizedSymbol, interval, source, startTime: request.startTime, endTime: request.endTime, limit } : { symbol: normalizedSymbol, interval, source, startTime: 1, endTime: 2, limit }, [interval, limit, normalizedSymbol, request, source]); const page = trpc.marketData.liveHistoryPage.useQuery(queryInput, { enabled: request !== null, retry: false });
  const merge = useCallback((existing: ProgressiveCandle[], incoming: ProgressiveCandle[]) => { const merged = mergeProgressiveCandles(existing, incoming, expectedMs); setGaps(merged.gaps); setIntegrityError(merged.conflict); return merged.candles; }, [expectedMs]);
  useEffect(() => { const initial = mergeProgressiveCandles([], initialProgressive, expectedMs); setCandles(initial.candles); setGaps(initial.gaps); setIntegrityError(initial.conflict); setRequest(null); setHasMoreOlder(initialProgressive.length > 0); setHasMoreNewer(initialProgressive.length > 0); setProviderMessage(null); setTemporaryFailure(null); setInvalidRange(null); setEarliestBoundary(false); setLatestBoundary(false); setRestoredViewport(null); setActiveViewport(null); setRangeAdjustment(null); handledRequest.current = null; appliedPreference.current = null; lastSavedViewport.current = null; latestActiveSnapshot.current = 0; }, [expectedMs, interval, source, normalizedSymbol]);
  useEffect(() => { if (!initialProgressive.length || (initialSnapshotAt !== null && initialSnapshotAt < latestActiveSnapshot.current)) return; setCandles((existing) => { const updated = existing.length ? mergeIncrementalOhlcv(existing, initialProgressive, expectedMs) : { candles: initialProgressive, gaps: [] as ReturnType<typeof mergeIncrementalOhlcv<ProgressiveCandle>>["gaps"], conflict: null }; setGaps(updated.gaps.map((gap) => ({ afterSequence: gap.afterOpenTime, beforeSequence: gap.beforeOpenTime, expectedOpenTime: gap.expectedOpenTime, observedOpenTime: gap.beforeOpenTime }))); setIntegrityError(updated.conflict); return updated.candles; }); }, [expectedMs, initialCandleKey, initialProgressive, initialSnapshotAt]);
  useEffect(() => { if (!activeProgressive || activeResult?.source !== source || activeResult.isStale || (initialSnapshotAt !== null && activeResult.cachedAt < initialSnapshotAt)) return; setCandles((existing) => { const updated = mergeIncrementalOhlcv(existing, [activeProgressive], expectedMs); if (updated.changed) latestActiveSnapshot.current = activeResult.cachedAt; setGaps(updated.gaps.map((gap) => ({ afterSequence: gap.afterOpenTime, beforeSequence: gap.beforeOpenTime, expectedOpenTime: gap.expectedOpenTime, observedOpenTime: gap.beforeOpenTime }))); setIntegrityError(updated.conflict); return updated.candles; }); }, [activeCandleKey, activeProgressive, activeResult, expectedMs, initialSnapshotAt, source]);
  useEffect(() => { if (!user || !preference.data || !candles.length) return; const saved = preference.data; const preferenceKey = `${saved.requestedStart}:${saved.requestedEnd}:${saved.visibleCandles}:${candles[0]!.openTime}:${candles.at(-1)!.openTime}`; if (appliedPreference.current === preferenceKey) return; const clamped = clampSavedChartView({ startTime: saved.requestedStart, endTime: saved.requestedEnd, visibleCandles: saved.visibleCandles }, candles, source === "coinbase" && interval === "4h" ? 75 : 300); if (!clamped) return; setRestoredViewport(clamped.viewport); setActiveViewport(clamped.viewport); if (clamped.adjusted) setRangeAdjustment("Saved chart range was adjusted to the currently verified provider coverage."); appliedPreference.current = preferenceKey; }, [candles, interval, preference.data, source, user]);
  useEffect(() => { if (!request || !page.error) return; const requestId = requestKey(request); if (handledRequest.current === requestId) return; handledRequest.current = requestId; setTemporaryFailure(page.error.message); setProviderMessage(`Temporary ${source} history request failure. Retry the boundary request; no provider boundary was inferred.`); }, [page.error, request, source]);
  useEffect(() => { if (!request || !page.data || handledRequest.current === requestKey(request)) return; const requestId = requestKey(request); if (!page.data.success) { handledRequest.current = requestId; if (page.data.error.code === "INVALID_HISTORY_RANGE") { setInvalidRange(page.data.error.message); setProviderMessage(`Invalid provider history range: ${page.data.error.message}`); } else { setTemporaryFailure(page.data.error.message); setProviderMessage(`Temporary ${source} history request failure. No coverage boundary was inferred.`); } return; }
    const response = page.data.data; if (response.request.source !== source || response.request.startTime !== request.startTime || response.request.endTime !== request.endTime) return; handledRequest.current = requestId; setTemporaryFailure(null); setInvalidRange(null);
    if (response.coverage.status === "EMPTY") { if (request.direction === "older") { setHasMoreOlder(false); setEarliestBoundary(true); } else { setHasMoreNewer(false); setLatestBoundary(true); } setProviderMessage(`Reached ${request.direction === "older" ? "earliest" : "latest"} available history confirmed by ${source}.`); return; }
    setCandles((existing) => { const boundary = request.direction === "older" ? existing[0]?.openTime : existing.at(-1)?.openTime; const incomingBoundary = request.direction === "older" ? response.candles[0]?.openTime : response.candles.at(-1)?.openTime; if (boundary !== undefined && incomingBoundary !== undefined && (request.direction === "older" ? incomingBoundary >= boundary : incomingBoundary <= boundary)) { setTemporaryFailure("The provider page did not extend the loaded boundary."); setProviderMessage("Provider returned a non-extending page. Retry is available; this is not a confirmed history boundary."); return existing; } return merge(existing, response.candles.map(asProgressive)); });
    if (response.coverage.status === "PARTIAL") setProviderMessage(`${source} returned partial coverage for this requested UTC window.`); else if (response.coverage.status === "GAPPED") setProviderMessage(`${source} returned verified interval gaps; no candle was reconstructed.`); else setProviderMessage(null);
  }, [merge, page.data, request, source]);
  const loadOlder = () => { const first = candles[0]; if (!first || page.isFetching || !hasMoreOlder) return; const endTime = first.openTime; const startTime = Math.max(1, endTime - expectedMs * limit); if (startTime >= endTime) { setInvalidRange("No valid earlier UTC window can be requested from this loaded timestamp."); return; } setRequest({ direction: "older", startTime, endTime }); };
  const loadNewer = () => { const last = candles.at(-1); if (!last || page.isFetching || !hasMoreNewer) return; const startTime = last.openTime + expectedMs; const endTime = Math.min(Date.now(), startTime + expectedMs * limit); if (startTime >= endTime) { setProviderMessage("No completed UTC window can be requested yet. This is not a confirmed provider boundary."); return; } setRequest({ direction: "newer", startTime, endTime }); };
  const persistViewport = useCallback((viewport: ChartViewport) => { if (!user) return; const viewportKey = `${viewport.startTime}:${viewport.endTime}:${viewport.visibleCandles}`; if (lastSavedViewport.current === viewportKey) return; if (saveTimer.current) clearTimeout(saveTimer.current); saveTimer.current = setTimeout(() => { lastSavedViewport.current = viewportKey; savePreference.mutate({ ...key, requestedStart: viewport.startTime, requestedEnd: viewport.endTime, visibleCandles: viewport.visibleCandles }); }, 500); }, [key, savePreference, user]);
  const handleViewportChange = useCallback((viewport: ChartViewport) => { setActiveViewport((current) => current?.startTime === viewport.startTime && current?.endTime === viewport.endTime && current?.visibleCandles === viewport.visibleCandles ? current : viewport); persistViewport(viewport); }, [persistViewport]);
  const handleRangeSelect = useCallback((viewport: ChartViewport | null, notice: string | null) => { setRangeAdjustment(notice); if (!viewport) return; setRestoredViewport(viewport); setActiveViewport(viewport); persistViewport(viewport); }, [persistViewport]);
  useEffect(() => () => { if (saveTimer.current) clearTimeout(saveTimer.current); }, []);
  if (integrityError) return <section className="rounded-xl border border-danger/30 bg-danger/10 p-4 text-sm text-danger" role="alert">Live history merge stopped: {integrityError} No conflicting provider candle was rendered.</section>;
  const earliest = candles[0]?.openTime ?? null; const latest = candles.at(-1)?.openTime ?? null; const currentViewport = activeViewport ?? (earliest !== null && latest !== null ? { startTime: earliest, endTime: latest, visibleCandles: Math.min(candles.length, limit) } : { startTime: 0, endTime: 0, visibleCandles: limit }); const gapReport = buildVerifiedGapReport({ provider: source, assetSymbol: normalizedSymbol, timeframe: interval, requestedRangeStart: currentViewport.startTime, requestedRangeEnd: currentViewport.endTime, verifiedRangeStart: earliest, verifiedRangeEnd: latest, expectedIntervalMs: expectedMs, gaps }); const chartCandles = useMemo(() => candles.map((candle) => ({ timestamp: candle.openTime, open: candle.open, high: candle.high, low: candle.low, close: candle.close, volume: candle.volume })), [candles]);
  return <section><div className="mb-2 flex flex-wrap items-center justify-between gap-2 text-xs text-foreground-muted"><span className="inline-flex items-center gap-1.5"><RadioTower className="size-3.5 text-primary" />Authenticated live provider history</span><span>{candles.length} loaded · {source} · UTC ranges{activeResult ? ` · active candle ${activeResult.isStale ? "cached" : "updated"} ${new Date(activeResult.cachedAt).toLocaleTimeString()}` : ""}</span></div><ProviderCoverageTimeline source={source} earliest={earliest} latest={latest} gaps={gaps} earliestBoundary={earliestBoundary} latestBoundary={latestBoundary} temporaryFailure={temporaryFailure} invalidRange={invalidRange} /><ChartTimeRangeSelector earliest={earliest} latest={latest} visibleCandles={currentViewport.visibleCandles} onSelect={handleRangeSelect} />{rangeAdjustment ? <p className="mt-2 rounded-lg border border-warning/25 bg-warning/10 px-3 py-2 text-xs text-warning" role="status">{rangeAdjustment}</p> : null}<div className="mt-2"><CandlestickChart data={chartCandles} symbol={normalizedSymbol} interval={interval} sourceLabel={sourceLabel ?? `${source} · provider historical range`} isStale={isStale || Boolean(activeResult?.isStale)} annotations={annotations} hasMoreOlder={hasMoreOlder} hasMoreNewer={hasMoreNewer} isLoadingOlder={page.isFetching && request?.direction === "older"} isLoadingNewer={page.isFetching && request?.direction === "newer"} onRequestOlder={loadOlder} onRequestNewer={loadNewer} gapCount={gaps.length} initialViewport={restoredViewport} onViewportChange={handleViewportChange} /></div><VerifiedGapReportPanel report={gapReport} /><p className="mt-2 text-xs text-foreground-muted">{providerMessage ?? `Adjacent ${source} UTC windows load only at chart boundaries. Coverage shows verified loaded data only; unverified ranges are never reconstructed.`}</p></section>;
}
