import React from "react";
import { CalendarRange, CircleAlert, RadioTower } from "lucide-react";
import type { CandleGap } from "@/lib/progressiveCandles";

function stamp(value: number | null) { return value === null ? "Not yet verified" : new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }

export default function ProviderCoverageTimeline({ source, earliest, latest, gaps, earliestBoundary, latestBoundary, temporaryFailure, invalidRange }: { source: "binance" | "coinbase"; earliest: number | null; latest: number | null; gaps: CandleGap[]; earliestBoundary: boolean; latestBoundary: boolean; temporaryFailure: string | null; invalidRange: string | null; }) {
  const span = earliest !== null && latest !== null ? Math.max(1, latest - earliest) : 1;
  return <section className="rounded-xl border border-border bg-background/40 px-3.5 py-3" aria-label="Provider historical coverage"><div className="flex flex-wrap items-center justify-between gap-2"><div className="inline-flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground-secondary"><RadioTower className="size-3.5 text-primary" />{source} coverage timeline</div><span className="font-mono text-[11px] text-foreground-muted">Verified loaded range only</span></div><div className="mt-3"><div className="relative h-3 overflow-hidden rounded-full border border-border bg-background-secondary" aria-label={`${source} verified historical coverage`}><div className="absolute inset-y-0 left-[7%] right-[7%] rounded-full bg-primary/35" />{gaps.map((gap) => { const left = earliest === null ? 0 : 7 + ((gap.expectedOpenTime - earliest) / span) * 86; const width = Math.max(1.2, ((gap.observedOpenTime - gap.expectedOpenTime) / span) * 86); return <span key={`${gap.afterSequence}:${gap.beforeSequence}`} className="absolute inset-y-0 rounded-sm bg-danger/80" style={{ left: `${Math.max(7, Math.min(93, left))}%`, width: `${Math.min(86, width)}%` }} title="Verified interval gap" />; })}</div><div className="mt-1.5 flex items-start justify-between gap-3 text-[10px] text-foreground-muted"><span className="max-w-[45%]">{earliestBoundary ? `Earliest confirmed ${source} boundary` : stamp(earliest)}</span><span className="max-w-[45%] text-right">{latestBoundary ? `Latest confirmed ${source} boundary` : stamp(latest)}</span></div></div><div className="mt-3 flex flex-wrap gap-x-3 gap-y-1.5 text-[11px] text-foreground-muted"><span className="inline-flex items-center gap-1"><i className="size-2 rounded-full bg-primary/60" />Verified provider coverage</span>{gaps.length ? <span className="inline-flex items-center gap-1 text-danger"><i className="size-2 rounded-sm bg-danger" />{gaps.length} verified gap{gaps.length === 1 ? "" : "s"}</span> : <span className="inline-flex items-center gap-1"><i className="size-2 rounded-sm border border-border bg-background-secondary" />No gap in loaded range</span>}<span className="inline-flex items-center gap-1"><i className="size-2 rounded-full border border-border bg-background-secondary" />Unverified outside loaded range</span></div>{temporaryFailure ? <p className="mt-3 flex items-start gap-1.5 rounded-lg border border-warning/25 bg-warning/10 px-2.5 py-2 text-xs text-warning"><CircleAlert className="mt-0.5 size-3.5 shrink-0" />Temporary provider request failure: {temporaryFailure}. This is not a coverage boundary.</p> : null}{invalidRange ? <p className="mt-3 flex items-start gap-1.5 rounded-lg border border-danger/25 bg-danger/10 px-2.5 py-2 text-xs text-danger"><CalendarRange className="mt-0.5 size-3.5 shrink-0" />Invalid or unavailable range: {invalidRange}</p> : null}</section>;
}
